### ISSUE TITLE
AttributeError on_decode_error callback 

### ISSUE THREAD

**Issue by glrs** [celery/kombu#1005]
Hi,

I try to build a robust consumer to log JSON messages. I also want to override the `on_decode_error()` to handle bad JSON messages. However, I get an `AttributeError`. The function waits for a `kombu.message.Message` object, but it actually seems to get a dict. I use Python 3.6 and kombu v4.2.2-post1. Here is what I do:

    from kombu import Connection, Exchange, Queue
    from kombu.mixins import ConsumerMixin

    url = 'amqp://...'
    exchange = Exchange('my_exchange', type='topic')
    queues = [Queue('my_queue', exchange, routing_key='my_key')]

    class Worker(ConsumerMixin):
        def __init__(self, connection, queues):
            self.connection = connection
            self.queues = queues

        def get_consumers(self, Consumer, channel):
            return [Consumer(queues=self.queues,
                             accept=['application/json'],
                             callbacks=[self.on_message, self.on_decode_error])]

        def on_message(self, body, msg):
            print('body: {0}'.format(body))
            msg.ack()

    with Connection(url, heartbeat=4) as conn:
        import sys
        try:
            worker = Worker(conn, queues)
            worker.run()
        except KeyboardInterrupt:
            print('KeyboardInterrupt. Bye!\n')
            conn.release()
            sys.exit(0)

The input messages look like this: '{"info":{"user_id":"0123456789","timestamp":1549551269539}}'
Here is the output:

```
body: {'info': {'user_id': '0123456789', 'timestamp': 1549551204939}}
body: {'info': {'user_id': '0123456789', 'timestamp': 1549551237114}}
body: {'info': {'user_id': '0123456789', 'timestamp': 1549551269539}}
Traceback (most recent call last):
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 218, in establish_connection
    yield conn
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 229, in Consumer
    yield conn, channel, c
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 182, in consumer_context
    yield connection, channel, consumers
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 192, in consume
    conn.drain_events(timeout=safety_interval)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/connection.py", line 506, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/method_framing.py", line 79, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/connection.py", line 510, in on_inbound_method
    method_sig, payload, content,
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/abstract_channel.py", line 126, in dispatch_method
    listener(*args)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/channel.py", line 1616, in _on_basic_deliver
    fun(msg)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/messaging.py", line 590, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "consumer.py", line 38, in on_decode_error
    super().on_decode_error(message, exc)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 152, in on_decode_error
    exc, message.content_type, message.content_encoding,
AttributeError: 'dict' object has no attribute 'content_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "consumer.py", line 43, in <module>
    worker.run()
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 170, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 203, in consume
    elapsed = 0
  File "/home/anasglar/anaconda3/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 182, in consumer_context
    yield connection, channel, consumers
  File "/home/anasglar/anaconda3/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 231, in Consumer
    self.on_consume_end(conn, channel)
  File "/home/anasglar/anaconda3/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 218, in establish_connection
    yield conn
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/connection.py", line 777, in __exit__
    self.release()
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/connection.py", line 358, in release
    self._close()
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/connection.py", line 324, in _close
    self._do_close_self()
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/connection.py", line 314, in _do_close_self
    self.maybe_close_channel(self._default_channel)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/connection.py", line 306, in maybe_close_channel
    channel.close()
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/channel.py", line 226, in close
    wait=spec.Channel.CloseOk,
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/abstract_channel.py", line 60, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/connection.py", line 506, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/method_framing.py", line 79, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/connection.py", line 510, in on_inbound_method
    method_sig, payload, content,
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/abstract_channel.py", line 126, in dispatch_method
    listener(*args)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/amqp/channel.py", line 1616, in _on_basic_deliver
    fun(msg)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/messaging.py", line 590, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "consumer.py", line 38, in on_decode_error
    super().on_decode_error(message, exc)
  File "/home/anasglar/anaconda3/lib/python3.6/site-packages/kombu/mixins.py", line 152, in on_decode_error
    exc, message.content_type, message.content_encoding,
AttributeError: 'dict' object has no attribute 'content_type'`
```

There are thousands of messages in the queue, and before it crashes I get 3 messages for some reason. Apart from solving this issue, I have a few more questions:
1) The JSON objects in the queue look fine, so the decoder should not be triggered. But it does. Why?
2) I have tried to override the `on_decode_error()` and print the message it gets before it crashes. It seems both `on_message()` and `on_decode_error()` get triggered on the same message. Shouldn't they be mutually exclusive? Is there a way to make them work like that? 
3) I thought the `on_message()` gets triggered for each message received, so since `on_decode_error()` gets also triggered, why do I get 3 messages printed instead of 1? Is that due to asynchronous-ness(?).

**EDIT**
Upgraded to kombu v4.3.0. The issue remains.

**Comment by glrs** [comment]
I've realized I didn't get that the `on_detect_error()` and `on_message()` are attributes of the Consumer (my bad, I don't even know how I missed that). So now I have changed my code to this:
```
def get_consumers(self, Consumer, channel):
        return [Consumer(queues=self.queues,
                         accept=['json'],
                         on_decode_error=kombu.Consumer.on_decode_error,
                         on_message=self.on_message,
                         prefetch_count=1)]
```
and I've added `kombu.disable_insecure_serializers()`.

My new problem is that `on_decode_error()` does not get triggered on bad JSONs or non-JSON data. That's probably something I haven't figured out yet, but if you think this is a Kombu issue I can create another thread for it. You can delete the current one, since it's not an actual issue; I was just too fast to create one...
