### ISSUE TITLE
In memory and on_error raises 'Channel' object has no attribute 'events

### ISSUE THREAD

**Issue by Gsantomaggio** [celery/kombu#1050]
Hi team,
The following code works without problems:

```python
def on_return(exception, exchange, routing_key, message):
    pass
conn = kombu.Connection('amqp://guest:guest@localhost//')
producer = conn.Producer(on_return=on_return)
producer.publish("Hello there!")
``` 

We have unit tests and we use memory transport, and the following code:
```python
def on_return(exception, exchange, routing_key, message):
    pass
conn = kombu.Connection('memory:////')
producer = conn.Producer(on_return=on_return)
producer.publish("Hello there!")
```

raises:

```python
/home/gabriele/git/OpenStack/.venv3.mandatory/bin/python3 /home/gabriele/git/OpenStack/oslo.messaging.mand/kombu_mem.py
Traceback (most recent call last):
  File "..kombu_mem.py", line 15, in <module>
    producer.publish("Hello there!")
  File "...venv3.mandatory/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "...venv3.mandatory/lib/python3.6/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/...venv3.mandatory/lib/python3.6/site-packages/kombu/messaging.py", line 212, in _get_channel
    channel.events['basic_return'].add(self.on_return)
AttributeError: 'Channel' object has no attribute 'events'
```

The `events` field is undefined.
Unless I missed something, I think this is a bug.
Thank you

**Comment by auvipy** [comment]
version?

**Comment by Gsantomaggio** [comment]
```
pip freeze | grep kombu
kombu==4.5.0
```

**Comment by Gsantomaggio** [comment]
I think that we can close this issue since the in-memory transport does not follow the AMQP standard and it is not possible to test the `mandatory` flag.

Here is an example:
```python
import time

from kombu import Connection, Exchange, Queue, Consumer

media_exchange = Exchange('media', 'direct')


def handle_message(body, message):
    print("%s RECEIVED MESSAGE: %r" % (time.time(), body))
    message.ack()



connection = Connection("memory:///")
producer = connection.Producer(serializer='json')
producer.publish({"foo": "bar"}, mandatory=True, routing_key="does_not_exist")
producer.publish({"foo1": "bar2"}, mandatory=True, routing_key="does_not_exist")
producer.publish({"foo2": "bar3"}, mandatory=True, routing_key="does_not_exist")
### by following the AMQP stadard the messages above have to be discared.
queue = Queue('does_not_exist')
consumer = Consumer(connection, [queue], callbacks=[handle_message])
consumer.consume()
connection.drain_events()
consumer.consume()
connection.drain_events()
consumer.consume()
connection.drain_events()
```

The messages are actually stored and consumed:

```bash
1560153333.555721 RECEIVED MESSAGE: {'foo': 'bar'}
1560153333.5558174 RECEIVED MESSAGE: {'foo1': 'bar2'}
1560153333.5558908 RECEIVED MESSAGE: {'foo2': 'bar3'}
```



So is not possible to use the `mandatory` flag.
