### ISSUE TITLE
hard pin on amqp hurts co-installability

### ISSUE THREAD

**Issue by prometheanfire** [celery/kombu#1105]
Is there a particular reason for the hard pin on amqp?  Hard pinning it prevents independent updating.

https://zuul.opendev.org/t/openstack/build/ba284e1ea9fd47ac9a19315b93edc701/log/job-output.txt#1067

If there IS a good reason for the hard pin, do you mind adding it to a comment in the requirements file?

```
2019-10-07 06:25:40.816806 | ubuntu-bionic | Checking upper-constraints.txt
2019-10-07 06:25:40.816882 | ubuntu-bionic | Checking conflicts for os-vif:
2019-10-07 06:25:40.817174 | ubuntu-bionic | ContextualVersionConflict: (amqp 2.5.2 (/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/lib/python2.7/site-packages), Requirement.parse('amqp==2.5.1'), set(['kombu']))
2019-10-07 06:25:40.817262 | ubuntu-bionic | Traceback (most recent call last):
2019-10-07 06:25:40.817489 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/openstack_requirements/cmds/check_conflicts.py", line 59, in main
2019-10-07 06:25:40.817576 | ubuntu-bionic |     pkg_resources.require(name)
2019-10-07 06:25:40.817828 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
2019-10-07 06:25:40.817942 | ubuntu-bionic |     needed = self.resolve(parse_requirements(requirements))
2019-10-07 06:25:40.818189 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
2019-10-07 06:25:40.818312 | ubuntu-bionic |     raise VersionConflict(dist, req).with_context(dependent_req)
2019-10-07 06:25:40.818600 | ubuntu-bionic | ContextualVersionConflict: (amqp 2.5.2 (/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/lib/python2.7/site-packages), Requirement.parse('amqp==2.5.1'), set(['kombu']))
```

**Comment by thedrow** [comment]
@auvipy I'm still not clear on why you hard pinned that version.
Can you please explain?

**Comment by prometheanfire** [comment]
just to be clear, if there's a reason to avoid 2.5.2 I'd like to know so we could consider masking it openstack wide as well.

**Comment by decaz** [comment]
@auvipy @thedrow I guess the problem is version 4.6.5 doesn't contain https://github.com/celery/kombu/commit/b51d1d678e198a80d7e5fd95f32674c7d8e04a75 but there is https://github.com/celery/kombu/blob/master/Changelog#L21.

**Comment by timkpaine** [comment]
I would like to know if this is necessary as well.

**Comment by prometheanfire** [comment]
ping?

**Comment by auvipy** [comment]
wait please

**Comment by auvipy** [comment]
https://github.com/celery/kombu/commit/19528addd753171317c5063f1fa1699378459b42
