### ISSUE TITLE
FrameError when creating a SimpleQueue

### ISSUE THREAD

**Issue by eranzim** [celery/kombu#1109]
Using kombu 4.6.5 (amqp 2.5.1) on Linux (almost certain it's Ubuntu), with rabbitmq-server 3.6.10-1,
I (occasionally, not always) get the following traceback from my code:
```
Traceback (most recent call last):
  .......
    return self.connection.SimpleQueue(Queue(routing_key, '', routing_key=routing_key, durable=False))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/connection.py", line 771, in SimpleQueue
    exchange_opts, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/simple.py", line 137, in __init__
    consumer = messaging.Consumer(channel, queue)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py", line 408, in revive
    self.declare()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py", line 421, in declare
    queue.declare()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/entity.py", line 609, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/entity.py", line 618, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/entity.py", line 653, in queue_declare
    nowait=nowait,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/channel.py", line 1149, in queue_declare
    spec.Queue.DeclareOk, returns_tuple=True,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/connection.py", line 504, in drain_events
    while not self.blocking_read(timeout):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/connection.py", line 510, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/connection.py", line 514, in on_inbound_method
    method_sig, payload, content,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/connection.py", line 644, in _on_close
    (class_id, method_id), ConnectionError)
FrameError: (0, 0): (501) FRAME_ERROR - type 1, first 16 octets = <<0,60,0,40,0,0,6,97,103,101,110,116,115,77,83,50>>: {invalid_frame_end_marker,
                                                                                1}
```

One second later (although the exact time might be related to my own code), I get the following (probably related) RecoverableConnectionError:
```
Traceback (most recent call last):
  .......
    self.producer.publish(json.dumps({.......}), routing_key, exchange=self.exchange)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/amqp/channel.py", line 1751, in _basic_publish
    'basic_publish: connection closed')
RecoverableConnectionError: basic_publish: connection closed
```

Thanks :)

**Comment by thedrow** [comment]
There's not enough information for us to debug this problem.
Please include more details and a test case we can use to reproduce the problem.
