### ISSUE TITLE
SQS transport does not recover from errors

### ISSUE THREAD

**Issue by sveniu** [celery/kombu#1143]
Using Kombu 4.6.7, Celery 4.4.0.

When recovering from a socket/connection error, the SQS transport does not start polling for messages again (using the ReceiveMessage API call).

Impact: Celery must be restarted after temporary network problems, to make SQS polling active again.

The error in question is `socket.gaierror` with `errno=-3` (`socket.EAI_AGAIN`) since the DNS name of the SQS queue times out during lookup. Other errors would probably cause the same symptom.

I simulate a network outage using iptables, dropping all packets coming from Celery running in a Docker container.

I have tried adding `socket.gaierror` and even `Exception` to the `SQS.Transport.connection_errors`, but without any change in behaviour.

Full error log:
```
[NOTE: Celery starts while the network is up]

[2020-01-02 12:38:46,301: INFO/MainProcess] Connected to sqs://AKIALALALA:**@localhost//
[2020-01-02 12:38:47,259: INFO/MainProcess] everything@47948fca7a9e ready.

[NOTE: At this point, the network becomes unavailable - all packets are silently dropped]

[2020-01-02 12:48:36,407: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/botocore/httpsession.py", line 262, in send
    chunked=self._chunked(request.headers),
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f3ca64b5080>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.6/dist-packages/kombu/asynchronous/hub.py", line 301, in create_loop
    item()
  File "/usr/local/lib/python3.6/dist-packages/vine/promises.py", line 170, in __call__
    return self.throw()
  File "/usr/local/lib/python3.6/dist-packages/vine/promises.py", line 167, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/SQS.py", line 336, in _schedule_queue
    queue, callback=promise(self._loop1, (queue,)),
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/SQS.py", line 352, in _get_bulk_async
    return self._get_async(queue, maxcount, callback=callback)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/SQS.py", line 363, in _get_async
    callback=transform(self._on_messages_ready, callback, q, queue),
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/SQS.py", line 383, in _get_from_sqs
    callback=callback,
  File "/usr/local/lib/python3.6/dist-packages/kombu/asynchronous/aws/sqs/connection.py", line 75, in receive_message
    queue_url = self.get_queue_url(queue)
  File "/usr/local/lib/python3.6/dist-packages/kombu/asynchronous/aws/sqs/connection.py", line 45, in get_queue_url
    res = self.sqs_connection.get_queue_url(QueueName=queue)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python3.6/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python3.6/dist-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python3.6/dist-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.6/dist-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python3.6/dist-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python3.6/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.6/dist-packages/botocore/httpsession.py", line 282, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://eu-west-1.queue.amazonaws.com/"

[NOTE: At this point, the network recovers]

[2020-01-02 12:50:06,135: INFO/MainProcess] Connected to sqs://AKIALALALA:**@localhost//

[NOTE: At this point, there is no SQS queue activity - no ReceiveMessage calls at all]
```

**Comment by sveniu** [comment]
I've been trying to dig further on this, but without success – I quickly lose track of where things happen in the code. Highlighting #1059 and #1064 hero @ebeseda in case he might have some pointers on this one.
