### ISSUE TITLE
Periodic task not scheduled when connection gone away.

### ISSUE THREAD

**Issue by hzlmn** [celery/kombu#1169]
Hello, guys first of all thanks for good tool!

When have sometime accidental rabbitmq stops seems like periodic tasks does not try to reconnect and than we get into the state where `channel.connection` is None as can be seen from traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 242, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 367, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 359, in apply_async
    **entry.options)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 755, in send_task
    self.backend.on_task_call(P, task_id)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/rpc.py", line 168, in on_task_call
    maybe_declare(self.binding(producer.channel), retry=True)
  File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 120, in maybe_declare
    return _imaybe_declare(entity, channel, **retry_policy)
  File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 171, in _imaybe_declare
    return entity.channel.connection.client.ensure(
celery.beat.SchedulingError: Couldn't apply scheduled task quotas_limits: 'NoneType' object has no attribute 'client
```
This case handled in `_maybe_declare` here https://github.com/celery/kombu/blob/master/kombu/common.py#L159 

but not in `_imaybe_declare` 
https://github.com/celery/kombu/blob/master/kombu/common.py#L169-L172

But as we used RPC results backend from celery it automatically set retry here
https://github.com/celery/celery/blob/master/celery/backends/rpc.py#L162-L168

As far as i understand `RecoverableConnectionError` should be raised here as well.

If it is reasonable i can work on PR.

**Comment by auvipy** [comment]
feel free with test case

**Comment by matusvalo** [comment]
The fix of this issue is breaking celery CI.
