### ISSUE TITLE
Failover connection is partially broken

### ISSUE THREAD

**Issue by matusvalo** [celery/kombu#1179]
Kombu contains failover connection functionality - see [1]. Currently it is partially broken (reproducible on master branch) - e.g.:

How to reproduce issue:

```python
from kombu import Connection, Producer, Consumer, Queue

test_queue = Queue('test', routing_key='test')

with Connection('amqp://broken_borker.example.com;amqp://broker.example.com') as conn:
    with conn.channel() as channel:
        producer = Producer(channel)
        producer.publish(
            {'hello': 'world'},
            retry=True,
            exchange=test_queue.exchange,
            routing_key=test_queue.routing_key,
            declare=[test_queue],
            serializer='pickle'
        )
```
**Expected Result**: Kombu should connect to `broker.example.com`
**Actual Result**: Kombu raises exception:
```
Traceback (most recent call last):
  File "/home/matus/environments/kombu37/lib/python3.7/site-packages/amqp/transport.py", line 137, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/matus/dev/kombu/kombu/connection.py", line 288, in channel
    chan = self.transport.create_channel(self.connection)
  File "/home/matus/dev/kombu/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/home/matus/dev/kombu/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/matus/dev/kombu/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/matus/environments/kombu37/lib/python3.7/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/home/matus/environments/kombu37/lib/python3.7/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/matus/environments/kombu37/lib/python3.7/site-packages/amqp/transport.py", line 148, in _connect
    "failed to resolve broker hostname"))
  File "/home/matus/environments/kombu37/lib/python3.7/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
socket.timeout: timed out
```

But as mentioned, for some usage of kombu library, the failover strategy works -e.g. working script:
```python
from kombu import Connection, Producer, Consumer, Queue

test_queue = Queue('test', routing_key='test')

with Connection('amqp://broken_borker.example.com;amqp://broker.exaple.com') as conn:
    with conn.default_channel as channel:
        producer = Producer(channel)
        producer.publish(
            {'hello': 'world'},
            retry=True,
            exchange=test_queue.exchange,
            routing_key=test_queue.routing_key,
            declare=[test_queue],
            serializer='pickle'
        )
```

The difference between working and broken version is that using `conn.default_channel` vs. `conn.channel()`

The root cause of issue is that  method `Connection.ensure_connection()` is called in `default_channel` property and not in `channel()` method.

[1] https://kombu.readthedocs.io/en/latest/reference/kombu.html#connection

**Comment by matusvalo** [comment]
There are multiple differences between `.default_channel` and `.channel()`:
1. `default_channel` is blocking vs. `channel()` raises an error when connection fails:
```python
from kombu import *
connection = Connection('redis://localhost:65534/')
connection.channel()              # <---- Raises redis.exceptions.ConnectionError
``` 

```python
from kombu import *
connection = Connection('redis://localhost:65534/')
connection.default_channel   # Blocks indefinitely
```

2. `default_channel`  and. `channel()` are raising different exceptions:
```python
from kombu import *
connection = Connection('redis://localhost:65534/',
connection.channel()             # <---- Raises  redis.exceptions.ConnectionError
```
```python
from kombu import *
connection = Connection('redis://localhost:65534/', transport_options={'max_retries':1})
connection.default_channel     # <----------- Raises kombu.exceptions.OperationalError
```
