### ISSUE TITLE
RecoverableConnectionError: connection already closed

### ISSUE THREAD

**Issue by bibek-bhattacharya** [celery/kombu#1208]
Note: Issue relates to both versions 4.6.9 and 4.6.10. Works as expected in 4.6.8.

We are seeing RecoverableConnectionError exceptions while calling clear() on a SimpleQueue object within a test cleanup fixture
<code>
CLEANUP-ERROR in cleanup_fixture: RecoverableConnectionError: connection already closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/behave/runner.py", line 222, in _do_cleanups
    cleanup_func()
  File "/usr/local/lib/python3.8/site-packages/behave/fixture.py", line 162, in cleanup_fixture
    next(func_it)           # CLEANUP-FIXTURE PART
  File "/app/clients/rabbitmq_client.py", line 64, in create_rabbitmq_queues
    SimpleQueue(context.rabbitmq_connection, queue).clear()
  File "/usr/local/lib/python3.8/site-packages/kombu/simple.py", line 137, in __init__
    consumer = messaging.Consumer(channel, queue)
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 408, in revive
    self.declare()
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 421, in declare
    queue.declare()
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 610, in declare
    self._create_exchange(nowait=nowait, channel=channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 617, in _create_exchange
    self.exchange.declare(nowait=nowait, channel=channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 183, in declare
    return (channel or self.channel).exchange_declare(
  File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 610, in exchange_declare
    self.send_method(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 56, in send_method
    raise RecoverableConnectionError('connection already closed')
amqp.exceptions.RecoverableConnectionError: connection already closed
</code>

**Comment by matusvalo** [comment]
I confirm the bug. Here is the minimal reproduction steps:
```python
from kombu import *
from kombu.simple import *
c = Connection('amqp://')
c.connect()
q = Queue('foo')
qq = q.bind(c.default_channel)
c.close()
SimpleQueue(c, q).clear()
```

Give me some time for investigation.

**Comment by bibek-bhattacharya** [comment]
Many thanks for looking into this.

**Comment by henrikek** [comment]
I think the following is the same problem you identified.

I'm using celery version 4.4.3

If RabbitMQ server is not running, you get an error message with kombu version 4.6.8 which is absolutely correct.

If you instead use kumbu version 4.6.9 or 4.6.10 then the process hangs forever and you get no error message which is a problem.

See two examples below:
kombu==4.6.8

```
[localhost]$ python
Python 3.8.3 (default, Jun  4 2020, 02:17:28)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from celery import current_app
>>> props = current_app.connection().connection.server_properties
Traceback (most recent call last):
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 136, in _connect
    entries = socket.getaddrinfo(
  File "/ESSArch/pd/python/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -9] Address family for hostname not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 145, in _connect
    raise (e
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
>>>
```

kumbu==4.6.9 or 4.6.10

```
[localhost]$ python
Python 3.8.3 (default, Jun  4 2020, 02:17:28)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from celery import current_app
>>> props = current_app.connection().connection.server_properties

##### hangs forever until I press ctrl-c #####

^CTraceback (most recent call last):
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 137, in _connect
    entries = socket.getaddrinfo(
  File "/ESSArch/pd/python/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -9] Address family for hostname not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 869, in _connection_factory
    connection = self._establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 805, in _establish_connection
    conn = self.transport.establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 146, in _connect
    raise (e
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 863, in connection
    self._connection = self._ensure_connection(**conn_opts)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 437, in _ensure_connection
    return retry_over_time(
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/utils/functional.py", line 358, in retry_over_time
    sleep(1.0)
KeyboardInterrupt
>>>
```

**Comment by matusvalo** [comment]
@henrikek your issue is side effect of the PR #1193. Before fix kombu has two channel factories:
* `channel()` method which returns immediately error when connection cannot be established to broker
* `default_channel` property which hands until connection will be established (but this can be modified by parameters)

The side effect of the PR is that it unifies the behavior (kombu blocks until it will get connection) but the problem is that semantics is changed.

**Comment by matusvalo** [comment]
@bibek-bhattacharya  I have created PR fixing your issue can you check if it fixes your problem?

**Comment by henrikek** [comment]
@matusvalo I also prefer semantics so I'll try some more and see what works best. Can I select "channel" or "default_channel" with the configuration parameter broker_transport_options in celery? and also choose how long timeout? Do you have an configuration example?

**Comment by matusvalo** [comment]
@henrikek you can modify the behavior using transport options - see:
https://github.com/celery/kombu/blob/574641e01fb284e3f5d5833da5fefd0e12d8b23a/kombu/connection.py#L841-L849

**Comment by henrikek** [comment]
@matusvalo Thanks it works great! I use the following code now:
```
[localhost]$ python
Python 3.8.3 (default, Jun  4 2020, 02:17:28)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from celery import current_app
>>> props = current_app.connection(transport_options={'max_retries':1}).connection.server_properties
Traceback (most recent call last):
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 137, in _connect
    entries = socket.getaddrinfo(
  File "/ESSArch/pd/python/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -9] Address family for hostname not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
    yield
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 437, in _ensure_connection
    return retry_over_time(
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 869, in _connection_factory
    connection = self._establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 805, in _establish_connection
    conn = self.transport.establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 146, in _connect
    raise (e
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ESSArch/pd/python/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 863, in connection
    self._connection = self._ensure_connection(**conn_opts)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 437, in _ensure_connection
    return retry_over_time(
  File "/ESSArch/pd/python/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 454, in _reraise_as_library_errors
    reraise(ConnectionError, ConnectionError(text_t(exc)),
  File "/ESSArch/pd/python/lib/python3.8/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
    yield
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 437, in _ensure_connection
    return retry_over_time(
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 869, in _connection_factory
    connection = self._establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/connection.py", line 805, in _establish_connection
    conn = self.transport.establish_connection()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 146, in _connect
    raise (e
  File "/ESSArch/pd/python/lib/python3.8/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
kombu.exceptions.OperationalError: [Errno 111] Connection refused
>>>
```

**Comment by bibek-bhattacharya** [comment]
> @bibek-bhattacharya I have created PR fixing your issue can you check if it fixes your problem?

Many thanks @matusvalo for fixing this. I have tested kombu branch:master on our environment. It works as expected now.
