### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by qasimzee** [celery/kombu#1212]
While consuming a message I get the following error:
```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/mixins.py", line 175, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/mixins.py", line 197, in consume
    conn.drain_events(timeout=safety_interval)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/connection.py", line 323, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 1001, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/SQS.py", line 174, in drain_events
    self._poll(self.cycle, callback, timeout=timeout)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 402, in _poll
    return cycle.get(callback)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/SQS.py", line 366, in _get_bulk
    for msg in self._messages_to_python(resp['Messages'], queue):
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/SQS.py", line 328, in _messages_to_python
    return [self._message_to_python(m, queue, q) for m in messages]
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/SQS.py", line 328, in <listcomp>
    return [self._message_to_python(m, queue, q) for m in messages]
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/site-packages/kombu/transport/SQS.py", line 284, in _message_to_python
    body = base64.b64decode(base64.b64decode(message['Body'].encode()))
  File "/home/vagrant/.virtualenvs/service/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

Please note that the messages in the queue are pure JSON and we don't have access to change them. 

It seems like at this line we [do not](https://github.com/celery/kombu/blob/75027490c71b83342f92b5293461c679233dc25e/kombu/transport/SQS.py#L285) base64 encode the message before decoding it, is it a good idea to patch it like:
`base64.b64decode(base64.b64encode(message['Body'].encode()))`

**Comment by auvipy** [comment]
are you up for a PR with a test?

**Comment by qasimzee** [comment]
For sure

**Comment by matusvalo** [comment]
@qasimzee  I am not sure if I understand the issue. Are you consuming data not produced by kombu library? I am asking because kombu producer should encode the message.

**Comment by qasimzee** [comment]
I think we can close it as the messages are not kombu messages. The messages are generated using a non-kombu producer. I am not sure if this repo should support them
