### ISSUE TITLE
The update on pypi.org two days ago caused celery to not be used normally

### ISSUE THREAD

**Issue by qtvspa** [celery/kombu#1235]
```
Traceback (most recent call last):
--
  | File "/app/.venv/bin/celery", line 8, in <module>
  | sys.exit(main())
  | File "/app/.venv/lib/python3.7/site-packages/celery/__main__.py", line 15, in main
  | from celery.bin.celery import main as _main
  | File "/app/.venv/lib/python3.7/site-packages/celery/bin/__init__.py", line 3, in <module>
  | from .base import Option
  | File "/app/.venv/lib/python3.7/site-packages/celery/bin/base.py", line 16, in <module>
  | from celery import VERSION_BANNER, Celery, maybe_patch_concurrency, signals
  | File "/app/.venv/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
  | module = __import__(self._object_origins[name], None, None, [name])
  | File "/app/.venv/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
  | from celery import _state
  | File "/app/.venv/lib/python3.7/site-packages/celery/_state.py", line 17, in <module>
  | from celery.utils.threads import LocalStack
  | File "/app/.venv/lib/python3.7/site-packages/celery/utils/__init__.py", line 18, in <module>
  | from .log import LOG_LEVELS
  | File "/app/.venv/lib/python3.7/site-packages/celery/utils/log.py", line 13, in <module>
  | from kombu.five import PY3, values
  | ModuleNotFoundError: No module named 'kombu.five'
```

**Comment by auvipy** [comment]
Which version of celery  kombu you are using

**Comment by qtvspa** [comment]
Both are the latest version.

**Comment by hashlib** [comment]
The same thing for me.
Celery 4.4.7, Kombu 5.0.0

**Comment by auvipy** [comment]
U should not use kombu 5 with celery 4.4.x version. Pin your requirements to kombu 4.x series for celery 4.4

**Comment by M0r13n** [comment]
I ran into the same problem. Pinning the version to `kombu == 4.6.11` solved my issue. Maybe you should add that information somewhere or mention it in the changelog.

**Comment by qtvspa** [comment]
Pinning the version to `4.6.11` solved my problem as well, but some of my projects that default to use the latest version may have the same problem..

**Comment by auvipy** [comment]
You should follow production environment files basic. How could you not pin dependency version? Have some sense.
