### ISSUE TITLE
mongodb connection URI - replicaset

### ISSUE THREAD

**Issue by ckhoo** [celery/kombu#125]
According to Mongodb doc (http://www.mongodb.org/display/DOCS/Connections), it is possible to connect to a replicaset using the following uri scheme mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

However, when I pass in "mongodb://localhost:27017,localhost:27018/db_name", I am getting
ValueError: invalid literal for int() with base 10: '27017,localhost'

I am on kombu version 2.1.7

Stack as below:

File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/celery/app/task/**init**.py", line 353, in delay
    return self.apply_async(args, kwargs)
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/celery/app/task/**init**.py", line 449, in apply_async
    publish = publisher or self.app.amqp.publisher_pool.acquire(block=True)
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/kombu/utils/**init**.py", line 229, in **get**
    value = obj.**dict**[self.**name**] = self.**get(obj)
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/celery/app/amqp.py", line 356, in publisher_pool
    return PublisherPool(self.app)
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/celery/app/amqp.py", line 260, in __init**
    super(PublisherPool, self).**init**(self.app.pool,
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/celery/app/base.py", line 347, in pool
    self._pool = self.broker_connection().Pool(
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/celery/app/base.py", line 234, in broker_connection
    **transport_options or {}))
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/kombu/connection.py", line 106, in __init__
    params.update(parse_url(hostname))
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/kombu/utils/url.py", line 34, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/site-packages/kombu/utils/url.py", line 26, in _parse_url
    int(parts.port) if parts.port else None,
  File "/Users/ckhoo/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/urlparse.py", line 106, in port
    return int(port, 10)
ValueError: invalid literal for int() with base 10: '27017,localhost'

**Comment by shahafabileah** [comment]
+1 on this issue

We're using kombu v3.0.24 and we're hitting the same error:
```
File "<snip>", line <snip>, in <snip> 
  async_result.backend = celery_rx.backend 
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/utils/__init__.py", line 322, in __get__ 
  value = obj.__dict__[self.__name__] = self.__get(obj) 
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 625, in backend 
  return self._get_backend() 
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 443, in _get_backend 
  self.loader) 
File "/app/.heroku/python/lib/python2.7/site-packages/celery/backends/__init__.py", line 62, in get_backend_by_url 
  backend, _, _, _, _, _, _ = _parse_url(url) 
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/utils/url.py", line 24, in _parse_url 
  return (scheme, unquote(parts.hostname or '') or None, parts.port, 
File "/app/.heroku/python/lib/python2.7/urlparse.py", line 113, in port 
  port = int(port, 10) 
ValueError: invalid literal for int() with base 10: <snip>
```

We're using http://compose.io as our Mongo host and they announced that they're about to do some maintenance.  During that maintenance period, the primary DB in the replica set will be unavailable.  So it's important to use a replicaset URL in order to avoid downtime.

I guess the recommendation for now is to downgrade to v3.0.16, right?  Are there any important fixes between .16 and .24 that we would be missing?

I think this task should be re-opened.

**Comment by lanecm** [comment]
+1 on this issue.

We're seeing the same error on kombu v3.0.24.

**Comment by shahafabileah** [comment]
I wrote a monkey-patch for this problem.  It's included below.  I've only done the most rudimentary testing with it so far, so I don't recommend you push it to production right away.  But I figured I'd post it here to (hopefully) get the conversation going.

Here's the patch, which I saved in a file `lib/patch_celery.py`:
```
# Celery has a bug that prevents it from correctly handling Mongo replica set
# URLs.
#
# Details here:
# https://github.com/celery/kombu/issues/125
#
# The code below is a patch for that bug, until a real fix is released.

def patch_celery():
    import celery.backends

    try:
        from urllib.parse import urlparse
    except ImportError:
        # noqa
        from urlparse import urlparse

    def patched_get_backend_by_url(backend=None, loader=None):
        url = None
        if backend and '://' in backend:
            url = backend
            if '+' in url[:url.index('://')]:
                backend, url = url.split('+', 1)
            else:
                # The patch is here.
                #
                # The original code used kombu.utils.url._parse_url.  That function
                # internally uses urllib.parse.urlparse.  But that code does not
                # handle Mongo replicaset URLs correctly.  Specifically, it blows
                # up when you try to access the property parts.port.  You get an
                # error like this:
                #
                #   ValueError: invalid literal for int() with base 10:
                #   '27017,localhost'
                #
                # I noticed that we don't really need a "full parse" here.  All we
                # need is the backend, which is the scheme.

                # ORIGINAL CODE
                # backend, _, _, _, _, _, _ = _parse_url(url)

                # NEW CODE
                backend = urlparse(url).scheme

        # ALSO NEW: I added the module name prefix here:
        return celery.backends.get_backend_cls(backend, loader), url

    celery.backends.get_backend_by_url = patched_get_backend_by_url
```

To use it, I make sure to run `patch_celery()` right after I import celery code in every process:
```
import celery
from lib.patch_celery import patch_celery
patch_celery()
```

To test it, I ran my app (which includes both a web process and a few celery processes) using a replicaset URL.  It seems that everything works -- no parse errors.  What I haven't verified yet is whether the replicaset is truly being used, and whether this setup can survive "step down" events from our host (compose.io).  If you happen to know something about that, please share.

**Comment by mikeywaites** [comment]
I believe i'm also seeing this issue on 3.0.35 using the SQS backend.

```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 9, in <module>
    load_entry_point('celery', 'console_scripts', 'celery')()
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/worker/__init__.py", line 124, in setup_instance
    self._conninfo = self.app.connection()
  File "/usr/local/lib/python3.4/site-packages/celery-3.1.23-py3.4.egg/celery/app/base.py", line 386, in connection
    'BROKER_CONNECTION_TIMEOUT', connect_timeout
  File "/usr/local/lib/python3.4/site-packages/kombu-3.0.35-py3.4.egg/kombu/connection.py", line 167, in __init__
    params.update(parse_url(hostname))
  File "/usr/local/lib/python3.4/site-packages/kombu-3.0.35-py3.4.egg/kombu/utils/url.py", line 32, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/usr/local/lib/python3.4/site-packages/kombu-3.0.35-py3.4.egg/kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "/usr/local/lib/python3.4/urllib/parse.py", line 156, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: XXXXXXXXXX
```

where the BROKER_URL is formed as per the docs.
`BROKER_URL = 'sqs://%s:%s@' % (AWS_ACCESS_ID, AWS_ACCESS_SECRET)`

**Comment by agordon** [comment]
Hello,

There's a catch for quoting SQS secret keys: they might contain slashes, and python's urllib's `quote` does not quote slashes by default (due to the `safe` parameter).

So this won't work:
```
from urllib.parse import quote

access_key="ABCDAFSDAFDSFASDA"
secret_key="Bd8543k+J43/FOO"
broker_url = 'sqs://%s:%s@' % (access_key, quote(secret_key))  # BAD

print(broker_url)
```
The URL *still* contains a slash: `sqs://ABCDAFSDAFDSFASDA:Bd8543k%2BJ43/FOO@`
and that will break the url parsing with the same error as above (`invalid literal for int()...`).

The correct solution (hopefully will be added in Celery's SQS docs) is to add the `safe` parameter to the `quote()` call:

```
from urllib.parse import quote

access_key="ABCDAFSDAFDSFASDA"
secret_key="Bd8543k+J43/FOO"
broker_url = 'sqs://%s:%s@' % (access_key, quote(secret_key, safe=''))

print(broker_url)
```

The resulting URL will then be: `sqs://ABCDAFSDAFDSFASDA:Bd8543k%2BJ43%2FFOO@`,
which works just fine.

HTH
- assaf
