### ISSUE TITLE
Unpickling of objects in python3, which have been serialized in python2, fails if they contain NumPy arrays or instances of datetime, date and time

### ISSUE THREAD

**Issue by LaughInJar** [celery/kombu#1250]
### Environment
kombu==4.6.11 (compatible with python2 and python3)
celery==4.4.6 (compatible with python2 and python3 and [celery config for Django isn't broken]
(https://github.com/celery/celery/issues/6323))
redis==3.5.3

redis-server 5.0.9
python 2.7.18 and python 3.6.11

Celery is configured to use pickle as serialization protocol (Django settings):
```python
CELERY_ACCEPT_CONTENT = [u"pickle"]
CELERY_TASK_SERIALIZER = u"pickle"
```

### Steps to reproduce:
Send a message in python2 containing a datetime object (e.g. via celery task).
Have a receiver using python3

In Python2:
```python
from myproj.tasks import MyTask
from datetime import datetime
MyTask().delay(timestamp=datetime.now()
```

In Python3
Have a celery worker in python3 to consume the task

### Expected Result
The message is deserialized sucessfully and the task executed

### Actual Result
The python3 worker will produce an exception like this:
```
[2020-09-14 18:11:27,390: CRITICAL/MainProcess] Can't decode message body: DecodeError(UnicodeDecodeError('ascii', b'\x07\xe4\t\x01', 1, 2, 'ordinal not in range(128)'),) [type:'application/x-python-serialize' encoding:'binary' headers:{'origin': '****6@****', 'root_id': '16ab5d23-3bf0-4db1-aa39-39677e4b19f1', 'expires': None, 'shadow': None, 'id': '16ab5d23-3bf0-4db1-aa39-39677e4b19f1', 'kwargsrepr': "{'timestamp': datetime.date(2020, 9, 1)}", 'lang': 'py', 'retries': 0, 'task': 'myproj.tasks.MyTask', 'group': None, 'timelimit': [None, None], 'parent_id': None, 'argsrepr': '()', 'eta': None}]

body: b'\x80\x02)}q\x01(U\x03endq\x02cdatetime\ndate\nq\x03U\x04\x07\xe4\t\x01\x85Rq\x04U\x04daysq\x05K\x00u}q\x06(X\x05\x00\x00\x00chordq\x07NX\t\x00\x00\x00callbacksq\x08NX\x08\x00\x00\x00errbacksq\tNX\x05\x00\x00\x00chainq\nNu\x87q\x0b.' (120b)
Traceback (most recent call last):
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 337, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 59, in pickle_loads
    return load(BytesIO(s))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 571, in on_task_received
    callbacks,
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/celery/worker/strategy.py", line 137, in task_message_handler
    if body is None and 'args' not in message.payload:
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/message.py", line 208, in payload
    return self._decoded_cache if self._decoded_cache else self.decode()
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/message.py", line 193, in decode
    self._decoded_cache = self._decode()
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/message.py", line 198, in _decode
    self.content_encoding, accept=self.accept)
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 337, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/****/Development/virtualenvs/myproj3/lib64/python3.6/site-packages/kombu/serialization.py", line 59, in pickle_loads
    return load(BytesIO(s))
kombu.exceptions.DecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)
```

### Suspected Cause

This is due to [this](https://docs.python.org/3/library/pickle.html):
```
Using encoding='latin1' is required for unpickling NumPy arrays and instances of datetime, date and time pickled by Python 2.
```

The `kombu.serialization.pickle_load` function looks like [this](https://github.com/celery/kombu/blob/56e88dc275831196ca396fce81275ac687d1207b/kombu/serialization.py#L58):
```python
def pickle_loads(s, load=pickle_load):
    # used to support buffer objects
    return load(BytesIO(s))
```
### Suggested Fix
```python
def pickle_loads(s, load=pickle_load):
    # used to support buffer objects
    return load(BytesIO(s), encoding="latin1")
```
Shouldn't cause any issues since `ascii` is a subset of `latin1`, but this hypothesis needs more verification.

### Workaround
I realize that I'm late with migrating to python3, so I understand if this ticket gets closed right away. I opened this ticket so that others who run into the same problem don't have to do the same work again. If this doesn't get fixed here is a sketch for a possible workaround:
```python
from io import BytesIO
from kombu.serialization import pickle_protocol
from kombu.serialization import registry
from kombu.serialization import pickle
from kombu.serialization import pickle_load

def pickle_dumps(obj):
    return pickle.dumps(obj, protocol=pickle_protocol)

def pickle_loads(s, load=pickle_load):
    return load(BytesIO(s), encoding=u"latin1")

registry.register(
    "pickle",
    pickle_dumps,
    pickle_loads,
    content_type="application/x-python-serialize",
    content_encoding="binary",
)
```

**Comment by thedrow** [comment]
While this is a valid bug report I don't think we should apply your proposed fix as it may (or may not) break other users' code.
I feel the risk is not worth it since you can register your own serializer.

Thank you for opening this issue.

**Comment by muratoguz** [comment]
This info solved our problem. Thanks.
