### ISSUE TITLE
Bump AMQP dependency to at least 5.0.5

### ISSUE THREAD

**Issue by hbielenia** [celery/kombu#1291]
Currently, Kombu release depends on AMQP >= 5.0.0, while master depends on 5.0.2. Unfortunately, both include buggy version 5.0.4 which causes ImportErrors like this one:

```
~> celery help
Traceback (most recent call last):
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/celery/__main__.py", line 14, in main
    from celery.bin.celery import main as _main
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/celery/bin/celery.py", line 14, in <module>
    from celery.app.utils import find_app
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/celery/app/__init__.py", line 2, in <module>
    from celery import _state
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/celery/utils/__init__.py", line 6, in <module>
    from kombu.utils.objects import cached_property
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/kombu/utils/__init__.py", line 4, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/kombu/utils/compat.py", line 16, in <module>
    from kombu.exceptions import reraise
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/kombu/exceptions.py", line 5, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/amqp/__init__.py", line 42, in <module>
    from .types import ChannelT, ConnectionT, MessageT
  File "/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/amqp/types.py", line 13, in <module>
    from .spec import method_sig_t
ImportError: cannot import name 'method_sig_t' from 'amqp.spec' (/home/hubiel/.local/share/virtualenvs/Web_UnArchive-T1Ij4Mo3/lib/python3.8/site-packages/amqp/spec.py)
```

Updating AMQP to 5.0.5 fixes this error.

**Comment by auvipy** [comment]
https://github.com/celery/kombu/pull/1292
