### ISSUE TITLE
5.1.0: sphinx warnings

### ISSUE THREAD

**Issue by kloczek** [celery/kombu#1347]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2
making output directory... done
loading intersphinx inventory from https://docs.python.org/dev/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/stable/objects.inv...
loading intersphinx inventory from https://docs.celeryproject.org/en/master/objects.inv...
loading intersphinx inventory from https://django-celery.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://cyme.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://amqp.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://vine.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://flower.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://redis-py.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://django.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://boto.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://sqlalchemy.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://kazoo.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://msgpack-python.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://basho.github.io/riak-python-client/objects.inv...
loading intersphinx inventory from http://sendapatch.se/projects/pylibmc/objects.inv...
loading intersphinx inventory from https://eventlet.net/doc/objects.inv...
loading intersphinx inventory from http://www.gevent.org/objects.inv...
loading intersphinx inventory from https://pyopenssl.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://doc.pytest.org/en/latest/objects.inv...
loading intersphinx inventory from https://tox.readthedocs.io/en/latest/objects.inv...
intersphinx inventory has moved: https://www.sphinx-doc.org/en/stable/objects.inv -> https://www.sphinx-doc.org/en/master/objects.inv
intersphinx inventory has moved: https://amqp.readthedocs.io/en/latest/objects.inv -> https://docs.celeryproject.org/projects/amqp/en/latest/objects.inv
intersphinx inventory has moved: https://django-celery.readthedocs.io/en/latest/objects.inv -> https://docs.celeryproject.org/projects/django-celery/en/latest/objects.inv
intersphinx inventory has moved: https://pyopenssl.readthedocs.io/en/stable/objects.inv -> https://www.pyopenssl.org/en/stable/objects.inv
building [mo]: all of 0 po files
building [man]: all source files
updating environment: [new config] 83 added, 0 changed, 0 removed
/usr/lib/python3.8/site-packages/sphinx/util/inspect.py:412: SAWarning: Unmanaged access of declarative attribute messages from non-mapped class Queue
  return getattr(obj, name, *defargs)
/usr/lib/python3.8/site-packages/sphinx/util/inspect.py:412: SAWarning: Unmanaged access of declarative attribute queue_id from non-mapped class Message
  return getattr(obj, name, *defargs)
reading sources... [100%] userguide/simple
Changelog.rst:672: WARNING: Inline strong start-string without end-string.
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Exchange.auto_delete:1: WARNING: duplicate object description of kombu.Exchange.auto_delete, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Exchange.delivery_mode:1: WARNING: duplicate object description of kombu.Exchange.delivery_mode, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Exchange.durable:1: WARNING: duplicate object description of kombu.Exchange.durable, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Exchange.name:1: WARNING: duplicate object description of kombu.Exchange.name, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Exchange.no_declare:1: WARNING: duplicate object description of kombu.Exchange.no_declare, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Exchange.type:1: WARNING: duplicate object description of kombu.Exchange.type, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Queue.auto_delete:1: WARNING: duplicate object description of kombu.Queue.auto_delete, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Queue.durable:1: WARNING: duplicate object description of kombu.Queue.durable, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Queue.exchange:1: WARNING: duplicate object description of kombu.Queue.exchange, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Queue.exclusive:1: WARNING: duplicate object description of kombu.Queue.exclusive, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Queue.name:1: WARNING: duplicate object description of kombu.Queue.name, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/entity.py:docstring of kombu.Queue.routing_key:1: WARNING: duplicate object description of kombu.Queue.routing_key, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Request:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Request, other instance in reference/kombu.asynchronous.aws.connection, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.Response.buffer:1: WARNING: duplicate object description of kombu.asynchronous.http.Response.buffer, other instance in reference/kombu.asynchronous.http, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.Response.code:1: WARNING: duplicate object description of kombu.asynchronous.http.Response.code, other instance in reference/kombu.asynchronous.http, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.Response.effective_url:1: WARNING: duplicate object description of kombu.asynchronous.http.Response.effective_url, other instance in reference/kombu.asynchronous.http, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.Response.error:1: WARNING: duplicate object description of kombu.asynchronous.http.Response.error, other instance in reference/kombu.asynchronous.http, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.Response.headers:1: WARNING: duplicate object description of kombu.asynchronous.http.Response.headers, other instance in reference/kombu.asynchronous.http, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.Response.request:1: WARNING: duplicate object description of kombu.asynchronous.http.Response.request, other instance in reference/kombu.asynchronous.http, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.Response.status:1: WARNING: duplicate object description of kombu.asynchronous.http.Response.status, other instance in reference/kombu.asynchronous.http, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Response.buffer:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Response.buffer, other instance in reference/kombu.asynchronous.http.base, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Response.code:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Response.code, other instance in reference/kombu.asynchronous.http.base, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Response.effective_url:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Response.effective_url, other instance in reference/kombu.asynchronous.http.base, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Response.error:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Response.error, other instance in reference/kombu.asynchronous.http.base, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Response.headers:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Response.headers, other instance in reference/kombu.asynchronous.http.base, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Response.request:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Response.request, other instance in reference/kombu.asynchronous.http.base, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/asynchronous/http/base.py:docstring of kombu.asynchronous.http.base.Response.status:1: WARNING: duplicate object description of kombu.asynchronous.http.base.Response.status, other instance in reference/kombu.asynchronous.http.base, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/exceptions.py:docstring of kombu.exceptions.ContentDisallowed:1: WARNING: duplicate object description of kombu.exceptions.ContentDisallowed, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/exceptions.py:docstring of kombu.exceptions.ContentDisallowed:1: WARNING: duplicate object description of kombu.exceptions.ContentDisallowed, other instance in reference/kombu.compat, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/messaging.py:docstring of kombu.messaging.Producer:1: WARNING: duplicate object description of kombu.messaging.Producer, other instance in reference/kombu, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/SQS.py:docstring of kombu.transport.SQS.QoS:1: WARNING: duplicate object description of kombu.transport.SQS.QoS, other instance in reference/kombu.transport.SQS, use :noindex: for one of them
WARNING: autodoc: failed to import module 'azureservicebus' from module 'kombu.transport'; the following exception was raised:
No module named 'azure'
WARNING: autodoc: failed to import module 'librabbitmq' from module 'kombu.transport'; the following exception was raised:
No module named 'librabbitmq'
WARNING: autodoc: failed to import module 'mongodb' from module 'kombu.transport'; the following exception was raised:
No module named 'pymongo'
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/pyamqp.py:docstring of kombu.transport.pyamqp.Channel:1: WARNING: duplicate object description of kombu.transport.pyamqp.Channel, other instance in reference/kombu.transport.pyamqp, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/pyamqp.py:docstring of kombu.transport.pyamqp.Message:1: WARNING: duplicate object description of kombu.transport.pyamqp.Message, other instance in reference/kombu.transport.pyamqp, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/pyamqp.py:docstring of amqp.channel.Channel.basic_qos:63: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of kombu.transport.pyamqp.Connection.negotiate_capabilities:7: WARNING: Unexpected indentation.
docstring of kombu.transport.pyamqp.Connection.negotiate_capabilities:9: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of kombu.transport.pyamqp.Connection.negotiate_capabilities:10: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/pyamqp.py:docstring of kombu.transport.pyamqp.Message:1: WARNING: duplicate object description of kombu.transport.pyamqp.Message, other instance in reference/kombu.transport.pyamqp, use :noindex: for one of them
WARNING: autodoc: failed to import class 'KombuBroker' from module 'kombu.transport.pyro'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'kombu.transport.pyro' has no attribute 'KombuBroker'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: KombuBroker

/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/qpid.py:docstring of kombu.transport.qpid.Channel:1: WARNING: duplicate object description of kombu.transport.qpid.Channel, other instance in reference/kombu.transport.qpid, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/virtual/base.py:docstring of kombu.transport.virtual.base.Message:1: WARNING: duplicate object description of kombu.transport.virtual.base.Message, other instance in reference/kombu.transport.qpid, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/qpid.py:docstring of kombu.transport.qpid.QoS:1: WARNING: duplicate object description of kombu.transport.qpid.QoS, other instance in reference/kombu.transport.qpid, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/virtual/base.py:docstring of kombu.transport.virtual.base.Message:1: WARNING: duplicate object description of kombu.transport.virtual.base.Message, other instance in reference/kombu.transport.qpid, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/qpid.py:docstring of kombu.transport.qpid.QoS:1: WARNING: duplicate object description of kombu.transport.qpid.QoS, other instance in reference/kombu.transport.qpid, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/virtual/base.py:docstring of kombu.transport.virtual.base.Message:1: WARNING: duplicate object description of kombu.transport.virtual.base.Message, other instance in reference/kombu.transport.qpid, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/redis.py:docstring of kombu.transport.redis.QoS:1: WARNING: duplicate object description of kombu.transport.redis.QoS, other instance in reference/kombu.transport.redis, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/transport/virtual/base.py:docstring of kombu.transport.virtual.base.Message:1: WARNING: duplicate object description of kombu.transport.virtual.base.Message, other instance in reference/kombu.transport.qpid, use :noindex: for one of them
docstring of kombu.transport.virtual.BrokerState.queue_index:3: WARNING: Unexpected indentation.
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/userguide/producers.rst:29: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 6 supplied.

.. code-block:: pycon
    >>> from kombu import Exchange

    >>> exchange = Exchange('name', type='direct')

    >>> producer.publish(
    ...      {'hello': 'world'},  # message to send
    ...      exchange=exchange,   # destination exchange
    ...      routing_key='rk',    # destination routing key,
    ...      declare=[exchange],  # make sure exchange is declared,
    ... )
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... kombu.1 { introduction userguide/index userguide/introduction userguide/connections userguide/producers userguide/consumers userguide/examples userguide/simple userguide/pools userguide/serialization userguide/failover faq reference/index reference/kombu reference/kombu.common reference/kombu.matcher reference/kombu.mixins reference/kombu.simple reference/kombu.clocks reference/kombu.compat reference/kombu.pidbox reference/kombu.exceptions reference/kombu.log reference/kombu.connection reference/kombu.message reference/kombu.compression reference/kombu.pools reference/kombu.abstract reference/kombu.resource reference/kombu.serialization reference/kombu.transport reference/kombu.transport.base reference/kombu.transport.virtual reference/kombu.transport.virtual.exchange reference/kombu.transport.azurestoragequeues reference/kombu.transport.azureservicebus reference/kombu.transport.pyamqp reference/kombu.transport.librabbitmq reference/kombu.transport.qpid reference/kombu.transport.memory reference/kombu.transport.redis reference/kombu.transport.mongodb reference/kombu.transport.consul reference/kombu.transport.etcd reference/kombu.transport.zookeeper reference/kombu.transport.filesystem reference/kombu.transport.sqlalchemy reference/kombu.transport.SQS reference/kombu.transport.SLMQ reference/kombu.transport.pyro reference/kombu.asynchronous reference/kombu.asynchronous.hub reference/kombu.asynchronous.semaphore reference/kombu.asynchronous.timer reference/kombu.asynchronous.debug reference/kombu.asynchronous.http reference/kombu.asynchronous.http.base reference/kombu.asynchronous.http.curl reference/kombu.asynchronous.aws reference/kombu.asynchronous.aws.connection reference/kombu.asynchronous.aws.sqs reference/kombu.asynchronous.aws.sqs.connection reference/kombu.asynchronous.aws.sqs.message reference/kombu.asynchronous.aws.sqs.queue reference/kombu.utils.amq_manager reference/kombu.utils.collections reference/kombu.utils.compat reference/kombu.utils.debug reference/kombu.utils.div reference/kombu.utils.encoding reference/kombu.utils.eventio reference/kombu.utils.functional reference/kombu.utils.imports reference/kombu.utils.json reference/kombu.utils.limits reference/kombu.utils.objects reference/kombu.utils.scheduling reference/kombu.utils.text reference/kombu.utils.time reference/kombu.utils.url reference/kombu.utils.uuid changelog } /home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/connection.py:docstring of kombu.connection.Connection:: WARNING: more than one target found for cross-reference 'Transport': kombu.transport.SLMQ.Transport, kombu.transport.SQS.Transport, kombu.transport.azurestoragequeues.Transport, kombu.transport.base.Transport, kombu.transport.consul.Transport, kombu.transport.etcd.Transport, kombu.transport.filesystem.Transport, kombu.transport.memory.Transport, kombu.transport.pyamqp.Transport, kombu.transport.pyamqp.Connection.Transport, kombu.transport.pyro.Transport, kombu.transport.qpid.Transport, kombu.transport.redis.Transport, kombu.transport.sqlalchemy.Transport, kombu.transport.virtual.Transport, kombu.transport.virtual.base.Transport, kombu.transport.zookeeper.Transport
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/connection.py:docstring of kombu.connection.Connection:: WARNING: more than one target found for cross-reference 'Transport': kombu.transport.SLMQ.Transport, kombu.transport.SQS.Transport, kombu.transport.azurestoragequeues.Transport, kombu.transport.base.Transport, kombu.transport.consul.Transport, kombu.transport.etcd.Transport, kombu.transport.filesystem.Transport, kombu.transport.memory.Transport, kombu.transport.pyamqp.Transport, kombu.transport.pyamqp.Connection.Transport, kombu.transport.pyro.Transport, kombu.transport.qpid.Transport, kombu.transport.redis.Transport, kombu.transport.sqlalchemy.Transport, kombu.transport.virtual.Transport, kombu.transport.virtual.base.Transport, kombu.transport.zookeeper.Transport
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/resource.py:docstring of kombu.resource.Resource.acquire:: WARNING: more than one target found for cross-reference 'LimitExceeded': kombu.exceptions.LimitExceeded, kombu.resource.Resource.LimitExceeded
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/resource.py:docstring of kombu.resource.Resource.acquire:: WARNING: more than one target found for cross-reference 'LimitExceeded': kombu.exceptions.LimitExceeded, kombu.resource.Resource.LimitExceeded
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/serialization.py:docstring of kombu.serialization.SerializerRegistry.loads:: WARNING: more than one target found for cross-reference 'ContentDisallowed': kombu.Queue.ContentDisallowed, kombu.exceptions.ContentDisallowed, kombu.compat.Consumer.ContentDisallowed, kombu.compat.ConsumerSet.ContentDisallowed
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/message.py:docstring of kombu.message.Message.ack:: WARNING: more than one target found for cross-reference 'MessageStateError': kombu.exceptions.MessageStateError, kombu.message.Message.MessageStateError, kombu.transport.pyamqp.Connection.Channel.Message.MessageStateError, kombu.transport.virtual.Message.MessageStateError
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/message.py:docstring of kombu.message.Message.reject:: WARNING: more than one target found for cross-reference 'MessageStateError': kombu.exceptions.MessageStateError, kombu.message.Message.MessageStateError, kombu.transport.pyamqp.Connection.Channel.Message.MessageStateError, kombu.transport.virtual.Message.MessageStateError
/home/tkloczko/rpmbuild/BUILD/kombu-5.1.0/docs/../kombu/message.py:docstring of kombu.message.Message.requeue:: WARNING: more than one target found for cross-reference 'MessageStateError': kombu.exceptions.MessageStateError, kombu.message.Message.MessageStateError, kombu.transport.pyamqp.Connection.Channel.Message.MessageStateError, kombu.transport.virtual.Message.MessageStateError
docstring of pycurl.Curl:1: WARNING: undefined label: curlobject
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.errstr:3: WARNING: undefined label: errstr_raw
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.errstr_raw:3: WARNING: undefined label: errstr_raw
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.getinfo:27: WARNING: undefined label: getinfo_raw
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.getinfo:36: WARNING: undefined label: getinfo_raw
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.getinfo:40: WARNING: undefined label: getinfo_raw
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.getinfo_raw:27: WARNING: undefined label: getinfo
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.getinfo_raw:31: WARNING: undefined label: getinfo
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.getinfo_raw:34: WARNING: undefined label: getinfo
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rb:3: WARNING: undefined label: perform
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rb:3: WARNING: undefined label: perform
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rb:10: WARNING: undefined label: perform_rs
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rs:3: WARNING: undefined label: perform
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rs:3: WARNING: undefined label: perform_rb
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rs:8: WARNING: undefined label: perform
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rs:15: WARNING: undefined label: perform
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.perform_rs:18: WARNING: undefined label: perform_rb
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.setopt:41: WARNING: undefined label: unicode
docstring of kombu.asynchronous.http.curl.CurlClient.Curl.setopt:89: WARNING: undefined label: curlshareobject
done
build succeeded, 80 warnings.
```

**Comment by kloczek** [comment]
Closing as this ticket is outdated.
