### ISSUE TITLE
Celery Heroku-redis possible kombu bug

### ISSUE THREAD

**Issue by hhartwell** [celery/kombu#1353]
Quick preface with super duper love kombu and all y'all do! 

We are trying to establish a connection to a heroku-redis from a celery worker running a django app inside a docker container, and it looks like there my be a bug popping up from some kombu jazz.

### here is the traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 311, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 398, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 404, in connection_for_read
    return self.ensure_connected(
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 430, in ensure_connected
    conn = conn.ensure_connection(
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 383, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 435, in _ensure_connection
    return retry_over_time(
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 313, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 879, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 814, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 938, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 920, in create_channel
    channel = self.Channel(connection)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 567, in __init__
    self.client.ping()
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/objects.py", line 29, in __get__
    return super().__get__(instance, owner)
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1050, in client
    return self._create_client(asynchronous=True)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1013, in _create_client
    return self.Client(connection_pool=self.async_pool)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1044, in async_pool
    self._async_pool = self._get_pool(asynchronous=True)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 1017, in _get_pool
    params = self._connparams(asynchronous=asynchronous)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 971, in _connparams
    connparams.update(conninfo.ssl)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
### from .env
```
CELERY_BROKER_USE_SSL = os.environ.get('BROKER_USE_SSL', False)
CELERY_REDIS_MAX_CONNECTIONS = 10
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'rediss://redis-host-here')
```
### and here are some celery conf settings
```
app.config_from_object('django.conf:settings', namespace='CELERY')
app.conf.broker_use_ssl = {"ssl_cert_reqs": ssl.CERT_NONE}
app.conf.redis_backend_use_ssl = {"ssl_cert_reqs": ssl.CERT_NONE}
```
We are using Celery 5.1.2 and Kombu 5.1.0.
we have also tried Celery <5 with Kombu 4.3.0 and that had the same result

We are able to get redis working with django-channels, but its pooping the bed with celery and kombu

again, love what yall do for us
we are pretty lost atm and not sure what other options we have. any help would be much appreciated

**Comment by hhartwell** [comment]
solved this and closing issue. our celery base settings were messing us up. we needed to remove this line from django settings.

`CELERY_BROKER_USE_SSL = os.environ.get('BROKER_USE_SSL', False)`
