### ISSUE TITLE
SQS worker errors our when Rejected

### ISSUE THREAD

**Issue by inai-shreyas** [celery/kombu#1358]
I get the following error when I raise a Reject exception

'str' object has no attribute 'headers'

full stacktrace:
```
[2021-07-22 16:01:04,309: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'str' object has no attribute 'headers'")
Traceback (most recent call last):
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 298, in create_loop
    item()
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/kombu/message.py", line 135, in reject_log_error
    self.reject(requeue=requeue)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/kombu/message.py", line 156, in reject
    self.channel.basic_reject(self.delivery_tag, requeue=requeue)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 671, in basic_reject
    self.qos.reject(delivery_tag, requeue=requeue)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/kombu/transport/SQS.py", line 179, in reject
    self.apply_backoff_policy(
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/kombu/transport/SQS.py", line 199, in apply_backoff_policy
    self.extract_task_name_and_number_of_retries(delivery_tag)
  File "/home/shreyas/.local/share/virtualenvs/inai-backend-mwrd66wz/lib/python3.8/site-packages/kombu/transport/SQS.py", line 213, in extract_task_name_and_number_of_retries
    message_headers = message.headers
AttributeError: 'str' object has no attribute 'headers'
```

When I fetched the actual message from SQS I found that some of the attributes were missing in the delivery tag. However in this case it fails even before it reaches that part. 

Please help.

**Comment by inai-shreyas** [comment]
All the attributes are available when message is actually received from sqs, but vanishes at the point where we extract them.

**Comment by inai-shreyas** [comment]
I think this https://github.com/celery/kombu/pull/1301/files PR itself has a bug.
>extract_task_name_and_number_of_retries
expected the actual message but we are passing in delivery_tag to it.

**Comment by thedrow** [comment]
We'd gladly accept a contribution to fix this issue.

**Comment by thedrow** [comment]
This is now fixed! Thanks for the bug report.
