### ISSUE TITLE
Redis regression with kombu 5.2.0

### ISSUE THREAD

**Issue by ddevault** [celery/kombu#1419]
Upon starting up a Celery worker to verify the new release:

```
[2021-11-05 10:41:38,224: CRITICAL/MainProcess] Unrecoverable error: TypeError("__init__() got an unexpected keyword argument 'username'")
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 916, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/redis/connection.py", line 988, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/lib/python3.9/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/usr/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 422, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/usr/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 428, in connection_for_read
    return self.ensure_connected(
  File "/usr/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 454, in ensure_connected
    conn = conn.ensure_connection(
  File "/usr/lib/python3.9/site-packages/kombu/connection.py", line 382, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/kombu/connection.py", line 434, in _ensure_connection
    return retry_over_time(
  File "/usr/lib/python3.9/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/kombu/connection.py", line 878, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/lib/python3.9/site-packages/kombu/connection.py", line 813, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 936, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 918, in create_channel
    channel = self.Channel(connection)
  File "/usr/lib/python3.9/site-packages/kombu/transport/redis.py", line 675, in __init__
    self.client.ping()
  File "/usr/lib/python3.9/site-packages/redis/client.py", line 1037, in ping
    return self.execute_command('PING')
  File "/usr/lib/python3.9/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/lib/python3.9/site-packages/redis/connection.py", line 990, in get_connection
    connection = self.make_connection()
  File "/usr/lib/python3.9/site-packages/redis/connection.py", line 1025, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'username'
```

**Comment by auvipy** [comment]
can you check the commit log to track it down?

**Comment by matusvalo** [comment]
I suppose this PR is pretty good candidate: #1351

**Comment by matusvalo** [comment]
The manual fix of this issue is to install redis-py >= 3.4.1. After upgrading it, it should work as expected.

**Comment by ddevault** [comment]
Confirmed fix on newer redis-py version. Thanks!

**Comment by NielkS** [comment]
The extra requirement is not propagated from `celery[redis]`: I have a project with a requirements file that look like this:
```
celery[redis]==5.1.0
redis==3.3.11
```
kombu is not mentioned purpose, I want to pick any version that match my requirements - but kombu 5.2.1 is the version that is currently picked and installed by pip.
I can work around this by either bumping redis version (i.e. `redis==3.4.1`) or explicitly adding `kombu==5.1.0`, but I was  expecting pip to manage this for me. Adding `kombu[redis]` (without a version) is not enough, pip does not seem to handle the additional version constraint on redis that was added in #1422. 

 Is that the expected behavior ? Maybe I just don't understand how pip resolves version constraints.

**Comment by matusvalo** [comment]
> Is that the expected behavior ? Maybe I just don't understand how pip resolves version constraints.

I think this is more question for pip project rather than here. Me personally, I don't know why it happens in this way (whether it is bug or expected behaviour)

**Comment by auvipy** [comment]
try latest pip and report the issue in pip github repo please. you can reference this issue for example.

**Comment by kaxil** [comment]
@auvipy I am seeing the same issues (same stracktrace) with the following dependencies:

```
kombu==5.2.1
celery==5.2.0
redis==3.5.3
```

Any ideas?

**Comment by auvipy** [comment]
Try celery 5.2.1 and upgrade redis version

**Comment by matusvalo** [comment]
Hi @kaxil . Not sure why. I checked the redis library and it do has username keyword argument of Connection. Could you please upgrade to redis 4.0.2. We are running tests against this version:
![image](https://user-images.githubusercontent.com/827060/145206758-0397cfd9-b98d-42f5-a8e3-71a2260d8c4e.png)

**Comment by kaxil** [comment]
@auvipy @matusvalo Celery 5.2.1 requires `redis < 4` right? So we can't update redis from 3.5.3, no ?

**Comment by kaxil** [comment]
Update: the user had 3.5.3 installed but then copied redis's `3.2.1` to site-packages which was causing the issue.

This is fixed now, thanks
