### ISSUE TITLE
Celery not working at Python3.8 

### ISSUE THREAD

**Issue by uannabi** [celery/kombu#1454]
### Celery stopped working when I deployed this webapp on AWS Elastic Beanstalk. I've tried to upgrade celery but, the issue remains the same. 

`File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/kombu/utils/objects.py", line 41, in _get_
    return obj._dict[self.name_]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/app/venv/staging-LQM1lest/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/_main_.py", line 15, in main
    sys.exit(_main())
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/bin/celery.py", line 205, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/click/core.py", line 829, in _call_
    return self.main(*args, **kwargs)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/bin/worker.py", line 136, in <lambda>
    callback=lambda ctx, _, value: value or ctx.obj.app.conf.worker_state_db,
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/utils/collections.py", line 112, in _getattr_
    return self[k]
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/utils/collections.py", line 420, in _getitem_
    return getitem(k)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/utils/collections.py", line 264, in _getitem_
    return mapping[_key]
  File "/usr/lib64/python3.8/collections/_init.py", line 1006, in __getitem_
    if key in self.data:
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/kombu/utils/objects.py", line 43, in _get_
    value = obj._dict[self.name] = self._get(obj)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/app/base.py", line 136, in data
    return self.callback()
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/app/base.py", line 897, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/app/base.py", line 907, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/loaders/base.py", line 128, in config_from_object
    self._conf = force_mapping(obj)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/celery/utils/collections.py", line 43, in force_mapping
    if isinstance(m, (LazyObject, LazySettings)):
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/conf/_init_.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/conf/_init.py", line 157, in __init_
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.8/importlib/_init_.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/app/current/backend/settings/_init_.py", line 5, in <module>
    from .components.database import *
  File "/var/app/current/backend/settings/components/database.py", line 13, in <module>
    'NAME': config('DB_NAME', cast=str),
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/decouple.py", line 199, in _call_
    return self.config(*args, **kwargs)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/decouple.py", line 83, in _call_
    return self.get(*args, **kwargs)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: DB_NAME not found. Declare it as envvar or define a default value.`

### Here is my all library 
`
amqp==5.0.1
asgiref==3.3.1
attrs==19.3.0
bcrypt==3.1.7
billiard==3.6.3.0
blessed==1.17.2
boto==2.49.0
boto3==1.16.7
botocore==1.19.7
cached-property==1.5.1
celery==5.0.1
cement==2.8.2
certifi==2019.11.28
cffi==1.15.0
chardet==3.0.4
click==7.1.2
click-didyoumean==0.0.3
click-repl==0.1.6
coreapi==2.3.3
coreschema==0.0.4
Django==2.2.18
django-celery-beat==2.1.0
django-constance==2.6.0
django-cors-headers==3.2.1
django-extensions==3.0.9
django-kombu==0.9.4
django-redis==4.11.0
django-rq==2.3.2
django-storages==1.10.1
django-taggit==1.3.0
django-timezone-field==4.0
djangorestframework==3.11.0
docutils==0.16
gunicorn==20.1.0
idna==2.8
importlib-metadata==2.0.0
inflection==0.5.1
itypes==1.2.0
Jinja2==2.11.3
jmespath==0.10.0
kombu==5.0.2
MarkupSafe==1.1.1
numpy==1.19.4
openapi-codec==1.3.2
packaging==20.9
pandas==1.1.4
Pillow==8.1.1
prompt-toolkit==3.0.8
psycopg2-binary==2.8.6
pycparser==2.21
pyparsing==2.4.7
python-crontab==2.5.1
python-dateutil==2.8.1
python-decouple==3.3
pytz==2019.3
PyYAML==5.4.1
redis==3.4.1
requests==2.22.0
rq==1.4.3
ruamel.yaml==0.16.13
ruamel.yaml.clib==0.2.2
s3transfer==0.3.3
simplejson==3.17.0
six==1.15.0
sqlparse==0.3.0
uritemplate==3.0.1
urllib3==1.25.8
vine==5.0.0
wcwidth==0.2.5
zipp==3.4.0`

**Comment by auvipy** [comment]
> File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/decouple.py", line 68, in get
> raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
> decouple.UndefinedValueError: DB_NAME not found. Declare it as envvar or define a default value.`

it is clear that its a problem on your conf not celery. also please use the latest release

**Comment by uannabi** [comment]
> > File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/decouple.py", line 68, in get
> > raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
> > decouple.UndefinedValueError: DB_NAME not found. Declare it as envvar or define a default value.`
> 
> it is clear that it's a problem on your conf, not celery. also please use the latest release

Thank you so much for your support and expert opinion. But I'm really confused, why the same copy of code work on python 3.6 and is not working on 3.8. Conf file same, Same Os, Same Architecture. The only difference is the Python version. Oh, Yes, I've tried upgrading celery's latest version.
