### ISSUE TITLE
No module named 'vine.five'

### ISSUE THREAD

**Issue by caleb15** [celery/kombu#1480]
Not sure why this was never reported but for a long time v5 of vine has been breaking installs. See https://github.com/mozilla/MozDef/issues/1678 and https://stackoverflow.com/questions/32757259/celery-no-module-named-five/63774459

It just happened to us too. 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/********/project/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/********/project/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/********/project/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "/home/********/project/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/********/project/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/********/project/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/********/.pyenv/versions/3.7.12/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/********/project/ff/__init__.py", line 18, in <module>
    from ff.celery_tasks import app as celery_app  # noqa
  File "/home/********/project/ff/celery_tasks.py", line 10, in <module>
    app = celery.Celery('ff')
  File "/home/********/project/venv/lib/python3.7/site-packages/celery/local.py", line 470, in __getattr__
    [name])
  File "/home/********/project/venv/lib/python3.7/site-packages/celery/app/__init__.py", line 2, in <module>
    from celery import _state
  File "/home/********/project/venv/lib/python3.7/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/home/********/project/venv/lib/python3.7/site-packages/celery/utils/__init__.py", line 6, in <module>
    from kombu.utils.objects import cached_property
  File "/home/********/project/venv/lib/python3.7/site-packages/kombu/utils/__init__.py", line 5, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/home/********/project/venv/lib/python3.7/site-packages/kombu/utils/compat.py", line 16, in <module>
    from kombu.five import reraise
  File "/home/********/project/venv/lib/python3.7/site-packages/kombu/five.py", line 6, in <module>
    import vine.five
ModuleNotFoundError: No module named 'vine.five'
```

**Comment by caleb15** [comment]
wait, looks like kombu removed references to five in https://github.com/celery/kombu/commit/1916b815f88551138ff26eda3e4af4c519c893e3#diff-f29e90d1926b0c9801f74a90de0c7410960c998fda329785546b7f7ccbd49600. I think upgrading our version of kombu to latest will fix this.

**Comment by caleb15** [comment]
Yep, that fixed it.
