### ISSUE TITLE
KeyError: 'ApproximateReceiveCount' in localstack when try to use celery with 'backoff_policy' in broker_transport_options

### ISSUE THREAD

**Issue by MaximMalyavkoSolbeg** [celery/kombu#1555]
I try to use Celery with SQS (locally on localstack, latest version 0.14.2).
When I run worker 
```python
celery -A celery_django worker --loglevel=info
```
and after that run task via manage.py shell
```python
from celery_django.celery import add
task = add.delay(1, 0)
```
I receive error:
```
task = add.delay(1, 0)[2022-06-15 05:48:10,356: INFO/MainProcess] Task celery_django.celery.add[3ab85e98-e95e-4dc0-b8b6-dd6054dc7201] received                                                                                              
[2022-06-15 05:48:10,360: ERROR/ForkPoolWorker-8] Task celery_django.celery.add[3ab85e98-e95e-4dc0-b8b6-dd6054dc7201] raised unexpected: ZeroDivisionError('division by zero')
Traceback (most recent call last):                                                                                                                                            
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task                                     
    R = retval = fun(*args, **kwargs)                                                                                                                                         
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__                             
    return self.run(*args, **kwargs)
  File "/home/maxim/sqscelery/celery_django/celery_django/celery.py", line 81, in add
    return x / y
ZeroDivisionError: division by zero
[2022-06-15 05:48:10,362: CRITICAL/MainProcess] Unrecoverable error: KeyError('ApproximateReceiveCount')
Traceback (most recent call last):
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/kombu/message.py", line 160, in reject
    self.channel.basic_reject(self.delivery_tag, requeue=requeue)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 665, in basic_reject
    self.qos.reject(delivery_tag, requeue=requeue)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/kombu/transport/SQS.py", line 186, in reject
    self.apply_backoff_policy(
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/kombu/transport/SQS.py", line 206, in apply_backoff_policy
    self.extract_task_name_and_number_of_retries(delivery_tag)
  File "/home/maxim/.local/share/virtualenvs/sqscelery-OdBKA3Z5/lib/python3.8/site-packages/kombu/transport/SQS.py", line 223, in extract_task_name_and_number_of_retries
    message.properties['delivery_info']['sqs_message']
KeyError: 'ApproximateReceiveCount'

```

My code and configuration:
```
Python 3.8.10

celery[sqs]==5.2.7
boto3==1.24.8
botocore==1.27.8
kombu==5.2.4
```

celery.py

```python
from celery import Celery

app = Celery("my_celery")

app.conf.broker_url = "sqs://test:test@localhost:4566"

app.conf.broker_transport_options = {
    'predefined_queues': {
        'celery': {
            'url': 'http://localhost:4566/000000000000/celery',
            'access_key_id': 'test',
            'secret_access_key': 'test',
            'backoff_policy': {1: 10, 2: 20, 3: 40, 4: 80},
            'backoff_tasks': ['celery_django.celery.add']
        },
    },
}


@app.task(acks_late=True, acks_on_failure_or_timeout=False)
def add(x, y):
    return x / y
```

localstack docker

```docker
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs:4576,s3
      - DATA_DIR=/tmp/localstack/data
      - USE_SSL=false
    ports:
      - '4566:4566'
      - '4576:4576'
      - '4572:4572'
      - '8055:8080'
      - '9001:9001'
    volumes:
      - ./localstack/s3:/docker-entrypoint-initaws.d
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls | grep -i "test"
      interval: 5s
      timeout: 10s
      start_period: 10s
    networks:
      - backend
```

entrypoint-initaws.d
```bash
#!/bin/bash
set -x
awslocal s3 mb s3://test
awslocal s3api put-bucket-acl --bucket test --acl public-read
awslocal sqs create-queue --queue-name celery.fifo --attributes "FifoQueue=true"
awslocal sqs create-queue --queue-name celery
set +x
```

Appropriate queues are exist in localstack SQS:
```
awslocal sqs list-queues

{
    "QueueUrls": [
        "http://localhost:4566/000000000000/celery.fifo",
        "http://localhost:4566/000000000000/celery"
    ]
}
```

**Comment by thedrow** [comment]
The problem appears to be in localstack since [ApproximateReceiveCount](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) is a mandatory field.
