### ISSUE TITLE
Redis CROSSSLOT error for WATCH command

### ISSUE THREAD

**Issue by dcecile** [celery/kombu#1569]
I'm using the `global_keyprefix` with Kombu 5.2.4, but this setting isn't being respected for the Redis WATCH command.

Here is the Celery error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/usr/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/lib/python3.10/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/usr/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 430, in connect
    conn.transport.register_with_event_loop(conn.connection, self.hub)
  File "/usr/lib/python3.10/site-packages/kombu/transport/redis.py", line 1292, in register_with_event_loop
    cycle.on_poll_init(loop.poller)
  File "/usr/lib/python3.10/site-packages/kombu/transport/redis.py", line 539, in on_poll_init
    return channel.qos.restore_visible(
  File "/usr/lib/python3.10/site-packages/kombu/transport/redis.py", line 409, in restore_visible
    self.restore_by_tag(tag, client)
  File "/usr/lib/python3.10/site-packages/kombu/transport/redis.py", line 424, in restore_by_tag
    client.transaction(restore_transaction, self.unacked_key)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 804, in transaction
    func_value = func(pipe)
  File "/usr/lib/python3.10/site-packages/kombu/transport/redis.py", line 416, in restore_transaction
    p = pipe.hget(self.unacked_key, tag)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 3010, in hget
    return self.execute_command('HGET', name, key)
  File "/usr/lib/python3.10/site-packages/kombu/transport/redis.py", line 250, in execute_command
    return super().execute_command(*self._prefix_args(args), **kwargs)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 3822, in execute_command
    return self.immediate_execute_command(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 3841, in immediate_execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/lib/python3.10/site-packages/kombu/transport/redis.py", line 242, in parse_response
    ret = super().parse_response(connection, command_name, **options)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: CROSSSLOT Keys in request don't hash to the same slot (context='within WATCH', command='HGET', original-slot='8345', wrong-slot='3213', first-key='unacked', violating-key='{celery}:unacked')
```

Here are the Redis MONITOR logs:

```
1657225975.600194 [0 34.86.100.201:3245] "WATCH" "unacked"
1657225975.604194 [0 34.86.100.201:3245] "HGET" "{celery}:unacked" "b49ae49b-8b51-4d62-89c3-fd2b365cc115"
1657225975.604194 [0 34.86.100.201:3245] "UNWATCH"
```

I have `{celery}:` set as the prefix, to get all Celery keys onto the same Redis cluster slot. The prefix works for the HGET command but not the WATCH command.

It looks like the [`client.transaction()` call](https://github.com/celery/kombu/blob/v5.2.4/kombu/transport/redis.py#L424) causes the WATCH, and the key would have been prefixed if WATCH was on the [`PREFIXED_SIMPLE_COMMANDS` list](https://github.com/celery/kombu/blob/v5.2.4/kombu/transport/redis.py#L189).

**Comment by auvipy** [comment]
can you try to contribute a fix on master?

**Comment by dcecile** [comment]
@auvipy No problem, I've opened a PR: #1572
