### ISSUE TITLE
Currently using celery for my django  but get error kombu.exceptions.OperationalError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by codertjay** [celery/kombu#1582]
I am  currently using django, celery and redis    i am always getting this  error  
`kombu.exceptions.OperationalError: [Errno 111] Connection refused`    But if I run the code on windows it work perfectly where i have rabbitmql but  it doesn’t work in my linux (wsl) and my Ubuntu server . if i run the task in django shell it works  but it doesn't work if i call the task in a view function 
I have also checked my redis server and it’s currently responding I even restart  to verify 

and my celery.py in my django project is 
Please can someone help me to know what I am missing 

```
`import os

from celery import Celery
from django.conf import settings


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Gimsap.settings')

BROKER_URL = "redis://localhost:6379"

# used redis broker if it exists
app = Celery('Gimsap', namespace='CELERY')

app.config_from_object('django.conf:settings')

# Load task modules from all registered Django app configs.
app.autodiscover_tasks(settings.INSTALLED_APPS)

app.conf.broker_url = BROKER_URL
CELERY_BROKER_URL = BROKER_URL

app.conf.beat_schedule = {

    """'
    Test celery worker
    send_admin_message': {
        'task': 'home.tasks.test_task',
        'schedule': 3,
    },"""
}


@app.task(bind=True)
def debug_task(self):
    print(f'Request: {self.request!r}')
`
```
I have also tried using external redis server but it doesnt work well

this is also my setting.py  i know it might be  wrong posting this much  code but i have been on this for hours but still cant fixed it 

```
"""
Django settings for Gimsap project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import datetime
from pathlib import Path
import os
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')
if DEBUG == "True":
    DEBUG = True
else:
    DEBUG = False
if not DEBUG:
    pass
    # todo : uncomment after adding domain name
    # CSRF_COOKIE_SECURE = True
    # SESSION_COOKIE_SECURE = True
    # SECURE_SSL_REDIRECT = True
    # SECURE_HSTS_SECONDS = 31536000  # One year in seconds
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
    # SECURE_CONTENT_TYPE_NOSNIFF = True
    #  todo remove when doamin is added
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

if DEBUG:
    ALLOWED_HOSTS = ["*", ]
else:
    ALLOWED_HOSTS = ["*.domain.com"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',

    #  third party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'django_celery_beat',
    'post_office',

    # my apps
    'orders',
    '
]

MIDDLEWARE = [
    # Todo : for heroku will be removed later
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Gimsap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'items.context_processors.add_variable_to_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gimsap.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': config('POSTGRESDB_NAME', default=''),
            'USER': config('POSTGRESDB_USER', default=''),
            'PASSWORD': config('POSTGRESDB_PASSWORD', default=''),
            'HOST': config('POSTGRESDB_HOST', default=''),
            'PORT': '',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
#  Add configuration for static files storage using whitenoise
# Todo: note i installed  gunicorn dj-database-url whitenoise psycopg2 for heroku
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django allauth
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_QUERY_EMAIL = True

SIGNUP_REDIRECT_URL = LOGIN_REDIRECT_URL
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_SIGNUP_REDIRECT_URL = LOGIN_REDIRECT_URL
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300

AUTHENTICATION_BACKENDS = (
    # Needed to log in by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"
)

# EMAIL_BACKEND = "post_office.EmailBackend"
EMAIL_BACKEND = "post_office.EmailBackend"
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')

POST_OFFICE = {
    # 'DEFAULT_PRIORITY': 'now',
    'CELERY_ENABLED': True,
    'MESSAGE_ID_ENABLED': True,
    'MAX_RETRIES': 5,
    'RETRY_INTERVAL': datetime.timedelta(minutes=15),  # Schedule to be retried 15 minutes later
    'THREADS_PER_PROCESS': 10,
}

ADMINS = [('Afenikhena Favour', config('ADMIN_MAIL'),)]

SITE_ID = 1

CRISPY_TEMPLATE_PACK = 'bootstrap4'

DOMAIN_URL = config('DOMAIN_URL', default="https://domain.com")

# change the credentials if on debug
if DEBUG:
    PAYPAL_CLIENT_ID = config('DEBUG_PAYPAL_CLIENT_ID')
    PAYPAL_SECRET_KEY = config('DEBUG_PAYPAL_SECRET_KEY')
    PAYPAL_URL = config('DEBUG_PAYPAL_URL')
else:
    PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID')
    PAYPAL_SECRET_KEY = config('PAYPAL_SECRET_KEY')
    PAYPAL_URL = config('PAYPAL_URL')

GOOGLE_API_KEY = config('GOOGLE_API_KEY')

CELERY_ENABLED = True
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"
```

And the full error i have been having 

```
`Internal Server Error: /contact/
Traceback (most recent call last):
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/utils/functional.py", line 30, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
    yield
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 433, in _ensure_connection
    return retry_over_time(
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 877, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 812, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection
    conn.connect()
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/amqp/connection.py", line 323, in connect
    self.transport.connect()
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/amqp/transport.py", line 129, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/amqp/transport.py", line 184, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/c/Users/Codertjay/PycharmProjects/freelance/Gimsap-Ecommerce/home/views.py", line 95, in get
    test_task.delay()
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/messaging.py", line 177, in publish
    return _publish(
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 523, in _ensured
    return fun(*args, **kwargs)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/messaging.py", line 186, in _publish
    channel = self.channel
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/utils/functional.py", line 32, in __call__
    value = self.__value__ = self.__contract__()
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/messaging.py", line 225, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 895, in default_channel
    self._ensure_connection(**conn_opts)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 433, in _ensure_connection
    return retry_over_time(
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/codertjay/.virtualenvs/Gimsap-Ecommerce/lib/python3.9/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: [Errno 111] Connection refused
[13/Aug/2022 15:56:40] "GET /contact/ HTTP/1.1" 500 228751
`


```

This is my requirements.txt

```
`amqp==5.1.1
asgiref==3.5.2
async-timeout==4.0.2
billiard==3.6.4.0
bleach==5.0.1
celery==5.2.7
certifi==2022.6.15
cffi==1.15.0
charset-normalizer==2.1.0
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
colorama==0.4.5
cryptography==37.0.2
defusedxml==0.7.1
Deprecated==1.2.13
Django==4.0.7
django-allauth==0.51.0
django-celery-beat==2.3.0
django-crispy-forms==1.14.0
django-post-office==3.6.1
django-timezone-field==5.0
googlemaps==4.6.0
gunicorn==20.1.0
idna==3.3
joblib==1.1.0
jsonfield==3.1.0
kombu==5.2.4
nltk==3.7
numpy==1.23.1
oauthlib==3.2.0
order==1.3.5
packaging==21.3
Pillow==9.1.1
prompt-toolkit==3.0.30
psycopg2-binary==2.9.3
pycparser==2.21
PyJWT==2.4.0
pyparsing==3.0.9
python-crontab==2.6.0
python-dateutil==2.8.2
python-decouple==3.6
python3-openid==3.2.0
pytz==2022.1
redis==4.3.4
regex==2022.7.25
requests==2.28.1
requests-oauthlib==1.3.1
scinum==1.4.1
six==1.16.0
sqlparse==0.4.2
textblob==0.17.1
tinycss2==1.1.1
tqdm==4.64.0
tzdata==2022.1
urllib3==1.26.11
vine==5.0.0
wcwidth==0.2.5
webencodings==0.5.1
whitenoise==6.2.0
wrapt==1.14.1
`
```

**Comment by codertjay** [comment]
My current celery version is celery==5.2.7

**Comment by codertjay** [comment]
I fixed the error by adding broker and broker url to the Celery.py and I made sure my redis-server was running 

my new settings is 

`import os

from celery import Celery
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Gimsap.settings')

# used redis broker if it exists
app = Celery('Gimsap', broker="redis://localhost:6379", backend="redis://localhost:6379")

app.config_from_object('django.conf:settings')

# Load task modules from all registered Django app configs.
app.autodiscover_tasks(settings.INSTALLED_APPS)
BROKER_URL = "redis://localhost:6379"
broker_url = "redis://localhost:6379"
app.conf.broker_url = BROKER_URL
CELERY_BROKER_URL = BROKER_URL

app.conf.beat_schedule = {

    """'
    Test celery worker
    send_admin_message': {
        'task': 'home.tasks.test_task',
        'schedule': 3,
    },"""
}


@app.task
def debug_task():
    print(f'Request: ') `

**Comment by elfarsaouiomar** [comment]
if some still facing this issue. here how i solve it

in the __init__.py add the following code. 

```python
from .celery import app as CRM_CELERY_APP

__all__ = ["CRM_CELERY_APP"]
```

**Comment by nathanieldavidson916** [comment]
> ```python
> from .celery import app as CRM_CELERY_APP
> 
> __all__ = ["CRM_CELERY_APP"]
> ```

For anyone curious as to why this is required like myself there's an explanation for it on celery's ["First steps with Django" guide](https://docs.celeryq.dev/en/latest/django/first-steps-with-django.html)

> Then you need to import this app in your proj/proj/__init__.py module. This ensures that the app is loaded when Django starts so that the @shared_task decorator (mentioned later) will use it:

> proj/proj/__init__.py:
```python
# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app

__all__ = ('celery_app',)
```

**Comment by Chephos** [comment]
I'm having the same issue but with fastapi
