### ISSUE TITLE
SQLAlchemy 2.0.0 breaking API changes

### ISSUE THREAD

**Issue by woutdenolf** [celery/kombu#1609]
https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-2.0.0b1
```
Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.0b1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
```

```python
Traceback (most recent call last):
  File "examples/example_with_events.py", line 119, in <module>
    future = submit(args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.8/site-packages/ewoksjob/client/celery/tasks.py", line 17, in trigger_workflow
    return send_task("ewoksjob.apps.ewoks.execute_workflow", **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 784, in send_task
    with self.producer_or_acquire(producer) as P:
  File "/usr/local/lib/python3.8/site-packages/celery/utils/objects.py", line 84, in __enter__
    context = self._context = self.fallback(
  File "/usr/local/lib/python3.8/site-packages/kombu/resource.py", line 88, in acquire
    R = self.prepare(R)
  File "/usr/local/lib/python3.8/site-packages/kombu/pools.py", line 61, in prepare
    p = p()
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 187, in __call__
    return self.evaluate()
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 190, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/pools.py", line 41, in create_producer
    conn = self._acquire_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/usr/local/lib/python3.8/site-packages/kombu/resource.py", line 88, in acquire
    R = self.prepare(R)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 1035, in prepare
    resource = resource()
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 187, in __call__
    return self.evaluate()
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 190, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 1007, in new
    return self.connection.clone()
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 631, in clone
    return self.__class__(**dict(self._info(resolve=False), **kwargs))
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 641, in _info
    D = self.transport.default_connection_params
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 929, in transport
    self._transport = self.create_transport()
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 620, in create_transport
    return self.get_transport_cls()(client=self)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 626, in get_transport_cls
    transport_cls = get_transport_cls(transport_cls)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/__init__.py", line 89, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/__init__.py", line 74, in resolve_transport
    return symbol_by_name(transport)
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 58, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 67, in <module>
    from .models import Message as MessageBase
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/sqlalchemy/models.py", line 9, in <module>
    from sqlalchemy.orm import relation
ImportError: cannot import name 'relation' from 'sqlalchemy.orm' (/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/__init__.py)
```

**Comment by auvipy** [comment]
thanks for the early report. we generally don't add support of beta versions. but will test and try to add support of new API's soon

**Comment by craigmulligan** [comment]
Hey @auvipy, 

Sqlalchemy v2 is now out. I was trying to integrate it into one of my projects and bumped into this. Here are the [changes](https://github.com/craigmulligan/kombu/commit/70a50082d524341d7bef561996ff7cc8a4bc2405) I needed to get things running. Would you like me to open a PR?

**Comment by auvipy** [comment]
yes please
