### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetQueueAttributes operation: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by adi5551** [celery/kombu#1615]
When I try to connect to SQS using Celery, I'm not able to. The worker crashes with the following message:
```
[2022-10-28 14:05:39,237: CRITICAL/MainProcess] Unrecoverable error: ClientError('An error occurred (InvalidClientTokenId) when calling the GetQueueAttributes operation: The security token included in the request is invalid.')
Traceback (most recent call last):
  File "/home/aditya/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/aditya/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/aditya/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/aditya/.local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/home/aditya/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/aditya/.local/lib/python3.10/site-packages/celery/worker/consumer/tasks.py", line 38, in start
    c.task_consumer = c.app.amqp.TaskConsumer(
  File "/home/aditya/.local/lib/python3.10/site-packages/celery/app/amqp.py", line 274, in TaskConsumer
    return self.Consumer(
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/messaging.py", line 387, in __init__
    self.revive(self.channel)
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/messaging.py", line 409, in revive
    self.declare()
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/messaging.py", line 422, in declare
    queue.declare()
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/entity.py", line 606, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/entity.py", line 615, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/entity.py", line 643, in queue_declare
    ret = channel.queue_declare(
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 523, in queue_declare
    return queue_declare_ok_t(queue, self._size(queue), 0)
  File "/home/aditya/.local/lib/python3.10/site-packages/kombu/transport/SQS.py", line 633, in _size
    resp = c.get_queue_attributes(
  File "/home/aditya/.local/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/aditya/.local/lib/python3.10/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetQueueAttributes operation: The security token included in the request is invalid.
```
The credentials are correct, and my Cloud Admin insists that my credentials have these permissions.
If it helps, these are in my `settings.py` :
```
from urllib.parse import quote

CELERY_BROKER_URL = 'sqs://{access_key}:{secret_key}@'.format(
    access_key=quote(env.str("AWS_ACCESS_KEY_ID"), safe=''),
    secret_key=quote(env.str("AWS_SECRET_ACCESS_KEY"), safe=''),
)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "region": "us-east-2", 
    "polling_interval": 60,
    'sdb_persistence': False,
    "predefined_queues":{
        'myq': {
            'url': 'https://sqs.us-east-2.amazonaws.com/164782647287/myq',
            'access_key_id': env.str("AWS_ACCESS_KEY_ID"),
            'secret_access_key': env.str("AWS_SECRET_ACCESS_KEY"),
        },
    }
}
CELERY_TASK_DEFAULT_QUEUE = 'myq'
```
I'm using the latest version of Celery and associated dependencies:
`celery[sqs]==5.2.7`

**Comment by adi5551** [comment]
Apologies, my Cloud Admin did not give me the required permissions, and that was causing this issue. Hence closing this.
