### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by arashm404** [celery/kombu#1649]
Hi
i have problem with kombu + celery
my broker is rabbitmq 3.11.7
im using this command to run my workers
celery -A proj worker -Q queue1 -c 150
celery -A proj worker -Q queue2 -c 150
celery 5.2.7 (dawn-chorus)
kombu==5.3.0b2
amqp==5.1.1
python3.10.6
i dont know it can be releated but my server file limit and proc limit is 256000
this is traceback
[2023-01-30 19:40:55,098: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'fileno'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/loops.py", line 62, in asynloop
    obj.controller.register_with_event_loop(hub)
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/worker.py", line 215, in register_with_event_loop
    self.blueprint.send_all(
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 148, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/components.py", line 175, in register_with_event_loop
    w.pool.register_with_event_loop(hub)
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/prefork.py", line 137, in register_with_event_loop
    return reg(loop)
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 517, in register_with_event_loop
    [self._track_child_process(w, hub) for w in self._pool]
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 517, in <listcomp>
    [self._track_child_process(w, hub) for w in self._pool]
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 498, in _track_child_process
    iterate_file_descriptors_safely(
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 214, in iterate_file_descriptors_safely
    hub_method(fd, *hub_args, **hub_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/kombu/asynchronous/hub.py", line 219, in add_reader
    return self.add(fds, callback, READ | ERR, args)
  File "/usr/local/lib/python3.10/dist-packages/kombu/asynchronous/hub.py", line 167, in add
    fd = fileno(fd)
  File "/usr/local/lib/python3.10/dist-packages/kombu/utils/compat.py", line 101, in fileno
    return f.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'
and also my celeryconfig file contains:
task_ignore_result = True
broker_url = "amqp://..."
result_expires = 10800
broker_pool_limit = 256
task_acks_late = True
broker_connection_retry_on_startup = True
worker_max_memory_per_child = 16000

**Comment by spiderpanel** [comment]
i have also this bug

**Comment by auvipy** [comment]
please follow a proper issue template.

**Comment by arashm404** [comment]
> please follow a proper issue template.

sorry what?

**Comment by spiderpanel** [comment]
i didnot understand too

**Comment by thedrow** [comment]
@auvipy Kombu does not have an issue template yet.
In any case, this is a Celery issue that we can't properly reproduce using the information provided for us.

**Comment by auvipy** [comment]
> @auvipy Kombu does not have an issue template yet. In any case, this is a Celery issue that we can't properly reproduce using the information provided for us.

thanks! I didn't notice that when commented!

**Comment by mstdokumaci** [comment]
how is this not a bug?

**Comment by auvipy** [comment]
can you reproduce it?

**Comment by mstdokumaci** [comment]
@auvipy yes happens often:

```
2026-07-02 15:24:12.231 unk AttributeError: 'NoneType' object has no attribute 'fileno' 
2026-07-02 15:24:12.231 unk            ^^^^^^^^ 
2026-07-02 15:24:12.231 unk     return f.fileno() 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/kombu/utils/compat.py", line 95, in fileno 
2026-07-02 15:24:12.231 unk     fd = fileno(fd) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/kombu/asynchronous/hub.py", line 169, in add 
2026-07-02 15:24:12.231 unk            ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk     return self.add(fds, callback, READ | ERR, args) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/kombu/asynchronous/hub.py", line 221, in add_reader 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk     hub_method(fd, *hub_args, **hub_kwargs) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/concurrency/asynpool.py", line 224, in iterate_file_descriptors_safely 
2026-07-02 15:24:12.231 unk         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk         self._event_process_exit, hub, proc) 
2026-07-02 15:24:12.231 unk         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk         [fd], None, hub.add_reader, 
2026-07-02 15:24:12.231 unk         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk         [fd], None, hub.add_reader, 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ 
2026-07-02 15:24:12.231 unk     iterate_file_descriptors_safely( 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/concurrency/asynpool.py", line 511, in _track_child_process 
2026-07-02 15:24:12.231 unk      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^ 
2026-07-02 15:24:12.231 unk     [self._track_child_process(w, hub) for w in self._pool] 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/concurrency/asynpool.py", line 530, in register_with_event_loop 
2026-07-02 15:24:12.231 unk     return reg(loop) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/concurrency/prefork.py", line 137, in register_with_event_loop 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^ 
2026-07-02 15:24:12.231 unk     w.pool.register_with_event_loop(hub) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/worker/components.py", line 175, in register_with_event_loop 
2026-07-02 15:24:12.231 unk     ~~~^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk     fun(parent, *args) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/bootsteps.py", line 148, in send_all 
2026-07-02 15:24:12.231 unk     ^ 
2026-07-02 15:24:12.231 unk     ) 
2026-07-02 15:24:12.231 unk         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk         description='hub.register', 
2026-07-02 15:24:12.231 unk         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk         self, 'register_with_event_loop', args=(hub,), 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~~~~~~~~~~~~~~^ 
2026-07-02 15:24:12.231 unk     self.blueprint.send_all( 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/worker/worker.py", line 215, in register_with_event_loop 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^ 
2026-07-02 15:24:12.231 unk     obj.controller.register_with_event_loop(hub) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/worker/loops.py", line 62, in asynloop 
2026-07-02 15:24:12.231 unk     ~~~~~~^^^^^^^^^^^^^^^^ 
2026-07-02 15:24:12.231 unk     c.loop(*c.loop_args()) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/worker/consumer/consumer.py", line 790, in start 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~^^^^^^^^ 
2026-07-02 15:24:12.231 unk     step.start(parent) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/bootsteps.py", line 116, in start 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~~~~~~^^^^^^ 
2026-07-02 15:24:12.231 unk     blueprint.start(self) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/worker/consumer/consumer.py", line 346, in start 
2026-07-02 15:24:12.231 unk            ~~~~~~~~~~~~~~^^ 
2026-07-02 15:24:12.231 unk     return self.obj.start() 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/bootsteps.py", line 365, in start 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~^^^^^^^^ 
2026-07-02 15:24:12.231 unk     step.start(parent) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/bootsteps.py", line 116, in start 
2026-07-02 15:24:12.231 unk     ~~~~~~~~~~~~~~~~~~~~^^^^^^ 
2026-07-02 15:24:12.231 unk     self.blueprint.start(self) 
2026-07-02 15:24:12.231 unk   File "/usr/local/lib/python3.13/site-packages/celery/worker/worker.py", line 203, in start 
2026-07-02 15:24:12.231 unk Traceback (most recent call last): 
2026-07-02 15:24:12.231 crit [2026-07-02 13:24:12,227: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'fileno'") 
```

**Comment by auvipy** [comment]
celery version?

**Comment by mstdokumaci** [comment]
@auvipy 5.6.0
