### ISSUE TITLE
KeyError when acknowledging message in azureservicebus

### ISSUE THREAD

**Issue by IsmaelJS** [celery/kombu#1661]
**Used libraries**
celery==5.1.2
kombu==5.1.0
azure-servicebus==7.8.1

**Detected issue**
There are errors as following when celery tries to acknowledge some messages. The traceback is similar to describe in these issues with SQS: https://github.com/celery/kombu/issues/73 and  https://github.com/celery/kombu/issues/137 

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 240, in perform_pending_operations
    self._pending_operations.pop()()
  File "/root/.local/lib/python3.8/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
  File "/root/.local/lib/python3.8/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/root/.local/lib/python3.8/site-packages/kombu/message.py", line 128, in ack_log_error
    self.ack(multiple=multiple)
  File "/root/.local/lib/python3.8/site-packages/kombu/message.py", line 123, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/root/.local/lib/python3.8/site-packages/kombu/transport/azureservicebus.py", line 278, in basic_ack
    delivery_info = self.qos.get(delivery_tag).delivery_info
  File "/root/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 221, in get
    return self._delivered[delivery_tag]
KeyError: '6818a766-3925-4c17-ba35-8cf889bf5ebe'

Why is this error ocurring?

**Comment by IsmaelJS** [comment]
@terrycain as author of the support the asb sdk 7.0 from celery 5.1, have you ever seen this error? do you know how to solve it?

Thank you.

**Comment by terrycain** [comment]
I've not seen that before, though ive not used celery and asb for over a year now (changed job)
