### ISSUE TITLE
Coroutine can't seem to be called directly by Celery

### ISSUE THREAD

**Issue by EITSxiaozhai** [celery/kombu#1679]
**async function**
```
@celery_app.task()
@PowerApp.get('/')
async def LetView():
    async with db_session() as session:
        try:
           print(e)
        except Exception as e:
            print(e)
```

**Asynchronous function calls, use **_LetView.delay()_****
```
@app.get("/test")
@celery_app.task(acks_late=True)
def add_to_db_task():
    LetView.delay()
    return {"status": True}
```

**When starting Celery, the corresponding task can be identified**
```
[tasks]
  . main.add_to_db_task
```

**When I call the above function in the below function, the following error occurs**

```
_error message_
[During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python3\lib\site-packages\celery\app\trace.py", line 518, in trace_task
    task.backend.mark_as_done(
  File "d:\python3\lib\site-packages\celery\backends\base.py", line 162, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "d:\python3\lib\site-packages\celery\backends\base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "d:\python3\lib\site-packages\celery\backends\base.py", line 962, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
  File "d:\python3\lib\site-packages\celery\backends\base.py", line 418, in encode
    _, _, payload = self._encode(data)
  File "d:\python3\lib\site-packages\celery\backends\base.py", line 422, in _encode
    return dumps(data, serializer=self.serializer)
  File "d:\python3\lib\site-packages\kombu\serialization.py", line 210, in dumps
    payload = encoder(data)
  File "d:\python3\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\python3\lib\site-packages\kombu\serialization.py", line 43, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "d:\python3\lib\site-packages\kombu\exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "d:\python3\lib\site-packages\kombu\serialization.py", line 39, in _reraise_errors
    yield
  File "d:\python3\lib\site-packages\kombu\serialization.py", line 210, in dumps
    payload = encoder(data)
  File "d:\python3\lib\site-packages\dill\_dill.py", line 263, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "d:\python3\lib\site-packages\dill\_dill.py", line 235, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "d:\python3\lib\site-packages\dill\_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "d:\python3\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "d:\python3\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "d:\python3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "d:\python3\lib\site-packages\dill\_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "d:\python3\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "d:\python3\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "d:\python3\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "d:\python3\lib\pickle.py", line 578, in save
    rv = reduce(self.proto)
kombu.exceptions.EncodeError: cannot pickle 'coroutine' object]
```

**requirements**

```
mysqlclient~=2.0.2
DateTime~=5.0
uvicorn~=0.18.3
fastapi~=0.89.1
SQLAlchemy~=2.0.5.post1
pydantic~=1.10.4
sqlalchemy_utils~=0.40.0
asyncmy ~= 0.2.7
alembic ~= 1.10.0
beautifulsoup4~=4.11.2
requests~=2.22.0
celery~=5.2.7
eventlet ~= 0.33.1
```

**I can't identify if this is a BUG or there is another way to call the task.If anyone could help me out with this it would be greatly appreciated**

**Comment by auvipy** [comment]
I think it is happening as expected.

**Comment by EITSxiaozhai** [comment]
I'm using a translation software to translate the dialogue. There may be mistakes, please forgive me
**I'm trying to use the dill module to convert a coroutine object into something Celery can use.**  


_Celery configuration file_
```
from celery import Celery
from celery.schedules import crontab
from kombu import serialization
from kombu.serialization import register
import dill


register('dill', dill.dumps, dill.loads, content_type='application/x-python-serialize')
celery_app = Celery('tasks', broker='****', backend='***',task_serializer='dill', result_serializer='dill',
    accept_content=['json', 'dill'])
```

I used Celery's official way to call a task,But it still prompts an error, so I modified it,So Celery's error message contains the name of the package.
Even if I changed to other serialization module,But he still can't use.

**Comment by EITSxiaozhai** [comment]
[Example for running celery task which includes db transcation in async fastapi app](https://github.com/tiangolo/fastapi/issues/1366)

```
async def some_task(param1: str, param2: str, current_task_ref):
    await db.connect()

    # interact with db
    tot = 1e4
    for i in range(tot):
        current_task_ref.update_state(state='PROGRESSING', meta={'current': i + 1, 'total': tot})

    await db.close()
    return {'current': tot, 'total': tot}
    
@app.task(bind=True, acks_late=True)
def some_task_t(self, *args, **kwargs):
    return asyncio.run(some_task(*args, **kwargs, current_task_ref=self))

```

I refer to this link, hoping to help others, although this method is not perfect.Because he doesn't seem to be converted to a message queue object.

**Comment by auvipy** [comment]
for some idea https://github.com/the-wondersmith/celery-aio-pool#using-upcoming-out-of-tree-worker-pool-preferred

**Comment by jefer94** [comment]
I made a decorator called Supervisor, and it has support to sync and async callable, you should use  `asyncio.iscoroutinefunction(fn)` and `inspect.isasyncgenfunction(fn)` and then, user `asyncio.run(fn)`, I didn't test for the async part, but it must work.

Original: https://github.com/breatheco-de/apiv2/blob/development/breathecode/utils/decorators/supervisor.py

```py
import asyncio
import functools
import inspect
from datetime import timedelta
from typing import Optional

from asgiref.sync import sync_to_async
from django.utils import timezone

from breathecode.monitoring.models import Supervisor, SupervisorIssue

__all__ = ['supervisor', 'paths']

paths = set()


def supervisor(fn: Optional[callable] = None,
               delta: Optional[timedelta] = None,
               auto: bool = True,
               raises: bool = False):
    """Create a supervisor (automated quality assurance)."""

    def create_supervisor(fn: callable, delta: Optional[timedelta] = None, auto: bool = True, raises: bool = False):

        @functools.wraps(fn)
        def wrapper(*args, **kwargs):
            ...

        @functools.wraps(fn)
        async def async_wrapper(*args, **kwargs):
            ...

        if delta is None:
            delta = timedelta(hours=1)

        paths.add((fn.__module__, fn.__name__, delta))

        if asyncio.iscoroutinefunction(fn) and inspect.isasyncgenfunction(fn):
            return async_wrapper

        return wrapper

    if fn:
        return create_supervisor(fn, delta, auto, raises)

    return create_supervisor
```

**Comment by ygbingo** [comment]
I used this command resolved problem ```celery -A src.celery_wrapper worker -l info -P threads --concurrency=4```. I change -P from eventlet to threads.
