### ISSUE TITLE
No module named 'tzdata'

### ISSUE THREAD

**Issue by renato-farias** [celery/kombu#1748]
Fail to start Celery beat and worker

Release 5.3.0
Python 3.10

Workaround -> `kombu = ">=5.2.3,<5.3.0"`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
    return importlib.resources.open_binary(package_name, resource_name)
  File "/usr/local/lib/python3.10/importlib/resources.py", line 43, in open_binary
    package = _common.get_package(package)
  File "/usr/local/lib/python3.10/importlib/_common.py", line 66, in get_package
    resolved = resolve(package)
  File "/usr/local/lib/python3.10/importlib/_common.py", line 57, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/golog/app/celery_beat.py", line 7, in <module>
    app.start(argv)
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 363, in start
    from celery.bin.celery import celery
  File "/usr/local/lib/python3.10/site-packages/celery/bin/celery.py", line 34, in <module>
    from celery.bin.worker import worker
  File "/usr/local/lib/python3.10/site-packages/celery/bin/worker.py", line 14, in <module>
    from celery.concurrency.base import BasePool
  File "/usr/local/lib/python3.10/site-packages/celery/concurrency/base.py", line 12, in <module>
    from celery.utils import timer2
  File "/usr/local/lib/python3.10/site-packages/celery/utils/timer2.py", line 14, in <module>
    from kombu.asynchronous.timer import Entry
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/__init__.py", line 7, in <module>
    from .hub import Hub, get_event_loop, set_event_loop
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 19, in <module>
    from .timer import Timer
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/timer.py", line 32, in <module>
    EPOCH = datetime.utcfromtimestamp(0).replace(tzinfo=ZoneInfo("UTC"))
  File "/usr/local/lib/python3.10/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'
```

**Comment by auvipy** [comment]
can you please share more? isn't the tzdata being installed with celery 5.3.0 release?

**Comment by auvipy** [comment]
can you try https://github.com/celery/kombu/releases/tag/v5.3.1? it should contain the fix

**Comment by auvipy** [comment]
your installation is missing https://pypi.org/project/tzdata/
