### ISSUE TITLE
Installation failed on pycurl for MAC M1 chipset

### ISSUE THREAD

**Issue by Asafb26** [celery/kombu#1752]
**gettings this since latest bump, apparently pycurl version 7.43.0.5 is not supported on mac, for version >= 7.44.1 everything works as expected, but now 7.43.0.5 is being locked on sqs extras req:**
```
poetry add "celery[sqs]@5.3.0"

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing pycurl (7.43.0.5): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  <string>:906: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  <string>:908: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  Using curl-config (libcurl 7.84.0)
  Using SSL library: OpenSSL/LibreSSL/BoringSSL
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-13.0-arm64-cpython-311
  creating build/lib.macosx-13.0-arm64-cpython-311/curl
  copying python/curl/__init__.py -> build/lib.macosx-13.0-arm64-cpython-311/curl
  running build_ext
  building 'pycurl' extension
  creating build/temp.macosx-13.0-arm64-cpython-311
  creating build/temp.macosx-13.0-arm64-cpython-311/src
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -DPYCURL_VERSION=\"7.43.0.5\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmp7foscu4t/.venv/include -I/Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11 -c src/docstrings.c -o build/temp.macosx-13.0-arm64-cpython-311/src/docstrings.o
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -DPYCURL_VERSION=\"7.43.0.5\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmp7foscu4t/.venv/include -I/Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11 -c src/easy.c -o build/temp.macosx-13.0-arm64-cpython-311/src/easy.o
  src/easy.c:283:5: warning: 'UsingDeprecatedTrashcanMacro' is deprecated [-Wdeprecated-declarations]
      Py_TRASHCAN_SAFE_BEGIN(self);
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/cpython/object.h:507:9: note: expanded from macro 'Py_TRASHCAN_SAFE_BEGIN'
          UsingDeprecatedTrashcanMacro cond=1; \
          ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/cpython/object.h:504:1: note: 'UsingDeprecatedTrashcanMacro' has been explicitly marked deprecated here
  Py_DEPRECATED(3.11) typedef int UsingDeprecatedTrashcanMacro;
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  1 warning generated.
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -DPYCURL_VERSION=\"7.43.0.5\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmp7foscu4t/.venv/include -I/Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11 -c src/easycb.c -o build/temp.macosx-13.0-arm64-cpython-311/src/easycb.o
  src/easycb.c:45:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:187:22: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      python_address = PyEval_CallObject(curl_sockaddr_type, arglist);
                       ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:198:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(self->opensocket_cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:260:15: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      ret_obj = PyEval_CallObject(self->sockopt_cb, arglist);
                ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:312:15: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      ret_obj = PyEval_CallObject(self->closesocket_cb, arglist);
                ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:413:15: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      ret_obj = PyEval_CallObject(self->ssh_key_cb, arglist);
                ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:491:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:557:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(self->r_cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:665:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(self->pro_cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:718:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(self->xferinfo_cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:778:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(self->debug_cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  src/easycb.c:819:14: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      result = PyEval_CallObject(self->ioctl_cb, arglist);
               ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  12 warnings generated.
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -DPYCURL_VERSION=\"7.43.0.5\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmp7foscu4t/.venv/include -I/Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11 -c src/easyinfo.c -o build/temp.macosx-13.0-arm64-cpython-311/src/easyinfo.o
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -DPYCURL_VERSION=\"7.43.0.5\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmp7foscu4t/.venv/include -I/Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11 -c src/easyopt.c -o build/temp.macosx-13.0-arm64-cpython-311/src/easyopt.o
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -DPYCURL_VERSION=\"7.43.0.5\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmp7foscu4t/.venv/include -I/Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11 -c src/easyperform.c -o build/temp.macosx-13.0-arm64-cpython-311/src/easyperform.o
  src/easyperform.c:31:10: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
      io = PyEval_CallObject(bytesio, NULL);
           ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:34:5: note: expanded from macro 'PyEval_CallObject'
      PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:27:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  1 warning generated.
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -DPYCURL_VERSION=\"7.43.0.5\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmp7foscu4t/.venv/include -I/Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11 -c src/module.c -o build/temp.macosx-13.0-arm64-cpython-311/src/module.o
  src/module.c:375:25: error: expression is not assignable
      Py_TYPE(&Curl_Type) = &PyType_Type;
      ~~~~~~~~~~~~~~~~~~~ ^
  src/module.c:376:30: error: expression is not assignable
      Py_TYPE(&CurlMulti_Type) = &PyType_Type;
      ~~~~~~~~~~~~~~~~~~~~~~~~ ^
  src/module.c:377:30: error: expression is not assignable
      Py_TYPE(&CurlShare_Type) = &PyType_Type;
      ~~~~~~~~~~~~~~~~~~~~~~~~ ^
  src/module.c:1416:5: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
      PyEval_InitThreads();
      ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/ceval.h:132:1: note: 'PyEval_InitThreads' has been explicitly marked deprecated here
  Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
  ^
  /Users/asafbenaharon/.pyenv/versions/3.11.3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  1 warning and 3 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1


  at ~/.pyenv/versions/3.11.3/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pycurl (7.43.0.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pycurl (==7.43.0.5)"'.
```

**Comment by auvipy** [comment]
the pin is relaxed in main branch. a new point release should fix this

**Comment by Asafb26** [comment]
Thanks, any ETA for that?
tried to point on latest commit with poetry, got error:
```
Package operations: 0 installs, 41 updates, 0 removals

  • Updating kombu (5.3.0b3 -> 5.3.0 6df5ce8): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "/Users/asafbenaharon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/asafbenaharon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/asafbenaharon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmpxuicio7k/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmpxuicio7k/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmpxuicio7k/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/gf/db0l08px22n6kr34qxq5mc700000gn/T/tmpxuicio7k/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 27, in <module>
  FileNotFoundError: [Errno 2] No such file or directory: '/Users/asafbenaharon/workspace/tres/platform/microservices/transaction-builder/.venv/src/kombu/__init__.py'
```
