### ISSUE TITLE
No module named 'azureservicebus'

### ISSUE THREAD

**Issue by m-araujo-voltalia** [celery/kombu#1762]
Hi, i'm trying to connect to Azure Service Bus as broker and result. But i receive this error:

```
[2023-06-28 11:54:02,970: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'azureservicebus'")
Traceback (most recent call last):
  File "c:\projects\base_api\env\lib\site-packages\celery\app\base.py", line 1250, in backend
    return self._local.backend
  File "c:\projects\base_api\env\lib\site-packages\eventlet\corolocal.py", line 45, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: 'local' object has no attribute 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\projects\base_api\env\lib\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "c:\projects\base_api\env\lib\site-packages\celery\bootsteps.py", line 112, in start
    self.on_start()
  File "c:\projects\base_api\env\lib\site-packages\celery\apps\worker.py", line 136, in on_start
    self.emit_banner()
  File "c:\projects\base_api\env\lib\site-packages\celery\apps\worker.py", line 170, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "c:\projects\base_api\env\lib\site-packages\celery\apps\worker.py", line 232, in startup_info
    results=self.app.backend.as_uri(),
  File "c:\projects\base_api\env\lib\site-packages\celery\app\base.py", line 1252, in backend
    self._local.backend = new_backend = self._get_backend()
  File "c:\projects\base_api\env\lib\site-packages\celery\app\base.py", line 955, in _get_backend
    backend, url = backends.by_url(
  File "c:\projects\base_api\env\lib\site-packages\celery\app\backends.py", line 69, in by_url
    return by_name(backend, loader), url
  File "c:\projects\base_api\env\lib\site-packages\celery\app\backends.py", line 49, in by_name
    cls = symbol_by_name(backend, aliases)
  File "c:\projects\base_api\env\lib\site-packages\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\m.araujo\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azureservicebus'
```

When i try to connect with "azure-servicebus" it returns: `KeyError: 'No such transport: azure-servicebus.  Did you mean azureservicebus?'`

**Comment by auvipy** [comment]
azureservicebus should be used not azure-servicebus
