### ISSUE TITLE
Can't connect to Kafka but got class NoBrokersAvailable exception:

### ISSUE THREAD

**Issue by csun-cpointe** [celery/kombu#1778]
I can't connect to Kafka using kombu but I was able to connect to kafka server using kafka-python and java.

Here is my code:
```
from __future__ import annotations

import datetime

from kombu import Connection

with Connection('confluentkafka://localhost:9092') as conn:
    simple_queue = conn.SimpleQueue('simple_queue')
    message = f'helloworld, sent at {datetime.datetime.today()}'
    simple_queue.put(message)
    print(f'Sent: {message}')
    simple_queue.close()
```
And the exception I've got

```
/Users/usera/bah/evaluation/py4J/src/main/java/python/venv/bin/python /Users/usera/bah/evaluation/py4J/src/main/java/python/kombu_producer.py 
Traceback (most recent call last):
  File "/Users/usera/bah/evaluation/py4J/src/main/java/python/kombu_producer.py", line 8, in <module>
    with Connection('confluentkafka://localhost:9092') as conn:
  File "/Users/usera/bah/evaluation/py4J/src/main/java/python/venv/lib/python3.9/site-packages/kombu/connection.py", line 201, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/Users/usera/bah/evaluation/py4J/src/main/java/python/venv/lib/python3.9/site-packages/kombu/transport/__init__.py", line 90, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/Users/usera/bah/evaluation/py4J/src/main/java/python/venv/lib/python3.9/site-packages/kombu/transport/__init__.py", line 75, in resolve_transport
    return symbol_by_name(transport)
  File "/Users/usera/bah/evaluation/py4J/src/main/java/python/venv/lib/python3.9/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/Users/usera/.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/usera/bah/evaluation/py4J/src/main/java/python/venv/lib/python3.9/site-packages/kombu/transport/confluentkafka.py", line 89, in <module>
    class NoBrokersAvailable(confluent_kafka.KafkaException):
AttributeError: 'NoneType' object has no attribute 'KafkaException'
```
Looking into the `test_kafka.py` file, I should be able to connect to kafka using 
```
def get_connection(hostname, port):
    return kombu.Connection(
        f'confluentkafka://{hostname}:{port}',
    )
```
Is it something I missed in configuration? Any suggestion appreciated. Thanks!!

**Comment by csun-cpointe** [comment]
https://stackoverflow.com/questions/76963371/connect-to-kafka-using-kombu-got-class-nobrokersavailableconfluent-kafka-kafkae
