### ISSUE TITLE
UnicodeDecodeError in Python 3

### ISSUE THREAD

**Issue by mpyatishev** [celery/kombu#191]
Python 3.2
Kombu 2.5.4

When I execute example code from documentation (http://kombu.readthedocs.org/en/latest/userguide/examples.html#task-queue-example) an exception is thrown:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/kombu/messaging.py", line 532, in _receive_callback
    message = m2p(message)
  File "/usr/local/lib/python3.2/dist-packages/kombu/transport/pyamqp.py", line 57, in message_to_python
    return self.Message(self, raw_message)
  File "/usr/local/lib/python3.2/dist-packages/kombu/transport/pyamqp.py", line 39, in __init__
    **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/kombu/transport/base.py", line 68, in **init**
    body = decompress(body, self.headers['compression'])
  File "/usr/local/lib/python3.2/dist-packages/kombu/compression.py", line 70, in decompress
    return bytes_to_str(get_decoder(content_type)(body))
  File "/usr/local/lib/python3.2/dist-packages/kombu/utils/encoding.py", line 36, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/kombu/utils/**init**.py", line 345, in nested
    yield vars
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 214, in Consumer
    yield conn, channel, c
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 181, in consume
    connection.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python3.2/dist-packages/kombu/connection.py", line 276, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/kombu/transport/pyamqp.py", line 89, in drain_events
    return connection.drain_events(**kwargs)
  File "/usr/local/lib/python3.2/dist-packages/amqp/connection.py", line 294, in drain_events
    return amqp_method(channel, args, content)
  File "/usr/local/lib/python3.2/dist-packages/amqp/channel.py", line 1884, in _basic_deliver
    fun(msg)
  File "/usr/local/lib/python3.2/dist-packages/kombu/messaging.py", line 537, in _receive_callback
    self.on_decode_error(message, exc)
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 151, in on_decode_error
    message.ack()
  File "/usr/local/lib/python3.2/dist-packages/amqp/serialization.py", line 375, in __getattr__
    raise AttributeError(name)
AttributeError: ack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker.py", line 37, in <module>
    Worker(conn).run()
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 165, in run
    for _ in self.consume(limit=None):
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 191, in consume
    elapsed = 0
  File "/usr/lib/python3.2/contextlib.py", line 66, in **exit**
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 214, in Consumer
    yield conn, channel, c
  File "/usr/lib/python3.2/contextlib.py", line 66, in **exit**
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.2/dist-packages/kombu/utils/**init**.py", line 360, in nested
    raise exc[0](exc[1]).with_traceback(exc[2])
  File "/usr/local/lib/python3.2/dist-packages/kombu/utils/**init**.py", line 345, in nested
    yield vars
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 214, in Consumer
    yield conn, channel, c
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 181, in consume
    connection.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python3.2/dist-packages/kombu/connection.py", line 276, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/kombu/transport/pyamqp.py", line 89, in drain_events
    return connection.drain_events(**kwargs)
  File "/usr/local/lib/python3.2/dist-packages/amqp/connection.py", line 294, in drain_events
    return amqp_method(channel, args, content)
  File "/usr/local/lib/python3.2/dist-packages/amqp/channel.py", line 1884, in _basic_deliver
    fun(msg)
  File "/usr/local/lib/python3.2/dist-packages/kombu/messaging.py", line 537, in _receive_callback
    self.on_decode_error(message, exc)
  File "/usr/local/lib/python3.2/dist-packages/kombu/mixins.py", line 151, in on_decode_error
    message.ack()
  File "/usr/local/lib/python3.2/dist-packages/amqp/serialization.py", line 375, in __getattr__
    raise AttributeError(name)
AttributeError: ack

But if I execute it without compression in client.py file all is ok and I dont't get any exception. Also exception does not thrown when I comment out block in utils.encoding.bytes_to_str in that way:

def bytes_to_str(s):
        #if isinstance(s, bytes):
        #    return s.decode()
        return s

**Comment by xwj0813** [comment]
I also have this issue
