### ISSUE TITLE
Nofile error!

### ISSUE THREAD

**Issue by arashm404** [celery/kombu#2089]
[2024-08-04 12:21:58,657: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//                                                          
[2024-08-04 12:21:58,661: INFO/MainProcess] mingle: searching for neighbors                                                                        
[2024-08-04 12:22:00,523: INFO/MainProcess] mingle: sync with 9 nodes                                                                              
[2024-08-04 12:22:00,523: INFO/MainProcess] mingle: sync complete                                                                                  
[2024-08-04 12:22:00,537: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'fileno'")                 
Traceback (most recent call last):                                                                                                                 
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/worker.py", line 202, in start                                                       
    self.blueprint.start(self)                                                                                                                     
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 116, in start                                                           
    step.start(parent)                                                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 365, in start                                                           
    return self.obj.start()                                                                                                                        
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/consumer/consumer.py", line 340, in start                                            
    blueprint.start(self)                                                                                                                          
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 116, in start                                                           
    step.start(parent)                                                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/consumer/consumer.py", line 746, in start                                            
    c.loop(*c.loop_args())                                                                                                                         
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/loops.py", line 62, in asynloop                                                      
    obj.controller.register_with_event_loop(hub)                                                                                                   
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/worker.py", line 214, in register_with_event_loop                                    
    self.blueprint.send_all(                                                                                                                       
  File "/usr/local/lib/python3.10/dist-packages/celery/bootsteps.py", line 148, in send_all                                                        
    fun(parent, *args)                                                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/celery/worker/components.py", line 175, in register_with_event_loop                                
    w.pool.register_with_event_loop(hub)                                                                                                           
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/prefork.py", line 137, in register_with_event_loop                              
    return reg(loop)                                                                                                                               
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 519, in register_with_event_loop                             
    [self._track_child_process(w, hub) for w in self._pool]                                                                                        
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 519, in <listcomp>                                           
    [self._track_child_process(w, hub) for w in self._pool]                                                                                        
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 500, in _track_child_process                                 
    iterate_file_descriptors_safely(                                                                                                               
  File "/usr/local/lib/python3.10/dist-packages/celery/concurrency/asynpool.py", line 215, in iterate_file_descriptors_safely
    hub_method(fd, *hub_args, **hub_kwargs)                                                                                                        
  File "/usr/local/lib/python3.10/dist-packages/kombu/asynchronous/hub.py", line 221, in add_reader
    return self.add(fds, callback, READ | ERR, args)                                                                                               
  File "/usr/local/lib/python3.10/dist-packages/kombu/asynchronous/hub.py", line 169, in add
    fd = fileno(fd)                                                      
  File "/usr/local/lib/python3.10/dist-packages/kombu/utils/compat.py", line 95, in fileno
    return f.fileno()                                                    
AttributeError: 'NoneType' object has no attribute 'fileno'  

whats problem? 
also root@ubuntu ~ # ulimit -n
512000

root@dariview ~/v2/services # celery -A services report

software -> celery:5.4.0 (opalescent) kombu:5.3.7 py:3.10.12
            billiard:4.2.0 py-amqp:5.2.0
platform -> system:Linux arch:64bit
            kernel version:5.15.0-100-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:cache

broker_connection_retry_on_startup: True
broker_pool_limit: 32768
broker_url: 'amqp://guest:********@localhost:5672//'
cache_backend: 'memory'
enable_utc: True
imports: 
    ('services',)
pubrl: '30000/m'
result_backend: 'cache'
result_expires: 10800
task_acks_late: True
task_annotations: 
    'services.send_emails': {'rate_limit': '5000/m'},
task_ignore_result: True
worker_max_memory_per_child: 150000
worker_max_tasks_per_child: 60000
deprecated_settings: None

**Comment by thedrow** [comment]
Do you have a minimally reproducible test case to reproduce this issue?

**Comment by arashm404** [comment]
> Do you have a minimally reproducible test case to reproduce this issue?

No! it happens randomly after several hours of running worker with heavy number of tasks and its not happening very easily also it wont take long i mean after i facing this error if i re run worker everything is fine
