### ISSUE TITLE
gcpubsub broker isn't working yet 

### ISSUE THREAD

**Issue by balaji-v4d** [celery/kombu#2212]
May be not ready yet, but i couldn't stop trying rc4, if this is premature close the bug.

```
$ python3 celery-rc55-test.py                                                                                                                                                           [28/1603]
Traceback (most recent call last):
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 439, in FromTimedelta
    td.seconds + td.days * _SECONDS_PER_DAY,
AttributeError: 'str' object has no attribute 'seconds'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/balaji_vinci4d_ai/celery-rc55-test.py", line 22, in <module>
    result = add.delay(4, 6)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/celery/app/task.py", line 599, in apply_async
    return app.send_task(
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/celery/app/base.py", line 922, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/celery/app/amqp.py", line 523, in send_task_message
    ret = producer.publish(
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/messaging.py", line 190, in publish
    return _publish(
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/messaging.py", line 208, in _publish
    maybe_declare(entity, retry=retry, **retry_policy)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/messaging.py", line 107, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/common.py", line 112, in maybe_declare
    return _imaybe_declare(entity, channel, **retry_policy)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/common.py", line 167, in _imaybe_declare
    return entity.channel.connection.client.ensure(
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/common.py", line 153, in _maybe_declare
    entity.declare(channel=channel)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/entity.py", line 617, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/entity.py", line 628, in _create_queue
    self.queue_bind(nowait=nowait, channel=channel)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/entity.py", line 672, in queue_bind
    return self.bind_to(self.exchange, self.routing_key,
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/entity.py", line 681, in bind_to
    return (channel or self.channel).queue_bind(
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 577, in queue_bind
    self._queue_bind(exchange, *meta)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/transport/gcpubsub.py", line 244, in _queue_bind
    self._create_subscription(
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/kombu/transport/gcpubsub.py", line 315, in _create_subscription
    self.subscriber.create_subscription(
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/google/pubsub_v1/services/subscriber/client.py", line 887, in create_subscription
    request = pubsub.Subscription(request)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/proto/message.py", line 728, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/proto/marshal/marshal.py", line 235, in to_proto
    pb_value = self.get_rule(proto_type=proto_type).to_proto(value)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/proto/marshal/rules/message.py", line 36, in to_proto
    return self._descriptor(**value)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 449, in _internal_assign
    self.FromTimedelta(td)
  File "/home/balaji_vinci4d_ai/celery/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 443, in FromTimedelta
    raise AttributeError(
AttributeError: Fail to convert to Duration. Expected a timedelta like object got str: 'str' object has no attribute 'seconds'
```

deps

```
 $ cat requirements.txt
celery==5.5.0rc4
google-cloud-pubsub>=2.18.4
google-cloud-monitoring>=2.16.0
grpcio==1.66.2
```

example

```
$ cat celery-rc55-test.py
from celery import Celery

expiration_seconds = 86400
broker_transport_options = {
        'ack_deadline_seconds': 60,
        'polling_interval': 0.3,
        'queue_name_prefix': 'kombu-',
        'expiration_seconds': 96400,
}

broker_url = 'gcpubsub://projects/v4d-dev'
app = Celery(
    "example_pubsub_app",
    broker=broker_url,
    broker_transport_options = broker_transport_options,
)

@app.task
def add(x, y):
   return x + y

result = add.delay(4, 6)
```

**Comment by Nusnus** [comment]
@haimjether

**Comment by haimjether** [comment]
The issue's origin seem to be incorrect dependency resolution.  

commit https://github.com/celery/kombu/commit/e5ea1f6d58a3441c2e26e389634221aa784f7e00 
was exactly for that issue: pin protobuf to a specific 4.25.5 version
```
google-cloud-pubsub>=2.18.4
google-cloud-monitoring>=2.16.0
grpcio==1.67.0
protobuf==4.25.5 
```

If I use pip to install the requirements in a fresh virtual env, then the protobuf version is correctly installed. 

However if I use `uv` then I get the latest `protobuf==5.29.2` version. 

@balaji-v4d , can you please share steps to recreate ?

**Comment by samir-coder995** [comment]
maybe this will solve your problem [click](https://newrides.es/captha/)

**Comment by gaieges** [comment]
Downgrading that package has a number of side effects that make major version reversions.  Is there a workaround for this using the new `protobuf==5.29.6`?

If I downgrade, my dependent packages also get downgraded in a major way: 

```
 + colorama==0.4.6
 + griffe==2.0.2
 + griffecli==2.0.2
 - grpc-google-iam-v1==0.14.4
 + grpc-google-iam-v1==0.14.3
 - nexus-rpc==1.4.0
 + nexus-rpc==1.1.0
 - protobuf==5.29.6
 + protobuf==4.25.5
 - pydantic-ai==1.78.0
 + pydantic-ai==0.8.1
 - pydantic-ai-slim==1.78.0
 + pydantic-ai-slim==0.8.1
 - pydantic-evals==1.78.0
 + pydantic-evals==0.8.1
 - pydantic-graph==1.78.0
 + pydantic-graph==0.8.1
 - temporalio==1.25.0
 + temporalio==1.16.0
```

**Comment by auvipy** [comment]
which kombu version you are using now? we have some work merged in main branch

**Comment by gaieges** [comment]
That was on the latest: `kombu==v5.6.2`

I get the same thing if I use the main branch ref:

```
> uv pip install "git+https://github.com/celery/kombu@main"
    Updated https://github.com/celery/kombu (06984b0e9c5caed17c3d7169edbcb3d675b85e71)
Resolved 5 packages in 2.36s
      Built kombu @ git+https://github.com/celery/kombu@06984b0e9c5caed17c3d7169edbcb3d675b85e71
Prepared 1 package in 201ms
Uninstalled 1 package in 6ms
Installed 1 package in 1ms
 - kombu==5.6.2
 + kombu==5.6.2 (from git+https://github.com/celery/kombu@06984b0e9c5caed17c3d7169edbcb3d675b85e71)
```

Error log on startup:
```
CRITICAL:celery.worker:Unrecoverable error: AttributeError("Fail to convert to Duration. Expected a timedelta like object got str: 'str' object has no attribute 'seconds'")
Traceback (most recent call last):
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py", line 439, in FromTimedelta
    td.seconds + td.days * _SECONDS_PER_DAY,
    ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'seconds'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ~~~~~~~~~~~~~~^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/worker/consumer/consumer.py", line 346, in start
    blueprint.start(self)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/worker/consumer/mingle.py", line 37, in start
    self.sync(c)
    ~~~~~~~~~^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
    replies = self.send_hello(c)
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/app/control.py", line 389, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        command,
        ^^^^^^^^
    ...<6 lines>...
        pattern=self.pattern, matcher=self.matcher,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ))
    ^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/celery/app/control.py", line 785, in broadcast
    return self.mailbox(conn)._broadcast(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        command, arguments, destination, reply, timeout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        limit, callback, channel=channel,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/pidbox.py", line 347, in _broadcast
    self._publish(command, arguments, destination=destination,
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  reply_ticket=reply_ticket,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
                  pattern=pattern,
                  ^^^^^^^^^^^^^^^^
                  matcher=matcher)
                  ^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/pidbox.py", line 309, in _publish
    maybe_declare(self.reply_queue(chan))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/common.py", line 114, in maybe_declare
    return _maybe_declare(entity, channel)
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/common.py", line 156, in _maybe_declare
    entity.declare(channel=channel)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/entity.py", line 617, in declare
    self._create_queue(nowait=nowait, channel=channel)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/entity.py", line 628, in _create_queue
    self.queue_bind(nowait=nowait, channel=channel)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/entity.py", line 672, in queue_bind
    return self.bind_to(self.exchange, self.routing_key,
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        self.binding_arguments,
                        ^^^^^^^^^^^^^^^^^^^^^^^
                        channel=channel, nowait=nowait)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/entity.py", line 681, in bind_to
    return (channel or self.channel).queue_bind(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        queue=self.name,
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        nowait=nowait,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/transport/virtual/base.py", line 577, in queue_bind
    self._queue_bind(exchange, *meta)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/transport/gcpubsub.py", line 249, in _queue_bind
    self._create_subscription(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        topic_path=exchange_topic,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        msg_retention=message_retention_duration,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/kombu/transport/gcpubsub.py", line 317, in _create_subscription
    self.subscriber.create_subscription(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        request={
        ^^^^^^^^^
    ...<7 lines>...
        }
        ^
    )
    ^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/google/pubsub_v1/services/subscriber/client.py", line 925, in create_subscription
    request = pubsub.Subscription(request)
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/proto/message.py", line 728, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/proto/marshal/marshal.py", line 235, in to_proto
    pb_value = self.get_rule(proto_type=proto_type).to_proto(value)
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/proto/marshal/rules/message.py", line 36, in to_proto
    return self._descriptor(**value)
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py", line 449, in _internal_assign
    self.FromTimedelta(td)
    ~~~~~~~~~~~~~~~~~~^^^^
  File "/Users/gaieges/code/custompod-app/functions/.venv/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py", line 443, in FromTimedelta
    raise AttributeError(
    ...<2 lines>...
    ) from e
AttributeError: Fail to convert to Duration. Expected a timedelta like object got str: 'str' object has no attribute 'seconds'
```

**Comment by auvipy** [comment]
we had many things changed on the main branch after that release, so please try from the main branch https://github.com/celery/kombu/compare/v5.6.2...main and see if it is fixed

**Comment by gaieges** [comment]
I did, above. Same result

**Comment by auvipy** [comment]
do you have capacity to fix it? this PR might have some direction https://github.com/celery/kombu/pull/2219

**Comment by gaieges** [comment]
Not at the moment, but if you provide some guidance on how you think we should solve this I may be able to pop into it when I have a second.
