### ISSUE TITLE
ValueError: Unterminated string starting originates from _receive in kombu/transport/redis.py

### ISSUE THREAD

**Issue by RyanBalfanz** [celery/kombu#329]
Not really sure where to start with this one, or where to report it.

``` bash
[2014-03-22 23:24:50,115: WARNING/MainProcess] Cannot process event on channel 'celeryev': {'pattern': 'celeryev', 'type': 'pmessage', 'channel': 'celeryev', 'data': '{"body": "<redacted gibberish text>
Traceback (most recent call last):
  File "/Users/rbalfanz/.virtualenvs/cat/lib/python2.7/site-packages/kombu/transport/redis.py", line 583, in _receive
    message = loads(bytes_to_str(payload['data']))
  File "/Users/rbalfanz/.virtualenvs/cat/lib/python2.7/site-packages/anyjson/__init__.py", line 135, in loads
    return implementation.loads(value)
  File "/Users/rbalfanz/.virtualenvs/cat/lib/python2.7/site-packages/anyjson/__init__.py", line 99, in loads
    return self._decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 10 (char 9)
```

I'm sending messages containing messages which may be quite large. My celery tasks return Python lists containing 1000s to 100000s elements, which may not be a best practice…

**Comment by auvipy** [comment]
I think this issue is not relevant now. we can reopen it later
