### ISSUE TITLE
SQS: Limit queue_name to 80 characters or allow customization of pidbox queue_name

### ISSUE THREAD

**Issue by pconerly** [celery/kombu#387]
@ask 

When the queue name is more than 80 characters long we get an error from SQS.

```
[2014-08-04 15:49:42,734: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/celery/worker/pidbox.py", line 46, in start
    self.consumer = self.node.listen(callback=self.on_message)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/pidbox.py", line 94, in listen
    on_decode_error=self.on_decode_error)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/pidbox.py", line 81, in Consumer
    **options
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/messaging.py", line 359, in __init__
    self.revive(self.channel)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/messaging.py", line 371, in revive
    self.declare()
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/messaging.py", line 381, in declare
    queue.declare()
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/entity.py", line 505, in declare
    self.queue_declare(nowait, passive=False)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/entity.py", line 531, in queue_declare
    nowait=nowait)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 446, in queue_declare
    self._new_queue(queue, **kwargs)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/kombu/transport/SQS.py", line 265, in _new_queue
    queue, self.visibility_timeout,
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/boto/sqs/connection.py", line 91, in create_queue
    return self.get_object('CreateQueue', params, Queue)
  File "/Users/peterconerly/src/derp/build/ve/lib/python2.7/site-packages/boto/connection.py", line 916, in get_object
    raise self.ResponseError(response.status, response.reason, body)
SQSError: SQSError: 400 Bad Request
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2011-10-01/"><Error><Type>Sender</Type><Code>InvalidParameterValue</Code><Message>Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length</Message><Detail/></Error><RequestId>derp</RequestId></ErrorResponse>
```

Our first queuename is fine, but a second queue is made using the `[computer_name]-celery-pidbox` syntax.  The `[computer_name]` is sometimes fairly long.  (Looking at the code, it's coming from [here](https://github.com/celery/kombu/blob/146758ce7bf35740d5bc838e317ee91795e76a29/kombu/pidbox.py#L229)  )

We've "fixed" this by editing our `boto` installation to trim `queue_name`s to 80 characters.

`/lib/python2.7/site-packages/boto/connection.py, line 898`:  (added lines in bold)

<pre>
    def get_object(self, action, params, cls, path='/',
                   parent=None, verb='GET'):
        if not parent:
            parent = self
        <b>if params and ('QueueName' in params):
            params['QueueName'] = params['QueueName'][0:80]</b>
        response = self.make_request(action, params, path, verb)
        body = response.read()
        boto.log.debug(body)
        if not body:
</pre>
But I think you'd agree that it's a pretty gross hack.  Since `kombu` is handling SQS, I think it should be checking for valid queue names.

So!  I'd like to either:

* Have an 80 character limit on `queue_name`s when using SQS
* Allow customization of the pidbox `queue_name`.

Thanks a bunch!

**Comment by tuky** [comment]
this was already released, wasn't it? can be closed then? btw, if solved, what were the commits?
