### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by suquant** [celery/kombu#434]
If celery==3.1.17 && kombu===3.0.24 configured
BROKER_URL = "redis://redis.host:6379/10"
CELERY_RESULT_BACKEND = "redis://redis.host:6379/10"
BROKER_CONNECTION_MAX_RETRIES = 0
BROKER_TRANSPORT_OPTIONS = {
  "max_connections" = 100
}
CELERY_ACKS_LATE: true
CELERYD_PREFETCH_MULTIPLIER: 1
BROKER_POOL_LIMIT: 100
CELERY_REDIS_MAX_CONNECTIONS: 100

Workera crashed with exception:

```
[2014-12-01 01:28:15,250: ERROR/MainProcess] Unrecoverable error: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 97, in synloop
    connection.drain_events(timeout=2.0)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 840, in drain_events
    message, queue = item
TypeError: 'NoneType' object is not iterable
```

**Comment by ask** [comment]
Not able to reproduce here, sending millions of tasks now, so must be some other condition required.

**Comment by kbrownlees** [comment]
I just saw this is one of my runs as well.

redis-server                     2:2.8.4-2
celery==3.1.18
kombu==3.0.26
gevent==1.0.2
greenlet==0.4.7

BROKER: redis://host
RESULTS: redis://host

    celery -A services --loglevel=info --workdir=.. --pool=gevent --concurrency=100 multi start 7

It took out all 7 workers last night, then I restarted them and it happened to 5 of them. Been running for about 30 minutes since then and haven't seen it again.

**Comment by thanatos** [comment]
We see this all the time in our production setup. Also gevent'd.

**Comment by auvipy** [comment]
@thanatos does this happen with new versions of celery/kombu?

**Comment by georgepsarakis** [comment]
This most likely has to do with thread-safety. If you switch to a different pool than gevent, you may stop seeing the issue.

**Comment by georgepsarakis** [comment]
Please also check this issue https://github.com/celery/celery/issues/4363 for reference.
