### ISSUE TITLE
mongodb backend doesn't work with eventlet

### ISSUE THREAD

**Issue by buckensl** [celery/kombu#443]
Celery 3.1.16, Kombu 3.0.23, pymongo 2.7.2

When starting a celery worker with --pool=eventlet, following exception is raised
```
2015-01-19 13:16:28.037 +0000 ERROR [__init__.start] Unrecoverable error: NameError("global name 'GeventEvent' is not defined",)
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "venv/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 478, in start
    c.connection = c.connect()
  File "venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 375, in connect
    callback=maybe_shutdown,
  File "venv/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "venv/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "venv/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "venv/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "venv/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "venv/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "venv/lib/python2.7/site-packages/kombu/transport/mongodb.py", line 91, in __init__
    self._create_client()
  File "venv/lib/python2.7/site-packages/kombu/transport/mongodb.py", line 257, in _create_client
    self._open()
  File "venv/lib/python2.7/site-packages/kombu/transport/mongodb.py", line 182, in _open
    use_greenlets=_detect_environment() != 'default',
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 366, in __init__
    self._ensure_connected(True)
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 930, in _ensure_connected
    self.__ensure_member()
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 793, in __ensure_member
    self.__event_class)
  File "build/bdist.linux-x86_64/egg/pymongo/thread_util.py", line 195, in __init__
    self._event = event_class()
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 346, in <lambda>
    event_class = lambda: thread_util.create_event(g)
  File "build/bdist.linux-x86_64/egg/pymongo/thread_util.py", line 340, in create_event
    return GeventEvent()
NameError: global name 'GeventEvent' is not defined
```

mongodb transport creates MongoClient with use_greenlets = True when either gevent or eventlet is installed
https://github.com/celery/kombu/blob/39a6491013fc35325bfb0517e5343a2f7d32aa31/kombu/transport/mongodb.py#L186
https://github.com/celery/kombu/blob/39a6491013fc35325bfb0517e5343a2f7d32aa31/kombu/syn.py#L23-L46

pymongo assumes you're using gevent when use_greenlets equals True
https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/thread_util.py#L338-L340

**Comment by ask** [comment]
Then isn't the problem with pymong? Or what option must we use for eventlet?

**Comment by buckensl** [comment]
pymongo added support for eventlet as of 3.0 (according to their changelog: https://github.com/mongodb/mongo-python-driver/blob/70185ff98eb815ce2e7a40577bfdcf5c227e391a/doc/changelog.rst)
Older version only support gevent

**Comment by ask** [comment]
Supoprt for MongoDB as a broker is deprecated as we don't have the resources to maintain it :(
