### ISSUE TITLE
redis transport poller descriptor leak

### ISSUE THREAD

**Issue by fillest** [celery/kombu#462]
Hello. It seems there's descriptor leak in kombu/transport/redis.py. We use celery with redis, disk got full, redis crashed, celery lost its connection with redis and started to reconnect. After some time I found lots of the following error in the log:

```
[2015-03-25 09:41:48,438: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 478, in start
    c.connection = c.connect()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 375, in connect
    callback=maybe_shutdown,
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/connection.py", line 367, in ensure_connection
    retry_over_time(self.connect, self.recoverable_connection_errors,
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/connection.py", line 786, in recoverable_connection_errors
    return self.transport.recoverable_connection_errors
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/connection.py", line 769, in transport
    self._transport = self.create_transport()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/connection.py", line 514, in create_transport
    return self.get_transport_cls()(client=self)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 923, in __init__
    self.cycle = MultiChannelPoller()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 237, in __init__
    self.poller = poll()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/utils/eventio.py", line 265, in poll
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/utils/eventio.py", line 74, in __init__
IOError: [Errno 24] Too many open files
```

I've checked `lsof` and there's over a thousand of `anon_inode:[eventpoll]` of `celeryd` so I think it's a strong corellation.
Version is 3.0.24.

**Comment by ask** [comment]
So seems this is only related to reconnecting, or do you see thousands of entries in normal operation?

**Comment by ask** [comment]
Not seeing any problems with reconnecting here on OS X.  Trying to reproduce by counting filedescriptors as I take redis online and offline.  The number stays constant.

The code is different on Linux though, but I don't have Linux running here.

**Comment by fillest** [comment]
>So seems this is only related to reconnecting
Yes.

**Comment by fillest** [comment]
> counting filedescriptors as I take redis online and offline.

Have you tried to reconnect more then one time after taking redis offline?

**Comment by ask** [comment]
Yeah, I tried to leave it reconnecting for a few times now. And still no leak, but not that this is on OS X

**Comment by catastropheey** [comment]
I meet up the same issue, I'm using redis sentinel to connect the broker and  thousands of `anon_inode:[eventpoll]` of `celeryd`  presented

versions
celery: 4.2.1
kombu: 4.2.1
redis: 2.10.6

Traceback:
[2019-02-16 22:12:04,862: ERROR/MainProcess] Control command error: ConnectionError(u'Error 24 connecting to 172.16.10.34:6379. Too many open files.',)
Traceback (most recent call last):
  File "/venv/awx/lib/python2.7/site-packages/celery/worker/pidbox.py", line 46, in on_message
    self.node.handle_message(body, message)
  File "/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/venv/awx/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 605, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/venv/awx/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 70, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/venv/awx/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 714, in _lookup
    self.get_table(exchange),
  File "/venv/awx/lib/python2.7/site-packages/kombu/transport/redis.py", line 815, in get_table
    values = client.smembers(key)
  File "/venv/awx/lib/python2.7/site-packages/redis/client.py", line 1638, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/venv/awx/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/venv/awx/lib/python2.7/site-packages/redis/connection.py", line 613, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/venv/awx/lib/python2.7/site-packages/redis/connection.py", line 588, in send_packed_command
    self.connect()
  File "/venv/awx/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 24 connecting to 172.16.10.34:6379. Too many open files.
