### ISSUE TITLE
latest version of pymongo fails 1 test in kombu-3.0.26; test_options

### ISSUE THREAD

**Issue by idella** [celery/kombu#474]
with pymongo-3.0

```bash
======================================================================
ERROR: test_options (kombu.tests.transport.test_mongodb.test_mongodb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/kombu-3.0.24/work/kombu-3.0.24/kombu/tests/case.py", line 188, in _skip_if_not_module
    return fun(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/kombu-3.0.24/work/kombu-3.0.24/kombu/tests/transport/test_mongodb.py", line 70, in test_options
    hostname, dbname, options = c.channels[0]._parse_uri()
  File "/mnt/gen2/TmpDir/portage/dev-python/kombu-3.0.24/work/kombu-3.0.24/kombu/transport/mongodb.py", line 157, in _parse_uri
    parsed = uri_parser.parse_uri(hostname, port)
  File "/usr/lib64/python2.7/site-packages/pymongo/uri_parser.py", line 305, in parse_uri
    options = split_options(opts, validate)
  File "/usr/lib64/python2.7/site-packages/pymongo/uri_parser.py", line 205, in split_options
    return validate_options(options)
  File "/usr/lib64/python2.7/site-packages/pymongo/uri_parser.py", line 159, in validate_options
    return dict([_validate(opt, val) for opt, val in iteritems(opts)])
  File "/usr/lib64/python2.7/site-packages/pymongo/common.py", line 425, in validate
    value = validator(option, value)
  File "/usr/lib64/python2.7/site-packages/pymongo/common.py", line 100, in raise_config_error
    raise ConfigurationError("Unknown option %s" % (key,))
ConfigurationError: Unknown option safe

----------------------------------------------------------------------
Ran 852 tests in 11.972s

FAILED (SKIP=109, errors=1)
```

but passes with pymongo-2.8

**Comment by buckensl** [comment]
should be fixed by 8e6aed9fcf978b6c34108c0d37b720bd125f0352
