### ISSUE TITLE
Using ?new_join=1 in BROKER_URL for celery causes TypeError

### ISSUE THREAD

**Issue by aarcro** [celery/kombu#496]
```
$ celery -A app worker -c 1 --loglevel=DEBUG
Traceback (most recent call last):
  File "/virtual_envs/massimport/bin/celery", line 9, in <module>
    load_entry_point('celery==3.2.0a2', 'console_scripts', 'celery')()
  File "/src/celery/celery/__main__.py", line 30, in main
    main()
  File "/src/celery/celery/bin/celery.py", line 83, in main
    cmd.execute_from_commandline(argv)
  File "/src/celery/celery/bin/celery.py", line 780, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/src/celery/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/src/celery/celery/bin/celery.py", line 772, in handle_argv
    return self.execute(command, argv)
  File "/src/celery/celery/bin/celery.py", line 704, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/src/celery/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/src/celery/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/src/celery/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/src/celery/celery/worker/__init__.py", line 102, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/src/celery/celery/worker/__init__.py", line 126, in setup_instance
    self._conninfo = self.app.connection()
  File "/src/celery/celery/app/base.py", line 426, in connection
    'BROKER_CONNECTION_TIMEOUT', connect_timeout
  File "/src/kombu/kombu/connection.py", line 171, in __init__
    self._init_params(**params)
TypeError: _init_params() got an unexpected keyword argument 'new_join'
```

Maybe it's odd that Celery triggers the new_join behavior through a url param that the backend doesn't really support. But we can just ignore it by adding **kwargs to the signature

**Comment by ask** [comment]
`new_join` is not an option for the kombu transport, it's only an option for the Celery redis result backend.

It's currently only supported in the URL since it's an experimental feature, there should be a more convenient way to configure this (if not the default), by the time the feature is released.
