### ISSUE TITLE
Should retry on ConnectionError("Socket was disconnected")

### ISSUE THREAD

**Issue by neaket360pi** [celery/kombu#507]
We encountered a ConnectionError when a node on RabbitMQ was restarted.  Unfortunately  this caused all of our celery workers to get into a bad state, and they were not consuming any tasks.  

My suggested fix is to raise a RecoverableConnectionError instead of a ConnectionError. on line https://github.com/celery/kombu/blob/master/kombu/transport/base.py#L157

**Stack Trace:** Note this stack trace is from kombu version 3.0.21
```python
[2015-08-21 22:22:43,407: WARNING/MainProcess]  consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/base.py", line 162, in on_readable
    reader(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/base.py", line 142, in _read
    raise ConnectionError('Socket was disconnected')
ConnectionError: Socket was disconnected
```

**Comment by neaket360pi** [comment]
Thanks you.

**Comment by parkour99** [comment]
environment: 
celery: 3.1.25
kombu: 3.0.23
i aslo met this problem. when a rabbitmq node suddenly restarted, so the celery raise a RecoverableConnectionError exception.
but i think When celery raise RecoverableConnectionError, we should aslo retry to establish the connection again.
otherwise, we must restart worker by hand.
besides when celery worker raise RecoverableConnectionError, the worker main process did not catch the exception and not stop the worker. 

how should the celery process the 'RecoverableConnectionError' to recovery the worker?
any ideas would be appricated

**Comment by thedrow** [comment]
We don't support Celery 3.

**Comment by hahsfb** [comment]
It is also possible that the server network bandwidth is not enough.
