### ISSUE TITLE
Can i implement rpc with kombu?

### ISSUE THREAD

**Issue by zohaibtechknox** [celery/kombu#530]
I have worked on rpc with pika client but I have studied that openstack is using kumbo to do this so I have started searching a script of kumbo to implement rpc but found nothing. Please answer me if i can implemnt rpc with kumbi alone . I am aware of the other methods explain in some thread a ssame forum like https://github.com/celery/kombu/issues/430 .. I just want to know that can i implement the thing explain in this link http://www.rabbitmq.com/tutorials/tutorial-six-python.html . Thanks

**Comment by ask** [comment]
I created kombu versions of the tutorial for you.

I couldn't get auto generated queues to work, as I got an "Access Denied": error, but you can try by replacing `Queue(uuid(), exclusive=True, auto_delete=True)` with `Queue(exclusive=True)` in `rpc_client.py`.

Note also that the prefetch_count argument to Consumer is new in the development version,
and also the ConsumerProducerMixin that I just added now in the second patch.

**Comment by zohaibtechknox** [comment]
Thankyou for your reply.

**Comment by eavictor** [comment]
Hi, I'm getting `TypeError: object of type 'Queue' has no len()` when executing rpc_client.py
Tried replacing `Queue(uuid(), exclusive=True, auto_delete=True)` with `Queue(exclusive=True)` but still getting same error.

### python 3.5.2
### kombu 4.0.0rc6
### Traceback:
`Traceback (most recent call last):
  File "C:/Users/ITPROAdmin/PycharmProjects/MQ_Example/rpc_client.py", line 46, in <module>
    main('amqp://my_secret_url')
  File "C:/Users/ITPROAdmin/PycharmProjects/MQ_Example/rpc_client.py", line 41, in main
    response = fibonacci_rpc.call(30)
  File "C:/Users/ITPROAdmin/PycharmProjects/MQ_Example/rpc_client.py", line 27, in call
    correlation_id=self.correlation_id,
  File "C:\Users\ITPROAdmin\AppData\Local\Programs\Python\Python35\lib\site-packages\kombu\messaging.py", line 175, in publish
    exchange_name, declare,
  File "C:\Users\ITPROAdmin\AppData\Local\Programs\Python\Python35\lib\site-packages\kombu\messaging.py", line 197, in _publish
    mandatory=mandatory, immediate=immediate,
  File "C:\Users\ITPROAdmin\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\channel.py", line 1748, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "C:\Users\ITPROAdmin\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\abstract_channel.py", line 64, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "C:\Users\ITPROAdmin\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\method_framing.py", line 114, in write_frame
    properties = content._serialize_properties()
  File "C:\Users\ITPROAdmin\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\serialization.py", line 555, in _serialize_properties
    write(dumps(b''.join(sformat), svalues))
  File "C:\Users\ITPROAdmin\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\serialization.py", line 308, in dumps
    write(pack(b'B', len(val)))
TypeError: object of type 'Queue' has no len()`
