### ISSUE TITLE
Oracle Backend DatabaseError: ORA-00907: missing right parenthesis

### ISSUE THREAD

**Issue by mbande** [celery/kombu#535]
after installing Celery as mentioned in the [docs](http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html), trying to run Celery worker, i get
```
 -------------- celery@linux v3.1.19 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-3.16.0-51-generic-x86_64-with-Ubuntu-14.04-trusty
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         sample:0x7fb5a48255d0
- ** ---------- .> transport:   django://localhost//
- ** ---------- .> results:     djcelery.backends.database:DatabaseBackend
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . sample.celery.debug_task
  . report.tasks.add
  . report.tasks.mul
  . report.tasks.xsum

[2015-11-04 14:32:54,702: INFO/Beat] beat: Starting...
[2015-11-04 14:32:54,719: INFO/MainProcess] Connected to django://localhost//
[2015-11-04 14:32:54,788: DEBUG/MainProcess] (0.001) QUERY = u'SELECT "DJKOMBU_QUEUE"."ID", "DJKOMBU_QUEUE"."NAME" FROM "DJKOMBU_QUEUE" WHERE "DJKOMBU_QUEUE"."NAME" = :arg0' - PARAMS = (u'celery',); args=('celery',)
[2015-11-04 14:32:54,791: DEBUG/MainProcess] (0.001) QUERY = u'SELECT "DJKOMBU_QUEUE"."ID", "DJKOMBU_QUEUE"."NAME" FROM "DJKOMBU_QUEUE" WHERE "DJKOMBU_QUEUE"."NAME" = :arg0' - PARAMS = (u'celery',); args=('celery',)
[2015-11-04 14:32:54,794: DEBUG/MainProcess] (0.001) QUERY = u'SELECT COUNT(*) AS "__COUNT" FROM "DJKOMBU_MESSAGE" WHERE "DJKOMBU_MESSAGE"."QUEUE_ID" = :arg0' - PARAMS = (1,); args=(1,)
[2015-11-04 14:32:54,797: DEBUG/MainProcess] (0.001) QUERY = u'SELECT "DJKOMBU_QUEUE"."ID", "DJKOMBU_QUEUE"."NAME" FROM "DJKOMBU_QUEUE" WHERE "DJKOMBU_QUEUE"."NAME" = :arg0' - PARAMS = (u'celery@linux.celery.pidbox',); args=(u'celery@linux.celery.pidbox',)
[2015-11-04 14:32:54,799: DEBUG/MainProcess] (0.001) QUERY = u'SELECT "DJKOMBU_QUEUE"."ID", "DJKOMBU_QUEUE"."NAME" FROM "DJKOMBU_QUEUE" WHERE "DJKOMBU_QUEUE"."NAME" = :arg0' - PARAMS = (u'celery@linux.celery.pidbox',); args=(u'celery@linux.celery.pidbox',)
[2015-11-04 14:32:54,802: DEBUG/MainProcess] (0.001) QUERY = u'SELECT COUNT(*) AS "__COUNT" FROM "DJKOMBU_MESSAGE" WHERE "DJKOMBU_MESSAGE"."QUEUE_ID" = :arg0' - PARAMS = (2,); args=(2,)
[2015-11-04 14:32:54,803: WARNING/MainProcess] /usr/local/lib/python2.7/dist-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2015-11-04 14:32:54,803: WARNING/MainProcess] celery@linux ready.
[2015-11-04 14:32:54,805: DEBUG/MainProcess] (0.001) QUERY = u'SELECT "DJKOMBU_QUEUE"."ID", "DJKOMBU_QUEUE"."NAME" FROM "DJKOMBU_QUEUE" WHERE "DJKOMBU_QUEUE"."NAME" = :arg0' - PARAMS = (u'celery',); args=('celery',)
[2015-11-04 14:32:54,810: DEBUG/MainProcess] (0.002) QUERY = u'SELECT * FROM (SELECT "_SUB".*, ROWNUM AS "_RN" FROM (SELECT "DJKOMBU_MESSAGE"."ID" AS Col1, "DJKOMBU_MESSAGE"."VISIBLE" AS Col2, "DJKOMBU_MESSAGE"."SENT_AT" AS Col3, "DJKOMBU_MESSAGE"."PAYLOAD" AS Col4, "DJKOMBU_MESSAGE"."QUEUE_ID" AS Col5 FROM "DJKOMBU_MESSAGE" WHERE ("DJKOMBU_MESSAGE"."QUEUE_ID" = :arg0 AND "DJKOMBU_MESSAGE"."VISIBLE" = :arg1) ORDER BY "DJKOMBU_MESSAGE"."SENT_AT" ASC, "DJKOMBU_MESSAGE"."ID" ASC FOR UPDATE) "_SUB" WHERE ROWNUM <= 1) WHERE "_RN" > 0' - PARAMS = (1, True); args=(1, True)
[2015-11-04 14:32:54,811: ERROR/MainProcess] Unrecoverable error: DatabaseError(<cx_Oracle._Error object at 0x7fb59ce8f5d0>,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 103, in synloop
    connection.drain_events(timeout=2.0)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 830, in drain_events
    item, channel = get(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/scheduling.py", line 39, in get
    return self.fun(resource, **kwargs), resource
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 850, in _drain_channel
    return channel.drain_events(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 642, in drain_events
    return self._poll(self.cycle, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 328, in _poll
    return cycle.get()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/scheduling.py", line 39, in get
    return self.fun(resource, **kwargs), resource
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/django/__init__.py", line 49, in _get
    m = self.Queue.objects.fetch(queue)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/django/managers.py", line 37, in fetch
    return queue.messages.pop()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/django/managers.py", line 21, in _commit
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/django/managers.py", line 71, in pop
    result = resultset[0:1].get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/oracle/base.py", line 478, in execute
    return self.cursor.execute(query, self._param_generator(params))
DatabaseError: ORA-00907: missing right parenthesis

[2015-11-04 14:32:55,818: INFO/MainProcess] beat: Shutting down...
```

**Comment by ask** [comment]
Fixed by 696d4d0e2584ed7e276f02362dd5b8f6dd5a5bfe, new release shortly
