### ISSUE TITLE
incompatible for py2.7.11

### ISSUE THREAD

**Issue by rexzhang** [celery/kombu#546]
~~~
(vent-haohelper)rex-mbp15:haohelper rex$ celery -A haohelper worker --loglevel=INFO
Traceback (most recent call last):
  File "/Users/rex/py/haohelper/vent/bin/celery", line 7, in <module>
    from celery.__main__ import main
  File "/Users/rex/py/haohelper/vent/lib/python2.7/site-packages/celery/__init__.py", line 131, in <module>
    from celery import five  # noqa
  File "/Users/rex/py/haohelper/vent/lib/python2.7/site-packages/celery/five.py", line 153, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
  File "/Users/rex/py/haohelper/vent/lib/python2.7/site-packages/kombu/utils/__init__.py", line 19, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name _uuid_generate_random
~~~

ref: https://github.com/python/cpython/commit/0a167ba55d7b78ddf958cbd47a484e06aa98b892

**Comment by malinoff** [comment]
Duplicate https://github.com/celery/kombu/pull/540
I really wish github to improve their ticket system and to include duplicate suggestions by default :(

**Comment by ask** [comment]
Kombu 3.0.30 is on PyPI
