### ISSUE TITLE
Support the 'Auth Failure' RabbitMQ protocol extension

### ISSUE THREAD

**Issue by edmorley** [celery/kombu#611]
I'm not sure if this should be filed against kombu or py-amqp (whilst the original exception originates from py-amqp, perhaps it should still be caught and converted to another exception in kombu).

**STR:**
1) `sudo apt-get install rabbitmq-server` on Ubuntu 16.04 (which at time of filing is rabbitmq v3.5.7)
2) `pip install kombu==3.0.35 amqp==1.4.9 anyjson==0.3.3`
3) Run this:
```python
#!/usr/bin/env python

from kombu import Connection

connection = Connection('amqp://guest:invalid_password@localhost:5672')
connection.connect()
print("connection.connected: %s" % connection.connected)
```

**Expected:**
Some error/exception that make it clear that the connection was refused due to invalid username/password, eg:
`AuthenticationError: The supplied credentials were invalid`

**Actual:**
```
Traceback (most recent call last):
  File "./kombu-test.py", line 6, in <module>
    connection.connect()
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/home/vagrant/.virtualenvs/kombu_test/local/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
socket.error: [Errno 104] Connection reset by peer
```

In other environments I've also seen `IOError: Socket closed` ([example](https://bugzilla.mozilla.org/show_bug.cgi?id=1281810#c0)) - I'm guessing the difference is that SSL was enabled there.

This is really frustrating, since the connection error sounds like there was a network issue rather than incorrect credentials -- there have now been at least three occasions in the last 9 months where my team have been trying to debug issues, only to have it turn out to be due to someone rotating credentials (or changing permissions) they shouldn't have (yeah I know...!).

Happy to re-file against py-amqp if more appropriate.

Thanks :-)

**Comment by ask** [comment]
I think this is more of a rabbitmq quirk, as it doesn't give us any error on invalid credentials, it just closes the socket.

**Comment by edmorley** [comment]
Yeah fair point, I've filed rabbitmq/rabbitmq-server#947

That said, should pyamqp/kombu convert the raw `socket.error` / `IOError` into a more library-specific timeout/connection exception?

**Comment by michaelklishin** [comment]
@ask @edmorley authentication failure notifications are available [as of RabbitMQ 3.2.0](http://www.rabbitmq.com/auth-notification.html) — for close to 3 years now — as a protocol extension (the spec dictates that the server must close the socket without sending any more data).

Kombu most support it and indicate it as a client capability.

**Comment by edmorley** [comment]
Thank you for clarifying :-)

I've filed celery/py-amqp#106 and celery/librabbitmq#89 for adding support for the `authentication_failure_close` capability. I'm presuming there will then need to be further changes to Kombu to handle the new exception types that they'll generate, which can be handled by this issue.

**Comment by edmorley** [comment]
See also #373, though I think that `authentication_failure_close` support is best kept in individual libraries themselves, rather than only in Kombu.

**Comment by edmorley** [comment]
Many thanks!
