### ISSUE TITLE
Redis Transport: attemping to create an SSL connection raises an exception

### ISSUE THREAD

**Issue by bkolba** [celery/kombu#628]
Repro environment:
- `kombu==4.0.0rc4`
- `redis-server` running locally

Two bugs here in the Redis transport that break the SSL connection

1. `connection_class` should be `redis.SSLConnection`, not `redis.Connection` (which does not support any ssl parameters). There is a workaround for this by adding `connection_class` to the SSL dict (e.g. via `celery.conf.broker_use_ssl`) since that entire dict ends up being added to `connparams`. That said, the better fix is to explicitly set the `connection_class` here similar to the socket case.

2. Redis-py requires a very specific set of SSL parameters to be passed in to initialize a connection. The supported parameters are:

    - ssl_cert_reqs
    - ssl_ca_certs
    - ssl_certfile
    - ssl_keyfile

    The `ssl` flag that is appended to `connparams` on L883 of `kombu/transport/redis.py` causes `redis.Connection` and `redis.SSLConnection` to fail initialization (stack trace below) due to an unknown keyword. While the `StrictRedis` client understand this keyword, it is not necessary to pipe it through since `KombuRedis` ends up explicitly setting the `connection` property.

```python
>>> from kombu.connection import Connection
>>> with Connection('redis://', ssl=True) as conn:
...     t = conn.connect()

...
Traceback (most recent call last):
  File "kombu/transport/virtual/base.py", line 912, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kombu/utils/objects.py", line 40, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "redis/connection.py", line 895, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "kombu/connection.py", line 258, in connect
    return self.connection
  File "kombu/connection.py", line 798, in connection
    self._connection = self._establish_connection()
  File "kombu/connection.py", line 751, in _establish_connection
    conn = self.transport.establish_connection()
  File "kombu/transport/virtual/base.py", line 932, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "kombu/transport/virtual/base.py", line 914, in create_channel
    channel = self.Channel(connection)
  File "kombu/transport/redis.py", line 490, in __init__
    self.client.ping()
  File "kombu/utils/objects.py", line 42, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "kombu/transport/redis.py", line 976, in client
    return self._create_client(async=True)
  File "kombu/transport/redis.py", line 925, in _create_client
    return self.Client(connection_pool=self.async_pool)
  File "kombu/transport/redis.py", line 946, in __init__
    self.connection = self.connection_pool.get_connection('_')
  File "redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
```

From my testing, this change (https://github.com/textioHQ/kombu/commit/46e0825aedc208a67085c1b3339699d0d2a8a3c7) fixes these issues and allows me to connect to Redis over SSL. Let me know if there's interest in a PR.

**Comment by ask** [comment]
Sure! If that patch works, then please open a pull request!

**Comment by YitianSusanLinLime** [comment]
what is the difference between ssl_ca_certs and ssl_certfile?

**Comment by thedrow** [comment]
@YitianSusanLinLime This is not the place for such questions. Please refer to the documentation.
If something is not clear you may ask on Stackoverflow or IRC.
