### ISSUE TITLE
Failing serialization of itertools.cycle to JSON

### ISSUE THREAD

**Issue by tnsengimana** [celery/kombu#635]
I upgraded kombu from 3.0.35 to 3.0.36 but `itertools.cycle` is not being properly serialized. The behavior works in 3.0.35. This issue happens when serializing events from celery flower.

```python
Traceback (most recent call last):
   File "/usr/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 38, in on_message
     self.node.handle_message(body, message)
   File "/usr/local/lib/python2.7/site-packages/kombu/pidbox.py", line 133, in handle_message
     return self.dispatch(**kwdict(body))
   File "/usr/local/lib/python2.7/site-packages/kombu/pidbox.py", line 116, in dispatch
     ticket=ticket)
   File "/usr/local/lib/python2.7/site-packages/kombu/pidbox.py", line 139, in reply
     serializer=self.mailbox.serializer)
   File "/usr/local/lib/python2.7/site-packages/kombu/pidbox.py", line 245, in _publish_reply
     **opts
   File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 165, in publish
     compression, headers)
   File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 241, in _prepare
     body) = dumps(body, serializer=serializer)
   File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
     payload = encoder(data)
   File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
     self.gen.throw(type, value, traceback)
   File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 59, in _reraise_errors
     reraise(wrapper, wrapper(exc), sys.exc_info()[2])
   File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 55, in _reraise_errors
     yield
   File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
     payload = encoder(data)
   File "/usr/local/lib/python2.7/site-packages/anyjson/__init__.py", line 141, in dumps
     return implementation.dumps(value)
   File "/usr/local/lib/python2.7/site-packages/anyjson/__init__.py", line 87, in dumps
     return self._encode(data)
   File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 380, in dumps
     return _default_encoder.encode(obj)
   File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
     chunks = self.iterencode(o, _one_shot=True)
   File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
     return _iterencode(o, 0)
   File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 252, in default
     raise TypeError(repr(o) + " is not JSON serializable")
 EncodeError: <type 'itertools.cycle'> is not JSON serializable

```

**Comment by ask** [comment]
That's strange, I don't think anything related to this changed.

Do you know what remote control command this is?

I doubt itertools.cycle was ever serializable, it's an infinite data structure so it sounds unlikely.

**Comment by bsgiles** [comment]
I upgraded to 3.0.36 and had exactly the same problem. Pinning at 3.0.35 fixed the issue. No other changes.

**Comment by tnsengimana** [comment]
@ask It seems to be happening when invoking `inspect stats`. This is the full command I am using:

`celery --broker=amqp://guest:guest@10.0.2.2:8025// inspect stats -d my-worker`

**Comment by ask** [comment]
kombu 3.0.37 is on PyPI fixing this issue!
