### ISSUE TITLE
RPC client example TypeError: object of type 'Queue' has no len()

### ISSUE THREAD

**Issue by eavictor** [celery/kombu#639]
@ask 
rpc_client.py is broken in kombu 4.0.0
### environment

python 3.5.2
kombu 4.0.0
RabbitMQ 3.4.2 (CloudAMQP)
### TypeError: object of type 'Queue' has no len()

I have no idea how to fix this, the example code looks correct.
Also tried replacing `Queue(uuid(), exclusive=True, auto_delete=True)` with `Queue(exclusive=True)` in issue #530 

```
Traceback (most recent call last):
  File "C:/Users/EAVICTOR/PycharmProjects/MQ_Example/rpc_client.py", line 46, in <module>
    main('amqp://my_secret_rabbitmq_url')
  File "C:/Users/EAVICTOR/PycharmProjects/MQ_Example/rpc_client.py", line 41, in main
    response = fibonacci_rpc.call(30)
  File "C:/Users/EAVICTOR/PycharmProjects/MQ_Example/rpc_client.py", line 27, in call
    correlation_id=self.correlation_id,
  File "C:\Users\EAVICTOR\AppData\Local\Programs\Python\Python35\lib\site-packages\kombu\messaging.py", line 178, in publish
    exchange_name, declare,
  File "C:\Users\EAVICTOR\AppData\Local\Programs\Python\Python35\lib\site-packages\kombu\messaging.py", line 200, in _publish
    mandatory=mandatory, immediate=immediate,
  File "C:\Users\EAVICTOR\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\channel.py", line 1748, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "C:\Users\EAVICTOR\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\abstract_channel.py", line 64, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "C:\Users\EAVICTOR\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\method_framing.py", line 114, in write_frame
    properties = content._serialize_properties()
  File "C:\Users\EAVICTOR\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\serialization.py", line 555, in _serialize_properties
    write(dumps(b''.join(sformat), svalues))
  File "C:\Users\EAVICTOR\AppData\Local\Programs\Python\Python35\lib\site-packages\amqp\serialization.py", line 308, in dumps
    write(pack(b'B', len(val)))
TypeError: object of type 'Queue' has no len()
```
### [rpc_server.py (gist)](https://gist.github.com/eavictor/f02967653e0fed6b7ac829645da68ed6)

Added multiprocessing and heartbeat, but no idea why rpc_server.py establish 2 connections per process.
The connection with 0 channel will disconnect after first heartbeat is executed.
If I remove heartbeat keyword, then rpc_server.py only creates 1 connection per process (and lost reconnect ability).

**Comment by Carlosedo** [comment]
@eavictor There is a small error in the example that is causing your problem.

I solved it [here](https://github.com/celery/kombu/pull/650)

**Comment by eavictor** [comment]
@Carlosedo Thank you, I tried your fix and it works like a charm. 👍 
I was almost decide to do pika client + kombu server (which is a bad idea).
