### ISSUE TITLE
'NoneType' object has no attribute 'can_read' at redis.py:670

### ISSUE THREAD

**Issue by Cediddi** [celery/kombu#659]
I run celery on docker, redis on another server.
Celery==4.0.0
redis==2.10.5
redis server is v 2.8.4

My celery configuration is very simple, only broker and backend, both are redis. The task I'm running is gunzipping a 10GB file. It takes 10 minutes to finish.

```
Traceback (most recent call last):
  File "/venv/lib/python3.4/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/venv/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/venv/lib/python3.4/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/venv/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/venv/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/venv/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
  File "/venv/lib/python3.4/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/venv/lib/python3.4/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 1038, in on_readable
    self.cycle.on_readable(fileno)
  File "/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 670, in _receive
    while c.connection.can_read(timeout=0):
AttributeError: 'NoneType' object has no attribute 'can_read'
```

**Comment by ask** [comment]
I'd make sure the server timeout configuration is set to 0:

```
$ redis-cli config get timeout
1) "timeout"
2) "0"
```

If not then modify the timeout setting in your `redis.conf`

**Comment by Cediddi** [comment]
Okay, thank you very much :)

**Comment by HatBoy** [comment]
I have the same error, and my redis configuration timeout is 0,but I also can not solve the problem.
[2016-12-09 15:15:05,083: ERROR/MainProcess] Control command error: EncodeError(TypeError('b\'[[], {}, {"chord": null, "chain": null, "callbacks": null, "errbacks": null}]\' is not JSON serializable',),)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'[[], {}, {"chord": null, "chain": null, "callbacks": null, "errbacks": null}]' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/pidbox.py", line 42, in on_message
    self.node.handle_message(body, message)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/usr/local/lib/python3.5/dist-packages/kombu/messaging.py", line 167, in publish
    compression, headers)
  File "/usr/local/lib/python3.5/dist-packages/kombu/messaging.py", line 249, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/vine/five.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: b'[[], {}, {"chord": null, "chain": null, "callbacks": null, "errbacks": null}]' is not JSON serializable
[2016-12-09 15:15:05,097: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'can_read'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 1038, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 670, in _receive
    while c.connection.can_read(timeout=0):
AttributeError: 'NoneType' object has no attribute 'can_read'

**Comment by hedleyroos** [comment]
The change applied in https://github.com/celery/kombu/commit/66325920c72d395a7f1bafdf97d5462b7ce5b3f8 does not really fix the issue. The problem is the `connection` property is reset to `None` the moment a socket is terminated, and the few microseconds between the check `if c.connection is not None` and the next line `while c.connection.can_read(timeout=0)` is enough time for this to happen. You will only encounter this on a slow network or a network with packet loss. The two lines need to be threadsafe, and the only quick solution I see is to rewrite it as:

            if c.connection is not None:
            try:
                while c.connection.can_read(timeout=0):
                    ret.append(self._receive_one(c))
            except AttributeError:
                pass

This is ugly because AttributeError is such a broad exception. It would be nice to have eg. ConnectionLostError raised in the underlying code.

**Comment by alexandernst** [comment]
@auvipy @ask @thedrow ⬆️ can you check this, please. I'm constantly hitting this issue.

**Comment by thedrow** [comment]
Please don't comment on a new issue.
Instead, open a new one with all the details required for us to reproduce and fix the problem.

**Comment by alexandernst** [comment]
@thedrow Why do you want me to open a new (empty) issue when you have all the details AND the solution (or at least a workaround) to the problem here? Can't you just re-open this one?
