### ISSUE TITLE
Kombu may crash while running BRPOP on a connection that Redis decided to close

### ISSUE THREAD

**Issue by lddubeau** [celery/kombu#681]
### Versions

Kombu: 4.0.2
Celery: 4.0.2
redis-py: 2.10.5
Redis: 3.2.6
Python: 2.7.12

### Steps to reproduce

Start a `redis` server with `timeout 1`, I use the following config:

```
daemonize yes
pidfile ./redis.pid
port 0
unixsocket /tmp/celery.redis.test.sock
unixsocketperm 755
timeout 1
loglevel notice
logfile ./redis.log
databases 1
```

(I shove the unix socket into `/tmp/` because there's a limit to how long a unix socket path can be.)

I put the Celery configuration in `celeryconfig.py`:

```
CELERY_BROKER_URL = 'redis+socket:///tmp/celery.redis.test.sock'
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
```

The Celery app is in `tasks.py`:

```
import sys
import time

from celery import Celery, Task

app = Celery('tasks')
app.config_from_object('celeryconfig', namespace='CELERY')

@app.task
def add(x, y):
    return x + y
```

I have `test.py`:

```
from celery.bin.multi import MultiTool

from tasks import app, add

workers = [
    "A",
    "B"
]

while True:
    for worker in workers:
        retcode = MultiTool().execute_from_commandline(["multi", "start", "-A",
                                                        "tasks", worker])
        print "STARTED {0} WITH {1}".format(worker, retcode)

    print "PING AFTER START", app.control.inspect().ping()
    print add.delay(1, 2).get()
    print "PING AFTER TASK", app.control.inspect().ping()
    for worker in workers:

        retcode = MultiTool().execute_from_commandline(["multi", "stopwait", "-A",
                                                        "tasks", worker])
        print "STOPPED {0} WITH {1}".format(worker, retcode)
    print "PING AFTER STOP", app.control.inspect().ping()
```

Run `python test.py`.

### Expected Results

Should run forever without a crash.

### Actual Results

Crashes at the end of the first iteration:

```
PING AFTER STOP
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    print "PING AFTER STOP", app.control.inspect().ping()
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/celery/app/control.py", line 113, in ping
    return self._request('ping')
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/celery/app/control.py", line 81, in _request
    timeout=self.timeout, reply=True,
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 321, in _broadcast
    channel=chan)
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 360, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 961, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 352, in get
    self._register_BRPOP(channel)
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 301, in _register_BRPOP
    channel._brpop_start()
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 707, in _brpop_start
    self.client.connection.send_command('BRPOP', *keys)
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/ldd/src/celery_issues/celery_issue_2/.venv/local/lib/python2.7/site-packages/redis/connection.py", line 556, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.
```

### Observations

The code above in `test.py` imitates a sequence of operations that happen while testing an actual Django application of mine. The test suite starts and stops workers and executes some tasks on them.

Though the problem surfaced after I upgraded to Celery 4.x and thus started uising Kombu 4.x, a summary inspection of Kombu's source code in the 3.x series suggests the problem is present there too. It is unclear to me why I did not run into it in when running Kombu 3.x.

In my actual Redis setup I do not use a `timeout 1` setting. Using `timeout 1` is an easy way to cause Redis to close a connection. Other situations may be because the `tcp-keepalive` timeout deemed a connection "dead". Or because a client violated an output buffer limit, or for some other reason. What is clear is that Redis clients should be resilient in the face of connections that got closed by the server.

Indeed, the code of `redis-py` will generally retry sending commands that fail. This can be seen in [`execute_command`](https://github.com/andymccurdy/redis-py/blob/2.10.5/redis/client.py#L566):

```
    def execute_command(self, *args, **options):
        "Execute a command and return a parsed response"
        pool = self.connection_pool
        command_name = args[0]
        connection = pool.get_connection(command_name, **options)
        try:
            connection.send_command(*args)
            return self.parse_response(connection, command_name, **options)
        except (ConnectionError, TimeoutError) as e:
            connection.disconnect()
            if not connection.retry_on_timeout and isinstance(e, TimeoutError):
                raise
            connection.send_command(*args)
            return self.parse_response(connection, command_name, **options)
        finally:
            pool.release(connection)
```

Kombu's Redis `Channel` will generally benefit from `redis-py`'s automatic retrying because most of the time the methods it calls on its client ultimately run `execute_command`. However, [`_brpop_start`](https://github.com/celery/kombu/blob/v4.0.2/kombu/transport/redis.py#L700) calls `self.client.connection.send_command('BRPOP', *keys)`. If this call fails, the failure is automatically sent  up the stack without a retry.

I've been able to work around the issue by changing the code of `_brpop_start` to:

```
    def _brpop_start(self, timeout=1):
        queues = self._queue_cycle.consume(len(self.active_queues))
        if not queues:
            return
        keys = [self._q_for_pri(queue, pri) for pri in self.priority_steps
                for queue in queues] + [timeout or 0]
        self._in_poll = self.client.connection
        from redis.exceptions import ConnectionError
        try:
            self.client.connection.send_command('BRPOP', *keys)
        except ConnectionError:
            self.client.connection.send_command('BRPOP', *keys)
```

**Comment by ferenc-radius** [comment]
I got a lot of those errors 
 - redis 3.2.7
    timeout 0
    
  - celery 4.0.2

[2017-02-10 21:26:33,544: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/site-packages/kombu/async/hub.py", line 277, in create_loop
    tick_callback()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 1032, in on_poll_start
    cycle_poll_start()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 315, in on_poll_start
    self._register_BRPOP(channel)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 301, in _register_BRPOP
    channel._brpop_start()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 707, in _brpop_start
    self.client.connection.send_command('BRPOP', *keys)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 556, in send_packed_command
    (errno, errmsg))
ConnectionError: Error 32 while writing to socket. Broken pipe

**Comment by auvipy** [comment]
could you verify on current master

**Comment by benjolitz** [comment]
I suffer from the same stack trace, celery 4.0.3.

I found that if I removed autoscale from my celery multi command, the issue went away.

**Comment by benjolitz** [comment]
I upgraded to 4.1.0. Upon adding `--autoscale=12,4 ` to my celeryd options, the issue is provoked when I slam the task queue with a lot of tasks.

This would indicate that the post fork() call is *not* happening for `redis.Channel` instances.

**Comment by benjolitz** [comment]
I can confirm that `register_after_fork` is defined by the time  `kombu/transport/redis.py:512` runs, so the next question is "On Autoscale from celery multi, does the post fork run?"

**Comment by benjolitz** [comment]
Alright, I've got a running log of every PID allocated. Every time _after_fork is called, I log which pid it is called on. I also track the original pid of the process when a redis.Channel is instantiated.

```
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,089] [celery.worker.autoscale] [INFO] Scaling up 1 processes.
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,096] [minions.compat] [INFO] Calling after fork on pid 8544, ancestor was 8513
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,097] [minions.compat] [INFO] Calling after fork on pid 8544, ancestor was 8513
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,108] [minions.compat] [INFO] Calling after fork on pid 8544, ancestor was 8513
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,109] [minions.compat] [INFO] Calling after fork on pid 8544, ancestor was 8513
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,109] [minions.compat] [INFO] Calling after fork on pid 8544, ancestor was 8513
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,396] [minions.compat] [ERROR] Unexpected conn error on pid 8513, ancestor pid 8513
Traceback (most recent call last):
  File "/home/docker/minions.c4530621624c82818edd96263b2ccfebe3c4ad2e/minions/compat.py", line 115, in _brpop_start
    return super(NamedChannel, self)._brpop_start(timeout)
  File "/home/docker/.local/lib/python2.7/site-packages/kombu/transport/redis.py", line 707, in _brpop_start
    self.client.connection.send_command('BRPOP', *keys)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 556, in send_packed_command
    (errno, errmsg))
ConnectionError: Error 32 while writing to socket. Broken pipe.
Mar 13 00:38:51 ip-172-17-33-51 [2018-03-13 00:38:51,407] [celery.worker.consumer.consumer] [WARNING] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/docker/.local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/home/docker/.local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/docker/.local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/home/docker/.local/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/docker/.local/lib/python2.7/site-packages/kombu/async/hub.py", line 276, in create_loop
    tick_callback()
  File "/home/docker/.local/lib/python2.7/site-packages/kombu/transport/redis.py", line 1033, in on_poll_start
    cycle_poll_start()
  File "/home/docker/.local/lib/python2.7/site-packages/kombu/transport/redis.py", line 315, in on_poll_start
    self._register_BRPOP(channel)
  File "/home/docker/.local/lib/python2.7/site-packages/kombu/transport/redis.py", line 301, in _register_BRPOP
    channel._brpop_start()
  File "/home/docker/minions.c4530621624c82818edd96263b2ccfebe3c4ad2e/minions/compat.py", line 115, in _brpop_start
    return super(NamedChannel, self)._brpop_start(timeout)
  File "/home/docker/.local/lib/python2.7/site-packages/kombu/transport/redis.py", line 707, in _brpop_start
    self.client.connection.send_command('BRPOP', *keys)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 556, in send_packed_command
    (errno, errmsg))
ConnectionError: Error 32 while writing to socket. Broken pipe.
```

It looks like the parent process that we fork from can have it's connection poisoned/closed.

**Comment by benjolitz** [comment]
So from what I can tell, the issue is that calling `disconnect()` on a Redis Connection will poison the connection for **all** processes that use that connection because it calls `socket.shutdown` at https://github.com/andymccurdy/redis-py/blob/293b5e65e3f970c2e7c904ff3597ba51fde8eb36/redis/connection.py#L577

According to https://stackoverflow.com/a/598759/367120 the act of calling `socket.shutdown` for both directions (RDWR) will cause the remote server to disconnect.

Unfortunately, the architecture of https://github.com/celery/kombu/blob/488ed977e0345eb0f509f020a80bb88f42bb1315/kombu/transport/redis.py#L290 means that there can be a broken connection attached to the `self.client` object just waiting to explode.

**Comment by georgepsarakis** [comment]
@benjolitz could you try https://github.com/celery/celery/issues/4363#issuecomment-343647640 ?

**Comment by benjolitz** [comment]
Yeah, I tried that. It didn't do anything. I added into the `__init__` a logger call to see if the class was being initialized (it was). `on_after_fork` was never called however.

Either way, the exception is being thrown in the `redis.Channel` class.

**Comment by georgepsarakis** [comment]
@benjolitz What type of worker pool are you using? prefork, gevent?

**Comment by benjolitz** [comment]
Prefork.

**Comment by lddubeau** [comment]
I revisited this issue recently and spent quite a bit of time re-examining the problem. The `BRPOP` failure I experienced is really one manifestation of a larger problem:

1. Redis may close connections unilaterally.

2. `redis-py` *sometimes* reopens the connection automatically.

3. On those occasions when `redis-py` *does not reopen the connection* a subsequent attempt at using the connection causes `EPIPE` which causes an exception to be reported up the call stack.

My initial issue was with `BRPOP` but the problem can happen whenever Celery (through Kombu) tries to contact Redis. My recent brush with this problem actually happened while Celery (in Celery code proper, not through Kombu) was trying to subscribe to a pubsub channel on Redis: the connection had been closed and the subscription failed. Retrying the subscription after the failure worked just fine.

When I filed my initial report, `redis-py` was coded in a way that made `execute_command` almost always retry failed attempts at sending a command to Redis. It turns out that [the retry logic in `redis-py` was wrong](https://github.com/andymccurdy/redis-py/issues/1022) and has only been [fixed earlier this year](https://github.com/andymccurdy/redis-py/issues/1022#issuecomment-464516738). When I did my tests with the code of `redis-py` as it existed when I filed this issue, I could see retries happening regularly. Prior to the fix, if you used `redis-py` in its default configuration and the retry code faced a closed connection, it would always automatically reopen it. Once the retry logic in `redis-py` has been fixed, if you use `redis-py` in its default configuration and the retry code faces a closed connection, the connection is not automatically reopened . The retry logic is now such that it retries only if the socket timed out (in the [`socket.timeout`](https://docs.python.org/2/library/socket.html#socket.timeout) sense of "timed out") and the flag `retry_on_timeout` is true.

Although the new retry logic (by default) won't cause `redis-py` to automatically reconnect when Redis unilaterally closes a connection, there are other parts of `redis-py` that automatically resurrect closed connections. The `get_connection` method provided with the default `ConnectionPool`, contains [logic that reconnects](https://github.com/andymccurdy/redis-py/blob/c26e7c545f0b6205465394908ae18a248b79cc86/redis/connection.py#L996-L1011) disconnected connections that are still in the pool. These automatic reconnections make it difficult to diagnose problems that Redis disconnections cause with Kombu or Celery. Whether the disconnection is hidden by `redis-py` or not depends on timing, and explains why code that worked fine for the longest time suddenly throws exceptions on `EPIPE`.

**Comment by mlissner** [comment]
Thanks for the explainer, @ lddubeau. Did you ever figure out a solution? I've got a script that calls:

    task.get()

And it almost always fails. I'm pretty stumped on how to make that do an automatic retry (assuming that's the right thing to make it do).
