### ISSUE TITLE
Celery worker with multiple host broker url for ZooKeeper

### ISSUE THREAD

**Issue by koorgoo** [celery/kombu#734]
While Django server runs well, Celery worker fails to start.

```
CELERY_BROKER_URL = 'zookeeper://localhost:2181,localhost:2182/chroot'
```

```
Traceback (most recent call last):
  File "/vagrant/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/vagrant/venv/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/vagrant/venv/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/vagrant/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/vagrant/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 120, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/vagrant/venv/lib/python3.6/site-packages/celery/app/base.py", line 752, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/vagrant/venv/lib/python3.6/site-packages/celery/app/base.py", line 828, in _connection
    'broker_connection_timeout', connect_timeout
  File "/vagrant/venv/lib/python3.6/site-packages/kombu/connection.py", line 181, in __init__
    url_params = parse_url(hostname)
  File "/vagrant/venv/lib/python3.6/site-packages/kombu/utils/url.py", line 34, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/vagrant/venv/lib/python3.6/site-packages/kombu/utils/url.py", line 52, in url_to_parts
    parts.port,
  File "/usr/lib/python3.6/urllib/parse.py", line 159, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '2181,localhost:2182'
```

It is curious when the first host in the broker url does not contain port a worker starts!

```
CELERY_BROKER_URL = 'zookeeper://localhost,localhost:2182/chroot'
```

```
[2017-05-04 08:34:17,905: INFO/MainProcess] Connected to zookeeper://localhost%2Clocalhost:2182/extmon
[2017-05-04 08:34:17,917: INFO/MainProcess] Connecting to localhost:2181
```

**Comment by koorgoo** [comment]
I know Celery supports such kind of URL `amqp://foo;amqp://bar`.
`kazoo` package used as a driver for ZooKeeper accepts comma separated hosts:
```python
KazooClient(hosts='localhost:2181,localhost:2182')
```

I suggest a few options how to solve this issue. Please, help me to choose one to implement:

**Option 1**: Kombu supports special format of URL for ZooKeeper close to `kazoo` API.
```
zookeeper://<host>[:<port>][,<host>[:<port>]][/<chroot>]
```

**Option 2**: Kombu demands same `chroot`s in every _sub_-URL:
```
zookeeper://<host>[:<port>][/<chroot>][;zookeeper://<host>[:<port>][/<chroot>]]
```

Seems to be a too clever option. I doubt that anybody will use ZooKeeper with other brokers the same time...

**Comment by georgepsarakis** [comment]
This seems already implemented in the Zookeeper transport, see [here](https://github.com/celery/kombu/blob/master/kombu/transport/zookeeper.py#L168). Or is this a problem with `vhost` specifically?

**Comment by koorgoo** [comment]
As of now broker URL like `zookeeper://localhost:2181/chroot;zookeeper://localhost:2182/chroot` leads to error in [the line](https://github.com/celery/kombu/blob/2216856/kombu/transport/zookeeper.py#L168) you reference:

```python
...
# conn_str == 'localhost:2181,localhost:2181/chroot:2181,localhost:2181/chroot:2181'
conn = KazooClient(conn_str)
```

That's why the issue was opened. I want to agree on the one format and write some code to support it.

**Comment by koorgoo** [comment]
@georgepsarakis this is not the problem with `vhost` but with the some kind of mess after `if conninfo.alt:` in `_open` method.

**Comment by georgepsarakis** [comment]
I cannot see how this is caused by `_open`, so I am afraid that it may be caused in the `Connection` constructor. I would suggest *Option 2*, as it is closer to the current implementation. What do you think?

**Comment by koorgoo** [comment]
Option 2 would really be _consistent_ in terms of the Celery project.
Try to fix it. Will discuss technical details in comments on soon PR ;)

**Comment by auvipy** [comment]
was the issue fixed?
