### ISSUE TITLE
WinError 10042 when opening AMQP Channel

### ISSUE THREAD

**Issue by lutzhorn** [celery/kombu#736]
* Windows 7
* Python 3.5.3
* kombu 4.0.2

Using this code

````
from kombu import Connection

con = Connection("amqp://user:password@host/")
chan = con.channel()
````

gives this error:

````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Program Files\Python\Python35\lib\site-packages\kombu\connection.py", line 266, in channel
    chan = self.transport.create_channel(self.connection)
  File "c:\Program Files\Python\Python35\lib\site-packages\kombu\connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "c:\Program Files\Python\Python35\lib\site-packages\kombu\connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "c:\Program Files\Python\Python35\lib\site-packages\kombu\transport\pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "c:\Program Files\Python\Python35\lib\site-packages\amqp\connection.py", line 294, in connect
    self.transport.connect()
  File "c:\Program Files\Python\Python35\lib\site-packages\amqp\transport.py", line 122, in connect
    self.socket_settings, self.read_timeout, self.write_timeout,
  File "c:\Program Files\Python\Python35\lib\site-packages\amqp\transport.py", line 174, in _init_socket
    self._set_socket_options(socket_settings)
  File "c:\Program Files\Python\Python35\lib\site-packages\amqp\transport.py", line 204, in _set_socket_options
    self.sock.setsockopt(SOL_TCP, opt, val)
OSError: [WinError 10042] An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call
````

**Comment by srault95** [comment]
Same error on:
- Windows 10
- Python 3.5.3 64bits
- kombu 4.0.2
- amqp 2.1.4
- rabbitmq 3.6.2 (linux)

**Comment by lutzhorn** [comment]
The error does not occur using version 2.1.3 of amqp.

**Comment by eavictor** [comment]
This error is due to a missing feature in Windows.
See here: https://github.com/celery/py-amqp/pull/136

What we have to now is sit tight and wait for new AMQP release on pypi.

**Comment by auvipy** [comment]
in the mean time try install from master

**Comment by lutzhorn** [comment]
@auvipy Was has happened in the mean time so this issue can be fixed? Which released version does fix this issue?

**Comment by auvipy** [comment]
try 4.1+ release with all updated dependencies
