### ISSUE TITLE
'LifoQueue' object has no attribute 'mutex' when running gunicorn with eventlet and broker_pool_limit = 0

### ISSUE THREAD

**Issue by fgaudin** [celery/kombu#741]
I have this bug the first time I try to post a task with Celery from an API call:

```
Traceback (most recent call last):
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/fga/workspace/kombu_eventlet_bug/wsgi.py", line 18, in app
    add.delay(1,2)
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/celery/app/task.py", line 412, in delay
    return self.apply_async(args, kwargs)
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/celery/app/base.py", line 734, in send_task
    with self.producer_or_acquire(producer) as P:
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/celery/app/base.py", line 863, in producer_or_acquire
    producer, self.producer_pool.acquire, block=True,
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/celery/app/base.py", line 1232, in producer_pool
    return self.amqp.producer_pool
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/celery/app/amqp.py", line 610, in producer_pool
    self._producer_pool.limit = self.app.pool.limit
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/celery/app/base.py", line 1147, in pool
    pools.set_limit(limit)
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/kombu/pools.py", line 137, in set_limit
    pool.resize(limit)
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/kombu/resource.py", line 188, in resize
    self._shrink_down()
  File "/home/fga/workspace/kombu_eventlet_bug/.virtualenv/lib/python3.4/site-packages/kombu/resource.py", line 193, in _shrink_down
    with resource.mutex:
AttributeError: 'LifoQueue' object has no attribute 'mutex'
```

It seems to be because when gunicorn uses eventlet, the base class that is picked up is 'eventlet.green.Queue.LifoQueue' instead of the standard python one.
It only happens if I set broker_pool_limit = 0.

I've set up a project to isolate and reproduce the bug: https://github.com/fgaudin/kombu_eventlet_bug

**Comment by fgaudin** [comment]
Looks like an eventlet bug more than Kombu actually

**Comment by fgaudin** [comment]
And looks like that ugly workaround will do for now, I'm forcing the pool queue shrinking to zero when starting:
```
app = Celery('tasks', broker='amqp://guest:guest@localhost:5672/')

app.conf.update(
    broker_pool_limit=0,
)

try:
    app.producer_or_acquire()
except AttributeError as e:
    if str(e) != "'LifoQueue' object has no attribute 'mutex'":
        raise
```

**Comment by auvipy** [comment]
so we could keep this open until eventlet bug is fixed

**Comment by fgaudin** [comment]
In case I get no feedback on the eventlet side, would it be worth considering having a specific treatment for eventlet in kombu. It seems that they're doing the same thing with resize() https://github.com/eventlet/eventlet/blob/master/eventlet/queue.py#L198

**Comment by auvipy** [comment]
you can send a pr for review

**Comment by michaelwclark** [comment]
Any update on this? I'm running into the same issue.

**Comment by auvipy** [comment]
could you please manually verify this patch https://github.com/celery/kombu/pull/916 ?

**Comment by auvipy** [comment]
can you please check if this PR is relevant for your case https://github.com/celery/kombu/pull/2314 ?

**Comment by rubnov** [comment]
@auvipy indeed this is exactly the issue I was facing. This PR would most likely resolve the issue.
