### ISSUE TITLE
Bad File Descriptor

### ISSUE THREAD

**Issue by bpereto** [celery/kombu#800]
Hi,

We use Celery with RabbitMQ as Broker and have these looping "Bad Filedescriptor" errors in production:
```
[2017-09-12 18:05:59,782: INFO/MainProcess] missed heartbeat from ansible2@server2.prod.local
[2017-09-12 18:05:59,782: INFO/MainProcess] missed heartbeat from inventory3@server1.prod.local
[2017-09-12 18:05:59,782: INFO/MainProcess] missed heartbeat from ansible1@server2.prod.local
[2017-09-12 18:05:59,782: INFO/MainProcess] missed heartbeat from nagios@server2.prod.local
[2017-09-12 18:05:59,782: INFO/MainProcess] missed heartbeat from myapp2@server1.prod.local
[2017-09-12 18:05:59,782: INFO/MainProcess] missed heartbeat from myapp1@server1.prod.local
[2017-09-12 18:05:59,782: INFO/MainProcess] missed heartbeat from inventory2@server1.prod.local
[2017-09-12 18:05:59,783: INFO/MainProcess] missed heartbeat from packageflow4@server3.prod.local
[2017-09-12 18:05:59,783: INFO/MainProcess] missed heartbeat from packageflow1@server3.prod.local
[2017-09-12 18:05:59,783: INFO/MainProcess] missed heartbeat from packageflow2@server3.prod.local
[2017-09-12 18:05:59,783: INFO/MainProcess] missed heartbeat from packageflow3@server3.prod.local
[2017-09-12 18:05:59,783: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 280, in start
    blueprint.start(self)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 884, in start
    c.loop(*c.loop_args())
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/kombu/transport/base.py", line 144, in _read
    raise RecoverableConnectionError('Socket was disconnected')
RecoverableConnectionError: Socket was disconnected

[2017-09-12 18:06:13,225: INFO/MainProcess] Connected to amqp://myapp:**@myapp-broker.prod.local:5671/myapp
[2017-09-12 18:06:13,259: INFO/MainProcess] mingle: searching for neighbors
[2017-09-12 18:06:14,297: INFO/MainProcess] mingle: sync with 8 nodes
[2017-09-12 18:06:14,297: INFO/MainProcess] mingle: sync complete
[2017-09-12 18:06:14,343: WARNING/MainProcess] /usr/app/myapp/.venv/lib/python2.7/site-packages/kombu/pidbox.py:75: UserWarning: A node named inventory1@server1.prod.local is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))
[2017-09-12 18:06:14,350: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 280, in start
    blueprint.start(self)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 884, in start
    c.loop(*c.loop_args())
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/loops.py", line 41, in asynloop
    obj.controller.register_with_event_loop(hub)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/__init__.py", line 218, in register_with_event_loop
    description='hub.register',
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/bootsteps.py", line 155, in send_all
    fun(parent, *args)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/components.py", line 185, in register_with_event_loop
    w.pool.register_with_event_loop(hub)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 141, in register_with_event_loop
    return reg(loop)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 452, in register_with_event_loop
    for fd in self._fileno_to_outq]
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/kombu/async/hub.py", line 210, in add_reader
    return self.add(fds, callback, READ | ERR, args)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/kombu/async/hub.py", line 162, in add
    self.poller.register(fd, flags)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/kombu/utils/eventio.py", line 77, in register
    self._epoll.register(fd, events)
IOError: [Errno 9] Bad file descriptor
[2017-09-12 18:06:14,388: INFO/MainProcess] Connected to amqp://myapp:**@myapp-broker.prod.local:5671/myapp
[2017-09-12 18:06:14,419: INFO/MainProcess] mingle: searching for neighbors
[2017-09-12 18:06:15,464: INFO/MainProcess] mingle: sync with 8 nodes
[2017-09-12 18:06:15,464: INFO/MainProcess] mingle: sync complete
[2017-09-12 18:06:15,509: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 280, in start
    blueprint.start(self)
  File "/usr/app/myapp/.venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
...
```

billiard==3.3.0.23
celery==3.1.25
celery-redis-sentinel==0.3.0
kombu==3.0.37

Should be recoverable?
I use -Ofair.

**Comment by auvipy** [comment]
If you could try the newer version and see if it works
