### ISSUE TITLE
AttributeError after broker shutdown

### ISSUE THREAD

**Issue by sseg** [celery/kombu#809]
During an unexpected broker shutdown my consumer threw an AttributeError:
```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/kombu/utils/compat.py", line 120, in nested
     yield vars
   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 229, in Consumer
     yield conn, channel, c
   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 182, in consumer_context
     yield connection, channel, consumers
   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 192, in consume
     conn.drain_events(timeout=safety_interval)
   File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 301, in drain_events
     return self.transport.drain_events(self.connection, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
     return connection.drain_events(**kwargs)
   File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 464, in drain_events
     return self.blocking_read(timeout)
   File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 469, in blocking_read
     return self.on_inbound_frame(frame)
   File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 68, in on_frame
     callback(channel, method_sig, buf, None)
   File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 473, in on_inbound_method
     method_sig, payload, content,
   File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 142, in dispatch_method
     listener(*args)
   File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 595, in _on_close
     (class_id, method_id), ConnectionError)
 amqp.exceptions.ConnectionForced: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/listener/consumer.py", line 177, in consume
     consumer.run()
   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 170, in run
     for _ in self.consume(limit=None, **kwargs):
   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 203, in consume
     elapsed = 0
   File "/usr/local/lib/python3.6/contextlib.py", line 100, in __exit__
     self.gen.throw(type, value, traceback)
   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 182, in consumer_context
     yield connection, channel, consumers
   File "/usr/local/lib/python3.6/contextlib.py", line 100, in __exit__
     self.gen.throw(type, value, traceback)
   File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 229, in Consumer
     yield conn, channel, c
   File "/usr/local/lib/python3.6/contextlib.py", line 100, in __exit__
     self.gen.throw(type, value, traceback)
   File "/usr/local/lib/python3.6/site-packages/kombu/utils/compat.py", line 135, in nested
     reraise(exc[0], exc[1], exc[2])
   File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 176, in reraise
     raise value
   File "/usr/local/lib/python3.6/site-packages/kombu/utils/compat.py", line 127, in nested
     if exit(*exc):
   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 438, in __exit__
     conn_errors = self.channel.connection.client.connection_errors
 AttributeError: 'NoneType' object has no attribute 'client'
```

This occurred with Kombu version `4.0.2`

Is the expected behaviour that the consumer would try to reconnect?

**Comment by auvipy** [comment]
try the new release of kombu and see

**Comment by pokiz** [comment]
Still happening in Kombu 5.0.3 and Python 3.9.2.
![image](https://github.com/celery/kombu/assets/6131769/50436a0b-bd1b-4ffb-872f-10f985f1369d)
