### ISSUE TITLE
kombu.Connection fails with password with character "?"

### ISSUE THREAD

**Issue by RevengeComing** [celery/kombu#898]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cafebazar/Works/divar/Classified/env/local/lib/python2.7/site-packages/kombu/connection.py", line 181, in __init__
    url_params = parse_url(hostname)
  File "/home/cafebazar/Works/divar/Classified/env/local/lib/python2.7/site-packages/kombu/utils/url.py", line 34, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/home/cafebazar/Works/divar/Classified/env/local/lib/python2.7/site-packages/kombu/utils/url.py", line 52, in url_to_parts
    parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'asd'
```

I get this error if i use below code on both python 3 and 2:

```python
import kombu

password = "asd?qwe"
username = "guest"
host = "somewhere"
port = 32111

url = 'amqp://{username}:{password}@{host}:{port}//'.format(
    username=username,
    password=password,
    host=host,
    port=port
)

url = kombu.Connection(url)
```

It will be fixed if i url encode password. But it will be ideal if kombu handles this ?

**Comment by georgepsarakis** [comment]
This seems outside the responsibility of `Connection`. 

However, a helper function achieving what you are referring to, already exists in `kombu.utils.url`:

```python
from kombu.utils.url import as_url

password = "asd?qwe"
username = "guest"
host = "somewhere"
port = 32111
url = as_url(scheme='amqp', host=host, port=port, user=username, password=password)
print url # u'amqp://guest:asd%3Fqwe@somewhere:32111/'
```

Unless there is any other question, I think we can close this issue.

**Comment by carolinux** [comment]
Had the same issue when reading the connection string from an env var. If the password had a '?' in it, then the first four characters of the password were treated as the port. 
I am not sure if urlencoding the string in the environment would have worked for all the readers of this string. I just changed the password. :laughing:

**Comment by RevengeComing** [comment]
@carolinux `as_url` will do the work ... we used it like :

```
url = as_url(scheme='amqp', host=host, port=port, user=username, password=password)
connection = kombu.Connection(url)
```
and its fine.

**Comment by carolinux** [comment]
In my case, kombu is called by the airflow library, so I have no control over how it's done.
