### ISSUE TITLE
messages failing to ack

### ISSUE THREAD

**Issue by stuartspotlight** [celery/kombu#901]
I wrote about this on the issue here:- 
https://github.com/celery/kombu/issues/857
but I think this deserves a separate thread since it is probably a separate issue. When I attempt to ack a message on the queue it came from after processing and publishing to a different queue the acking fails with the error:-
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nanowire_plugin/__init__.py", line 511, in send_to_next_plugin
    message.ack()
  File "/usr/local/lib/python3.6/site-packages/kombu/message.py", line 125, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 1392, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 47, in send_method
    raise RecoverableConnectionError('connection already closed')
amqp.exceptions.RecoverableConnectionError: connection already closed

```
I attempted to retry the ack multiple times to no avail especially since the connection is listed as intact as shown by the information I print out:-
```
HAD TROUBLE ACKING TRYING ANOTHER 30 times
CONNECTION IS UP:- True
OUT CHANNEL IS UP:- True
CONNECTION INFO IS:- OrderedDict([('hostname', 'rabbitmq-dev.nanowire.io'), ('userid', 'rabbitmq'), ('password', 'un77zEPB6y7RHWf5'), ('virtual_host', '/'), ('port', 5672), ('insist', False), ('ssl', True), ('transport', 'amqp'), ('connect_timeout', 5), ('transport_options', {'confirm_publish': True}), ('login_method', 'AMQPLAIN'), ('uri_prefix', None), ('heartbeat', 25.0), ('failover_strategy', 'round-robin'), ('alternates', [])])
```
Does anyone have any insight into why this may be happening and any steps I might use to fix this problem?

**Comment by stuartspotlight** [comment]
I'm not sure if its pertenant but the connection on the message returned by 
```
message.channel.connection
```
is none and when I try to force this connection by setting 
```
message,channel.connection
```
the new error I get is:-

```
Traceback (most recent call last):
  File "/nanowire_plugin/__init__.py", line 511, in send_to_next_plugin
    message.ack()
  File "/usr/local/lib/python3.6/site-packages/kombu/message.py", line 125, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 1392, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
AttributeError: 'Connection' object has no attribute 'frame_writer'
```

**Comment by stuartspotlight** [comment]
What seems to be happening is that whilst the regex query is running on the consumed message the message's connection (found at ```message.channel.connection ```) is converting from a ```kombu.transport.pyamqp.Connection object```  to "None". Is there any way to re-establish the connection once this happens? Why is this happening? Is this due to regex interfering with the connection thread. I thought regex was meant to be thread safe

**Comment by sitegui** [comment]
I'm facing the same issue with kombu==4.5.0 and librabbitmq==2.0.0 when calling `message.ack()`

Is any fix/workaround known to this point?

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/src/app/scarab/handler/prediction_handler.py", line 65, in run
    message.ack()
  File "/usr/local/lib/python3.6/site-packages/kombu/message.py", line 125, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/usr/local/lib/python3.6/site-packages/librabbitmq/__init__.py", line 95, in basic_ack
    self.channel_id, delivery_tag, multiple,
_librabbitmq.ConnectionError: Operation on closed connection
```

**Comment by jugdizh** [comment]
For me the problem happens when rabbitmq-server dies for whatever reason. My consumer gets stuck in a loop of the following traceback, even ***after*** I have restarted the rabbitmq-server process.
```
Traceback (most recent call last):
  File "/opt/venv/local/lib/python2.7/site-packages/kombu/mixins.py", line 175, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/opt/venv/local/lib/python2.7/site-packages/kombu/mixins.py", line 197, in consume
    conn.drain_events(timeout=safety_interval)
  File "/opt/venv/local/lib/python2.7/site-packages/kombu/connection.py", line 315, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/opt/venv/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/connection.py", line 506, in blocking_read
    return self.on_inbound_frame(frame)
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/method_framing.py", line 79, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/connection.py", line 510, in on_inbound_method
    method_sig, payload, content,
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 126, in dispatch_method
    listener(*args)
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/channel.py", line 1620, in _on_basic_deliver
    fun(msg)
  File "/opt/venv/local/lib/python2.7/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/opt/venv/local/lib/python2.7/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/share/dev/src/myapp/worker/mixins/mq.py", line 123, in handle_message
    msg.ack()
  File "/opt/venv/local/lib/python2.7/site-packages/kombu/message.py", line 125, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/channel.py", line 1399, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/opt/venv/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 48, in send_method
    raise RecoverableConnectionError('connection already closed')
RecoverableConnectionError: connection already closed
```
