### ISSUE TITLE
Setting should_stop to True causes AttributeError exception

### ISSUE THREAD

**Issue by slowr** [celery/kombu#922]
I have a ConsumerProducerMixin class that is closed at some point through a SIGINT by setting the `should_stop` variable to `True`. This causes this exception:

```
Traceback (most recent call last):
  File "/root/core/detection.py", line 35, in run_worker
    self.worker.run()
  File "/usr/local/lib/python3.7/site-packages/kombu/mixins.py", line 170, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/kombu/mixins.py", line 203, in consume
    elapsed = 0
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/kombu/mixins.py", line 182, in consumer_context
    yield connection, channel, consumers
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/kombu/mixins.py", line 231, in Consumer
    self.on_consume_end(conn, channel)
  File "/usr/local/lib/python3.7/site-packages/kombu/mixins.py", line 284, in on_consume_end
    self._producer_connection.close()
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 358, in release
    self._close()
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 324, in _close
    self._do_close_self()
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 314, in _do_close_self
    self.maybe_close_channel(self._default_channel)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 306, in maybe_close_channel
    channel.close()
  File "/usr/local/lib/python3.7/site-packages/amqp/channel.py", line 223, in close
    wait=spec.Channel.CloseOk,
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.7/site-packages/amqp/channel.py", line 275, in _on_close
    self._do_revive()
  File "/usr/local/lib/python3.7/site-packages/amqp/channel.py", line 162, in _do_revive
    self.open()
  File "/usr/local/lib/python3.7/site-packages/amqp/channel.py", line 432, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'drain_events'
```

To reproduce run below code and hit Ctrl+C
```
class Detection(Object):

    def exit(self, signum, frame):
        if self.worker is not None:
            self.worker.should_stop = True

    def start(self):
        try:
            signal.signal(signal.SIGINT, self.exit)
            with Connection(RABBITMQ_HOST) as connection:
                self.worker = self.Worker(connection)
                self.worker.run()
        except:
            log.exception('exception')
        finally:
            log.info('stopped')

    class Worker(ConsumerProducerMixin):

        def __init__(self, connection):
            self.connection = connection
            log.info('started')

        def get_consumers(self, Consumer, channel):
            return [ ... ]

if __name__ == '__main__':
    c = Detection()
    c.start()
```

Does setting `should_stop` variable to `True` set the connection to `None` before the actual loop ends?

**Comment by matteius** [comment]
The issue is that the connections have been closed at some point so it is a None value -- doesn't have attribute drain_events.  Can you check on the latest pypi versions and report back if this is still an issue for you @slowr ?    I recall from working with the ConsumerMixin that it can be tricky to get past that error -- it might be that you are using heartbeats but not passing that into the Connection, or maybe you are using heartbeats and should try disabling them by setting the value to 0.   Also important I think to on_message implementation to make sure you call message.ack(), stuff like that can matter a lot.  More Info:  https://kombu.readthedocs.io/en/latest/reference/kombu.mixins.html

**Comment by auvipy** [comment]
closing for lack of feedback
