### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by baldman88** [celery/kombu#944]
(.venv) [21:07:57][baldman@bcs-dm][~/projects/py/flaskbb]$ flaskbb makeconfig
Traceback (most recent call last):
  File "/home/baldman/projects/py/flaskbb/.venv/bin/flaskbb", line 11, in <module>
    load_entry_point('FlaskBB', 'console_scripts', 'flaskbb')()
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/baldman/projects/py/flaskbb/flaskbb/__init__.py", line 17, in <module>
    from flaskbb.app import create_app  # noqa
  File "/home/baldman/projects/py/flaskbb/flaskbb/app.py", line 27, in <module>
    from flaskbb.extensions import (alembic, allows, babel, cache, celery, csrf,
  File "/home/baldman/projects/py/flaskbb/flaskbb/extensions.py", line 13, in <module>
    from celery import Celery
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/utils/__init__.py", line 10, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/utils/nodenames.py", line 7, in <module>
    from kombu.entity import Exchange, Queue
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/kombu/connection.py", line 8(.venv) [21:07:57][baldman@bcs-dm][~/projects/py/flaskbb]$ flaskbb makeconfig
Traceback (most recent call last):
  File "/home/baldman/projects/py/flaskbb/.venv/bin/flaskbb", line 11, in <module>
    load_entry_point('FlaskBB', 'console_scripts', 'flaskbb')()
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/baldman/projects/py/flaskbb/flaskbb/__init__.py", line 17, in <module>
    from flaskbb.app import create_app  # noqa
  File "/home/baldman/projects/py/flaskbb/flaskbb/app.py", line 27, in <module>
    from flaskbb.extensions import (alembic, allows, babel, cache, celery, csrf,
  File "/home/baldman/projects/py/flaskbb/flaskbb/extensions.py", line 13, in <module>
    from celery import Celery
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/utils/__init__.py", line 10, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/celery/utils/nodenames.py", line 7, in <module>
    from kombu.entity import Exchange, Queue
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/home/baldman/projects/py/flaskbb/.venv/lib/python3.7/site-packages/kombu/connection.py", line 893
    return self.transport.implements.async
                                         ^
SyntaxError: invalid syntax
(.venv) [21:08:12][baldman@bcs-dm][~/projects/py/flaskbb]$

**Comment by thedrow** [comment]
Python 3.7 is not supported yet.
Please wait for the next release.

**Comment by YingjieQiao** [comment]
Hi can I check if this issue still persists for `celery==4.1.0` version? I installed this version and I'm running the same syntax error.

Thanks.

**Comment by auvipy** [comment]
use latest version of celery==4.4.2 which supports upto 3.8

**Comment by YingjieQiao** [comment]
I have actually set up a python 2 environment to work with celery==4.1.0 and some other libraries that need python2 in the repo, and it works now. Thanks for your reply!
