### ISSUE TITLE
v4.2.2-post1 breaks "reddiss" in TRANSPORT_ALIASES from v.4.2.2

### ISSUE THREAD

**Issue by sbonebrake** [celery/kombu#979]
Release of v4.2.2-post1 does not include PR #910 

```
2019-01-03T18:30:42.7504916Z Traceback (most recent call last):
2019-01-03T18:30:42.7505206Z   File "/usr/local/lib/python3.5/dist-packages/kombu/transport/__init__.py", line 55, in resolve_transport
2019-01-03T18:30:42.7505253Z     transport = TRANSPORT_ALIASES[transport]
2019-01-03T18:30:42.7505418Z KeyError: 'rediss'
2019-01-03T18:30:42.7505492Z 
2019-01-03T18:30:42.7505533Z During handling of the above exception, another exception occurred:
2019-01-03T18:30:42.7505560Z 
2019-01-03T18:30:42.7505595Z Traceback (most recent call last):
2019-01-03T18:30:42.7505675Z   File "/usr/local/bin/flower", line 11, in <module>
2019-01-03T18:30:42.7505871Z     sys.exit(main())
2019-01-03T18:30:42.7506127Z   File "/usr/local/lib/python3.5/dist-packages/flower/__main__.py", line 11, in main
2019-01-03T18:30:42.7506219Z     flower.execute_from_commandline()
2019-01-03T18:30:42.7506469Z   File "/usr/local/lib/python3.5/dist-packages/celery/bin/base.py", line 275, in execute_from_commandline
2019-01-03T18:30:42.7506519Z     return self.handle_argv(self.prog_name, argv[1:])
2019-01-03T18:30:42.7506771Z   File "/usr/local/lib/python3.5/dist-packages/flower/command.py", line 59, in handle_argv
2019-01-03T18:30:42.7506862Z     return self.run_from_argv(prog_name, argv)
2019-01-03T18:30:42.7507097Z   File "/usr/local/lib/python3.5/dist-packages/flower/command.py", line 51, in run_from_argv
2019-01-03T18:30:42.7507292Z     self.print_banner('ssl_options' in settings)
2019-01-03T18:30:42.7507570Z   File "/usr/local/lib/python3.5/dist-packages/flower/command.py", line 144, in print_banner
2019-01-03T18:30:42.7507787Z     logger.info('Broker: %!s(MISSING)', self.app.connection().as_uri())
2019-01-03T18:30:42.7508148Z   File "/usr/local/lib/python3.5/dist-packages/celery/app/base.py", line 793, in connection
2019-01-03T18:30:42.7508240Z     **kwargs
2019-01-03T18:30:42.7508486Z   File "/usr/local/lib/python3.5/dist-packages/celery/app/base.py", line 751, in connection_for_write
2019-01-03T18:30:42.7508532Z     return self._connection(url or self.conf.broker_write_url, **kwargs)
2019-01-03T18:30:42.7508807Z   File "/usr/local/lib/python3.5/dist-packages/celery/app/base.py", line 819, in _connection
2019-01-03T18:30:42.7509004Z     'broker_connection_timeout', connect_timeout
2019-01-03T18:30:42.7509234Z   File "/usr/local/lib/python3.5/dist-packages/kombu/connection.py", line 179, in __init__
2019-01-03T18:30:42.7509323Z     if not get_transport_cls(transport).can_parse_url:
2019-01-03T18:30:42.7509572Z   File "/usr/local/lib/python3.5/dist-packages/kombu/transport/__init__.py", line 83, in get_transport_cls
2019-01-03T18:30:42.7509617Z     _transport_cache[transport] = resolve_transport(transport)
2019-01-03T18:30:42.7509922Z   File "/usr/local/lib/python3.5/dist-packages/kombu/transport/__init__.py", line 63, in resolve_transport
2019-01-03T18:30:42.7509968Z     transport, alt))
```

**Comment by sbonebrake** [comment]
I guess this is related to a bad package in issue #966.  If 4.2.2 was working for you, you can still use it with:
```
pip install -e git://github.com/celery/kombu.git@eded86487e8def549a961fd216b3048f6dd0f0f7#egg=kombu
```
